(function(g){var window=this;'use strict';var R6=function(v){v.publish("cardstatechange",v.Cj()&&v.ZX()?1:0)},lX=function(v,J){var G=g.HF(J),K=G?J:arguments;
for(G=G?0:1;G<K.length;G++){if(v==null)return;v=v[K[G]]}return v},Kc8=function(v){var J=g.dS(v);
v=g.lt(v);return new g.Y3(J.x,J.y,v.width,v.height)},VG8=function(v,J,G){var K=K===void 0?{}:K;
var V;return V=g.RP(v,J,function(){g.l$(V);G.apply(v,arguments)},K)},Lw=function(v){v=g.Cf(v);
delete Tc[v];g.Xb(Tc)&&pw&&pw.stop()},rNU=function(){pw||(pw=new g.Qq(function(){Yd8()},20));
var v=pw;v.isActive()||v.start()},Yd8=function(){var v=g.$X();
g.y2(Tc,function(J){qdL(J,v)});
g.Xb(Tc)||rNU()},yo=function(v,J,G,K){g.ej.call(this);
if(!Array.isArray(v)||!Array.isArray(J))throw Error("Start and end parameters must be arrays");if(v.length!=J.length)throw Error("Start and end points must be the same length");this.X=v;this.K=J;this.duration=G;this.J=K;this.coords=[];this.progress=this.j=0;this.L=null},qdL=function(v,J){J<v.startTime&&(v.endTime=J+v.endTime-v.startTime,v.startTime=J);
v.progress=(J-v.startTime)/(v.endTime-v.startTime);v.progress>1&&(v.progress=1);v.j=1E3/(J-v.L);v.L=J;EuG(v,v.progress);v.progress==1?(v.T=0,Lw(v),v.onFinish(),v.xe()):v.isPlaying()&&v.gb()},EuG=function(v,J){typeof v.J==="function"&&(J=v.J(J));
v.coords=Array(v.X.length);for(var G=0;G<v.X.length;G++)v.coords[G]=(v.K[G]-v.X[G])*J+v.X[G]},eno=function(v,J){g.FM.call(this,v);
this.coords=J.coords;this.x=J.coords[0];this.y=J.coords[1];this.z=J.coords[2];this.duration=J.duration;this.progress=J.progress;this.fps=J.j;this.state=J.T},wV=function(v,J,G,K,V){yo.call(this,J,G,K,V);
this.element=v},Pro=function(v,J,G,K,V){if(J.length!=2||G.length!=2)throw Error("Start and end points must be 2D");
wV.call(this,v,J,G,K,V)},Dvo=function(v){return Math.pow(v,3)},tGG=function(v){return 3*v*v-2*v*v*v},BRS=function(v){g.X.call(this);
this.X=v||window;this.T=[]},OY=function(v){return v.baseUrl||null},UY=function(v,J){return g.E_(g.yn(v,J),function(G){return!!G})},I4F=function(v,J,G){function K(Kf){var j8=Kf.hovercardButton;
if(!j8)return null;j8=j8.subscribeButtonRenderer;if(!j8)return null;var a=Y(j8.unsubscribedButtonText),C=Y(j8.subscribedButtonText);if(j8.subscribed){var d=Y(j8.subscriberCountWithUnsubscribeText);var A=Y(j8.subscriberCountText)}else d=Y(j8.subscriberCountText),A=Y(j8.subscriberCountWithSubscribeText);var cF=null;if(Kf.signinEndpoint){cF=lX(Kf,"signinEndpoint","webNavigationEndpointData","url");if(!cF){var RL,BN;cF=(BN=g.N((RL=j8.signInEndpoint)==null?void 0:RL.commandMetadata,g.Dh))==null?void 0:
BN.url}if(!cF)return null}return a&&(C||cF)?{subscribed:j8.subscribed,subscribeText:a,subscribeCount:d,unsubscribeText:C,unsubscribeCount:A,enabled:j8.enabled,signinUrl:cF,classic:Kf.useClassicSubscribeButton}:null}
function V(Kf){if(Kf){var j8=[],a=Kf.videoId;a&&j8.push("v="+a);(a=Kf.playlistId)&&j8.push("list="+a);(Kf=Kf.startTimeSeconds)&&j8.push("t="+Kf);return"/watch?"+j8.join("&")}}
function Y(Kf){if(!Kf)return null;var j8=Kf.simpleText;return j8?j8:Kf.runs?g.yn(Kf.runs,function(a){return a.text}).join(""):null}
J=J.endscreenElementRenderer;if(!J)return null;var r=J.style,E=J.endpoint||{},e=null,P=null,D=!1,t=null,B=null,I=null,h=null,R=!1,T=null,L=null,O=null,x=null,f=null,c=null;if(r==="VIDEO")g.N(E,g.g8)?e=g.N(E,g.g8).url:(c=g.N(E,g.ig),e=V(c)),P=!1,t=v,J.thumbnailOverlays?(D=J.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,B=Y(D.text),D=D.style==="LIVE"):B=Y(J.videoDuration);else if(r==="PLAYLIST")g.N(E,g.g8)?e=g.N(E,g.g8).url:(c=g.N(E,g.ig),e=V(c)),P=!1,t=v,I=Y(J.playlistLength);else if(r===
"CHANNEL"){if(R=lX(E,"browseEndpoint","browseId"))h=R,e="/channel/"+h;P=!1;t="new";(R=!!J.isSubscribe)?T=K(J):L=Y(J.subscribersText)}else r==="WEBSITE"?((O=lX(E,"urlEndpoint","url"))&&(e=O),P=!0,t="new",O=J.icon.thumbnails[0].url):r==="CREATOR_MERCHANDISE"&&(J.productPrice&&(x=Y(J.productPrice)),J.additionalFeesText&&(f=Y(J.additionalFeesText)),(P=lX(E,"urlEndpoint","url"))&&(e=P),P=!0,t="new");v=lX(J,"title","accessibility","accessibilityData","label");var b=J.endpoint?J.endpoint.clickTrackingParams:
null,M="";if(J.metadata){var Jw=Y(J.metadata);Jw&&(M=Jw)}return{id:"element-"+G,type:r,title:Y(J.title),metadata:M,callToAction:Y(J.callToAction),hO:J.image,iconUrl:O,left:Number(J.left),width:Number(J.width),top:Number(J.top),aspectRatio:Number(J.aspectRatio),startMs:Math.floor(Number(J.startMs)),endMs:Math.floor(Number(J.endMs)),videoDuration:B,vy:D,playlistLength:I,channelId:h,subscribeButton:T,subscribersText:L,isSubscribe:R,targetUrl:e||null,H0t:P,sessionData:b?{itct:b}:null,hZh:t,kE:v?v:null,
isPlaceholder:J.isPlaceholder,impressionUrls:UY(J.impressionUrls||[],OY),xr7:UY(J.hovercardShowUrls||[],OY),clickUrls:UY(E.loggingUrls||[],OY),visualElement:g.lW(J.trackingParams),productPrice:x,additionalFeesText:f,watchEndpoint:c||null}},hnm=function(v,J){var G={startMs:Math.floor(Number(v.startMs)),
impressionUrls:UY(v.impressionUrls||[],OY),elements:UY(v.elements||[],function(K,V){return I4F(J,K,V)})};
v.trackingParams&&(G.visualElement=g.lW(v.trackingParams));return G},znG=function(v){g.YQ.call(this,v);
this.L=this.endscreen=null;this.X={};this.j={};this.J=this.Z=null;this.U=[];this.T=null;this.oY=!0;this.K=0;v=v.B();this.N=g.ZR(v)||g.gU(v);this.events=new g.Zs(this);g.k(this,this.events);this.events.G(this.player,g.VG("creatorendscreen"),this.onCueRangeEnter);this.events.G(this.player,g.YM("creatorendscreen"),this.onCueRangeExit);this.events.G(this.player,"resize",this.E$);this.events.G(window,"focus",this.a6B);this.load();var J=g.qh("STYLE");(g.$t("HEAD")[0]||document.body).appendChild(J);this.addOnDisposeCallback(function(){g.tx(J)});
J.sheet&&(J.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),J.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},nu_=function(v){return v.player.getVideoData().aR?"current":v.N?"new":"current"},xo=function(v){return v.player.B().playerStyle==="creator-endscreen-editor"},dvS=function(v){var J=v.player.getVideoData(),G=J.videoId;
v.L&&v.L.abort();G={method:"POST",onFinish:function(V){var Y=v.L=null;V.status===200&&(V=V.responseText,V.substring(0,3)===")]}"&&(V=V.substring(3),Y=JSON.parse(V),Y=hnm(Y,nu_(v))));me(v,Y)},
urlParams:{v:G},withCredentials:!0};v.N&&(G.urlParams.ptype="embedded");var K=J.vQ;K&&(G.postParams={ad_tracking:K});if(J=g.KXF(J))if(J=g.ca(J),J=g.gR(J))v.L=g.pE(J,G)},me=function(v,J,G){G=G===void 0?!0:G;
v.player.RA("creatorendscreen");v.Z&&(v.Z.dispose(),v.Z=null,v.J.dispose(),v.J=null);for(var K=g.n(Object.values(v.X)),V=K.next();!V.done;V=K.next())V.value.dispose();v.X={};v.j={};v.U.length>0&&(v.U.forEach(function(E){E.dispose()}),v.U.length=0);
v.T&&(g.rz(v.T,"ytp-ce-element-show"),v.T.setAttribute("aria-hidden","true"));v.K=0;if((v.endscreen=J)&&J.elements){G&&szF(v);G=[];K=new g.o8(J.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});G.push(K);v.player.B().X||(v.Z=new g.F({Y:"div",D:"ytp-ce-shadow"}),g.gr(v.player,v.Z.element,4),v.J=new g.Jk(v.Z,200));for(K=0;K<J.elements.length;++K){V=J.elements[K];var Y=Rno(v,V);if(Y){v.X[V.id]=Y;v.j[V.id]=V;g.gr(v.player,Y.element,4);var r=new g.o8(V.startMs,V.endMs,{id:"ytp-ce-element-"+
V.id,namespace:"creatorendscreen"});G.push(r);l4Y(v,Y,V)}else g.Zl(new g.Mk("buildEndscreenElement null",V))}v.player.oR(G);v.E$()}},szF=function(v){var J=g.pW(),G=g.LW();
G&&J&&v.endscreen.visualElement&&g.jk(g.QV)(void 0,G,J,v.endscreen.visualElement)},Rno=function(v,J){var G=null;
switch(J.type){case "VIDEO":v={Y:"div",n7:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":J.kE||"","aria-hidden":"true"},W:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-covering-image",V:SJ(J)},{Y:"div",D:"ytp-ce-covering-shadow-top"},{Y:"a",D:"ytp-ce-covering-overlay",V:{href:fw(v,J.targetUrl),tabindex:"-1"},W:[{Y:"div",n7:["ytp-ce-video-title","ytp-webkit-ellipsis"],V:{dir:g.I9(J.title||"")},At:J.title},{Y:"div",D:J.vy?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
At:J.videoDuration||void 0}]}]};G=new g.F(v);break;case "PLAYLIST":v={Y:"div",n7:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":J.kE||"","aria-hidden":"true"},W:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-covering-image",V:SJ(J)},{Y:"div",D:"ytp-ce-covering-shadow-top"},{Y:"a",D:"ytp-ce-covering-overlay",V:{href:fw(v,J.targetUrl),tabindex:"-1"},W:[{Y:"div",n7:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],V:{dir:g.I9(J.title||"")},At:J.title},{Y:"div",D:"ytp-ce-playlist-count",
W:[{Y:"div",D:"ytp-ce-playlist-icon"},{Y:"div",D:"ytp-ce-playlist-count-text",At:J.playlistLength||void 0}]}]}]};G=new g.F(v);break;case "CHANNEL":G={Y:"div",n7:["ytp-ce-element","ytp-ce-channel",J.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":J.kE||"","aria-hidden":"true"},W:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-expanding-overlay",W:[{Y:"div",D:"ytp-ce-expanding-overlay-hider"},{Y:"div",D:"ytp-ce-expanding-overlay-background"},{Y:"div",D:"ytp-ce-expanding-overlay-content",
W:[{Y:"div",D:"ytp-ce-expanding-overlay-body",W:[{Y:"div",D:"ytp-ce-expanding-overlay-body-padding",W:[{Y:"a",n7:["ytp-ce-channel-title","ytp-ce-link"],V:{href:fw(v,J.targetUrl),target:"_blank",tabindex:"-1",dir:g.I9(J.title||"")},At:J.title},J.subscribeButton?{Y:"div",D:"ytp-ce-subscribe-container",W:[{Y:"div",D:"ytp-ce-channel-subscribe"}]}:"",J.subscribersText?{Y:"div",D:"ytp-ce-channel-subscribers-text",At:J.subscribersText}:"",J.metadata?{Y:"div",n7:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],At:J.metadata}:""]}]}]}]},{Y:"div",D:"ytp-ce-expanding-image",V:SJ(J)}]};G=new g.F(G);var K=g.Jx(document,"div","ytp-ce-channel-subscribe",G.element)[0];if(J.subscribeButton&&J.channelId){g.Vj(K,"ytp-ce-subscribe-button");if(v.player.B().X){var V=null;var Y=J.sessionData.itct}else V="endscreen",Y=null;V=new g.cv(J.subscribeButton.subscribeText,J.subscribeButton.subscribeCount,J.subscribeButton.unsubscribeText,J.subscribeButton.unsubscribeCount,!!J.subscribeButton.enabled,!!J.subscribeButton.classic,
J.channelId,!!J.subscribeButton.subscribed,V,Y,v.player,!1);K.appendChild(V.element);v.U.push(V)}break;case "WEBSITE":v={Y:"div",n7:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":J.kE||"","aria-hidden":"true"},W:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-expanding-overlay",W:[{Y:"div",D:"ytp-ce-expanding-overlay-hider"},{Y:"div",D:"ytp-ce-expanding-overlay-background"},{Y:"div",D:"ytp-ce-expanding-overlay-content",W:[{Y:"div",D:"ytp-ce-expanding-overlay-body",W:[{Y:"div",
D:"ytp-ce-expanding-overlay-body-padding",W:[{Y:"div",D:"ytp-ce-website-title",V:{dir:g.I9(J.title||"")},At:J.title},{Y:"div",D:"ytp-ce-website-metadata",At:J.metadata},{Y:"a",n7:["ytp-ce-website-goto","ytp-ce-link"],V:{href:fw(v,J.targetUrl),target:"_blank",tabindex:"-1"},At:J.callToAction}]}]}]}]},{Y:"div",D:"ytp-ce-expanding-image",V:SJ(J)},{Y:"div",D:"ytp-ce-expanding-icon",V:TRG(J.iconUrl)}]};G=new g.F(v);break;case "CREATOR_MERCHANDISE":G="",J.productPrice&&(G={Y:"div",D:"ytp-ce-merchandise-price-container",
W:[{Y:"div",D:"ytp-ce-merchandise-price",At:J.productPrice}]},J.additionalFeesText&&G.W.push({Y:"div",D:"ytp-ce-merchandise-additional-fees",At:J.additionalFeesText})),v={Y:"div",n7:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":J.kE||"","aria-hidden":"true"},W:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-expanding-overlay",W:[{Y:"div",D:"ytp-ce-expanding-overlay-hider"},{Y:"div",D:"ytp-ce-expanding-overlay-background"},{Y:"div",D:"ytp-ce-expanding-overlay-content",
W:[{Y:"div",D:"ytp-ce-expanding-overlay-body",W:[{Y:"div",D:"ytp-ce-expanding-overlay-body-padding",W:[{Y:"div",D:"ytp-ce-merchandise-title",V:{dir:g.I9(J.title||"")},At:J.title},G,{Y:"div",D:"ytp-ce-merchandise-metadata",At:J.metadata},{Y:"a",n7:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:fw(v,J.targetUrl),target:"_blank",tabindex:"-1"},At:J.callToAction}]}]}]}]},{Y:"div",D:"ytp-ce-expanding-image",V:SJ(J)},{Y:"div",D:"ytp-ce-merchandise-invideo-cta-container",W:[{Y:"div",D:"ytp-ce-merchandise-invideo-cta",
At:J.callToAction||void 0}]}]},G=new g.F(v)}J.isPlaceholder&&g.Vj(G.element,"ytp-ce-placeholder");return G},SJ=function(v){if(v.hO)var J=v.hO.thumbnails;
return TRG(J?J[J.length-1].url:null)},TRG=function(v){return v?{style:"background-image: url("+v+")"}:{}},l4Y=function(v,J,G){function K(e){e&&(J.listen("blur",function(){e.style.display!="none"&&v.oY&&e.focus()}),J.G(e,"focus",Y),J.G(e,"blur",r))}
function V(e){v.K+=e;v.K>0?(g.Vj(J.element,"ytp-ce-force-expand"),ZX(v,G.id,!0)):(g.rz(J.element,"ytp-ce-force-expand"),g.rz(J.element,"ytp-ce-element-hover"),ZX(v,G.id,!1))}
function Y(){V(1)}
function r(){V(-1)}
J.listen("mouseenter",function(){pa6(v,J,G)});
J.listen("mouseleave",function(){LcG(v,J,G)});
v.player.B().X||J.listen("click",function(){g.Vj(J.element,"ytp-ce-element-hover")});
J.listen("click",function(e){yNm(v,G,e)});
J.listen("keypress",function(e){yNm(v,G,e)});
J.listen("focus",function(){pa6(v,J,G)});
J.listen("blur",function(){LcG(v,J,G)});
J.listen("touchstart",function(){pa6(v,J,G)});
var E=g.Gs("ytp-ce-expanding-overlay-hider",J.element);E&&J.G(E,"touchstart",function(e){e.stopPropagation();g.rz(J.element,"ytp-ce-element-hover");g.rz(J.element,"ytp-ce-force-expand")});
J.listen("keydown",function(e){v.oY=e.keyCode===9&&!e.shiftKey});
K(g.Gs("ytp-sb-subscribe",J.element));K(g.Gs("ytp-sb-unsubscribe",J.element));J.listen("focus",Y);J.listen("blur",r)},yNm=function(v,J,G){if(J.targetUrl&&(!G||G.type!=="keypress"||G.keyCode===13)){for(var K=G.target;K&&!g.K7(K,"ytp-ce-element");){g.K7(K,"subscribe-label")&&waF(v,J);
if(g.K7(K,"ytp-ce-channel-subscribe"))return;K=K.parentElement||null}if(!K||g.K7(K,"ytp-ce-element-hover")){G.preventDefault();G.stopPropagation();if(K=v.X[J.id])LcG(v,K,J),K.element.blur();if(G.ctrlKey||G.metaKey||J.hZh==="new")waF(v,J),v.player.sendVideoStatsEngageEvent(17,void 0),v.player.pauseVideo(),G=g.ca(fw(v,J.targetUrl)),G=g.gR(G),g.Ak(G,void 0,J.sessionData);else{var V=g.bh(v.player.B())||v.player.getVideoData().aR,Y=function(){var r=fw(v,J.targetUrl),E=J.sessionData,e=J.watchEndpoint,P=
g.oS(r);V&&P&&(P.v||P.list)?v.player.Gx(P.v,E,P.list,!1,void 0,e||void 0):g.aA(r,E)};
waF(v,J,function(){v.player.sendVideoStatsEngageEvent(17,Y)})}}}},fw=function(v,J){v=v.player.B();
if(J){if(J.startsWith("//"))return v.protocol+":"+J;if(J.startsWith("/"))return g.oG(v)+J}else return"";return J},pa6=function(v,J,G){g.K7(J.element,"ytp-ce-element-hover")||(G.type==="VIDEO"||G.type==="PLAYLIST"?g.Vj(J.element,"ytp-ce-element-hover"):v.player.B().X?(new g.Qq(function(){g.Vj(J.element,"ytp-ce-element-hover")},200)).start():g.Vj(J.element,"ytp-ce-element-hover"),uX(v,G.xr7),ZX(v,G.id,!0))},LcG=function(v,J,G){g.rz(J.element,"ytp-ce-element-hover");
g.rz(J.element,"ytp-ce-force-expand");ZX(v,G.id,!1)},ZX=function(v,J,G){v.Z&&(G?v.J.show():v.J.hide());
for(var K=g.n(Object.keys(v.X)),V=K.next();!V.done;V=K.next())V=V.value,V!==J&&g.E3(v.X[V].element,"ytp-ce-element-shadow-show",G)},uX=function(v,J,G){function K(){Y||(V++,V===J.length&&(r.stop(),G&&G()))}
if(!J||J.length===0||xo(v))G&&G();else{J=O_T(v,J);var V=0,Y=!1,r=new g.Qq(function(){Y=!0;G&&G()},1E3,v);
r.start();for(v=0;v<J.length;v++)g.cO(J[v],K)}},waF=function(v,J,G){uX(v,J.clickUrls,G);
(v=g.LW())&&J.H0t&&g.VF(v,J.visualElement)},O_T=function(v,J){var G=v.player.getVideoData().clientPlaybackNonce;
v=v.player.getCurrentTime().toFixed(2);G={CPN:G,AD_CPN:G,MT:v};v=[];for(var K=0;K<J.length;K++)v.push(UvX(J[K],G));return v},UvX=function(v,J){return v.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(G){var K=unescape(G);
K=K.substring(1,K.length-1);return J[K]?escape(J[K]):G})},xvm=function(v){return typeof v==="string"?v:""},gV=function(v,J,G){for(var K in J)if(J[K]===v)return v;
return G},mvY=function(v,J,G,K){this.value=v;
this.target=J;this.showLinkIcon=G;this.T=K},X3=function(v){return v.value?v.value:null},ko=function(v){if(!v)return null;
var J=g.ca(xvm(v.value));J=g.gR(J);if(!J)return null;var G=gV(v.target,SdT,"current");if(G==null)v=null;else{var K=v.show_link_icon;v=new mvY(J,G,K==="true"||K==="false"?K==="true":!0,v.pause_on_navigation!=null?v.pause_on_navigation:!0)}return v},f4X=function(v,J,G){this.type=v;
this.trigger=J;this.url=G},guL=function(v){if(!v)return null;
var J=gV(v.type,Z_L),G=gV(v.trigger,uam);v=v.url;v=Array.isArray(v)&&v.length?v[0]:v;v=ko(v?v:null);return J?new f4X(J,G,v):null},XaF=function(v,J,G,K,V){this.id=v;
this.type=J;this.style=G;this.data=V;this.action=K||[]},kNY=function(v,J){return g.MS(v.action,J)},cNA=function(v,J){this.context=v;
this.T=J},NR_=function(v){return v.customMessage?cC("div","iv-card-message",v.customMessage):""},Nw=function(v,J){v="background-image: url("+v+");";
var G=[];J&&G.push(J);return{Y:"div",D:"iv-card-image",V:{style:v},W:G}},a4Y=function(v){if(!v.metaInfo||v.metaInfo.length===0)return"";
var J=[];v=g.n(v.metaInfo);for(var G=v.next();!G.done;G=v.next())J.push(cC("li","",G.value));return{Y:"ul",D:"iv-card-meta-info",W:J}},cC=function(v,J,G){J?typeof J==="string"?J={"class":J}:Array.isArray(J)&&(J={"class":J.join(" ")}):J={};
J.dir=g.I9(G);return{Y:v,V:J,At:G}},ANL=function(v){if(!v.customMessage)return"";
var J=["iv-card-action","iv-card-primary-link"],G={};v.i5&&(J.push("iv-card-action-icon"),G.style="background-image: url("+v.i5+");");G.dir=g.I9(v.customMessage);var K=[{Y:"span",At:v.customMessage}];v.showLinkIcon&&(K.push("\u00a0"),K.push({Y:"span",D:"iv-card-link-icon"}));return{Y:"div",n7:J,V:G,W:K}},a6=function(v,J,G,K){if(K){J=g.n(J);
for(var V=J.next();!V.done;V=J.next())v.T(V.value,K,G.id,G.sessionData,G.kR.click,5)}},FcA=function(v,J){this.merchant=v;
this.price=J},H_m=function(v){var J;
(J=v)&&!(J=v.length>1?v.charAt(0)==="/"&&v.charAt(1)!=="/":v==="/")&&(J=v.replace(/^(https?:)?\/\//,"").split("/",1),J=!J||J.length<1||!J[0]?[]:J[0].toLowerCase().split(".").reverse(),J=J[0]==="com"&&J[1]==="youtube"||J[0]==="be"&&J[1]==="youtu");return J?v.indexOf("/redirect?")===-1:!1},MGF=function(v,J){return J?J:H_m(v)?"current":"new"},AV=function(v,J){g.X.call(this);
var G=this;this.element=v;this.context=J;this.Nr=!1;this.RY=new Map;this.xB=new Map;this.context.S.addEventListener(g.VG("annotations_module"),function(K){(K=G.RY.get(K))&&K.apply(G)});
this.context.S.addEventListener(g.YM("annotations_module"),function(K){(K=G.xB.get(K))&&K.apply(G)})},F3=function(v,J,G,K,V,Y,r){v.context.T.listen(J,"click",function(E){v.p_(G,K,V,Y||[],r||0,E)});
v.context.T.listen(J,"touchstart",function(){v.Nr=!1});
v.context.T.listen(J,"touchmove",function(){v.Nr=!0})},Qz_=function(v){var J;
return((J=g.N(v,g.g8))==null?0:J.url)?g.N(v,g.g8).url:(v=g.N(v,g.ig))&&v.videoId?(J="/watch?v="+v.videoId,v.playlistId&&(J+="&list="+v.playlistId),v.index&&(J+="&index="+v.index),v.startTimeSeconds&&(J+="&t="+v.startTimeSeconds),J):null},HC=function(v,J,G){return{Gp:(v.impressionLoggingUrlsV2s||[]).map(function(K){return K.baseUrl||""}),
click:(G.loggingUrls||[]).map(function(K){return K.baseUrl||""}),
close:(J.dismissLoggingUrlsV2s||[]).map(function(K){return K.baseUrl||""}),
aM:(J.impressionLoggingUrlsV2s||[]).map(function(K){return K.baseUrl||""}),
JD:(J.clickLoggingUrlsV2s||[]).map(function(K){return K.baseUrl||""})}},WcT=function(v,J,G){AV.call(this,J,G);
var K=this;this.S=v;this.eventId=null;this.d_=this.YB=this.g_=this.Z=this.isInitialized=!1;this.cards=[];this.wh=this.U=this.qr=this.J=this.Gi=this.T=null;this.oY=[];this.Ti=this.K=this.A0=this.Mr=null;this.j=0;this.Ze=new g.Qq(function(){},G.EB.SF?4E3:3E3);
g.k(this,this.Ze);this.WH=new g.Qq(function(){});
g.k(this,this.WH);this.dh=new cNA(G,function(V,Y,r,E,e,P){F3(K,V,Y,r,E,e,P)});
this.N=new g.F({Y:"div",D:"iv-drawer",V:{id:"iv-drawer"},W:[{Y:"div",D:"iv-drawer-header",V:{"aria-role":"heading"},W:[{Y:"span",D:"iv-drawer-header-text"},{Y:"button",n7:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"Hide cards",tabindex:"0"}}]},{Y:"div",D:"iv-drawer-content"}]});g.k(this,this.N);this.L=this.N.element;this.BH=new g.Jk(this.N,330);g.k(this,this.BH);this.o$=g.Gs("iv-drawer-header-text",this.L);this.X=g.Gs("iv-drawer-content",this.L);this.addCueRange(0,G.videoData.lengthSeconds*
1E3,"",function(){K.g_&&Mw(K,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(K.g_=K.Z)&&Qo(K)});
this.jl=new g.Zs(this);g.k(this,this.jl);this.S.addEventListener("videodatachange",this.Q5.bind(this))},CrA=function(v,J){J=J.data;
J.autoOpenMs&&v.addCueRange(J.autoOpenMs,0x8000000000000,"",function(){Mw(v,"YOUTUBE_DRAWER_AUTO_OPEN")});
J.autoCloseMs&&v.addCueRange(J.autoCloseMs,0x8000000000000,"",function(){Qo(v)});
var G=J.headerText;g.In(v.o$,G);v.U&&v.U.setAttribute("title",G);J.eventId&&(v.eventId=J.eventId);v.Mr=g.lW(J.trackingParams);v.K=g.lW(J.closeTrackingParams);v.A0=g.lW(J.iconTrackingParams)},b_L=function(v,J){var G=J.cardId?J.cardId:"cr:"+v.j,K=v.S.B().experiments.OB("enable_error_corrections_infocard_web_client");
if(!J.content&&J.teaser.simpleCardTeaserRenderer&&K){var V=J.teaser.simpleCardTeaserRenderer,Y=J.icon?J.icon.infoCardIconRenderer:null;J={id:G,timestamp:v.j,type:"simple",teaserText:g.h9(V.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),startMs:Number(J.cueRanges[0].startCardActiveMs),autoOpen:!!J.autoOpen,sessionData:{},sponsored:!1,kR:{},LF:null,gG:V.trackingParams?g.lW(V.trackingParams):null,A0:Y&&Y.trackingParams?g.lW(Y.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
i5:null,title:"",customMessage:"",url:null,onClickCommand:V.onTapCommand||null};WC(v,J)}else{var r;if((r=J.content)==null?0:r.simpleCardContentRenderer){if(!J.cueRanges.length)return;Y=(V=J.content)==null?void 0:V.simpleCardContentRenderer;V=J.teaser.simpleCardTeaserRenderer;var E=J.icon?J.icon.infoCardIconRenderer:null;J={id:G,timestamp:v.j,type:"simple",teaserText:g.h9(V.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),startMs:Number(J.cueRanges[0].startCardActiveMs),autoOpen:!!J.autoOpen,
sessionData:Cw(v,G,J,Y),sponsored:!1,kR:HC(Y,V,Y.command),LF:Y.trackingParams?g.lW(Y.trackingParams):null,gG:V.trackingParams?g.lW(V.trackingParams):null,A0:E&&E.trackingParams?g.lW(E.trackingParams):null,imageUrl:bX(Y.image.thumbnails,290).url,displayDomain:Y.displayDomain?g.h9(Y.displayDomain):null,showLinkIcon:!!Y.showLinkIcon,i5:null,title:Y.title?g.h9(Y.title):"",customMessage:Y.callToAction?g.h9(Y.callToAction):"",url:g.N(Y.command,g.g8).url?ko({pause_on_navigation:!v.context.videoData.isLivePlayback,
target:"new",value:g.N(Y.command,g.g8).url}):null,onClickCommand:null};WC(v,J)}else{var e;if((e=J.content)==null?0:e.collaboratorInfoCardContentRenderer){if(!J.cueRanges.length)return;V=(Y=J.content)==null?void 0:Y.collaboratorInfoCardContentRenderer;Y=J.teaser.simpleCardTeaserRenderer;E=J.icon?J.icon.infoCardIconRenderer:null;J={id:G,timestamp:v.j,type:"collaborator",teaserText:g.h9(Y.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),startMs:Number(J.cueRanges[0].startCardActiveMs),
autoOpen:!!J.autoOpen,sessionData:Cw(v,G,J,V),sponsored:!1,kR:HC(V,Y,V.endpoint),LF:V.trackingParams?g.lW(V.trackingParams):null,gG:Y.trackingParams?g.lW(Y.trackingParams):null,A0:E&&E.trackingParams?g.lW(E.trackingParams):null,channelId:g.N(V.endpoint,g.ph).browseId,customMessage:V.customText?g.h9(V.customText):null,profileImageUrl:bX(V.channelAvatar.thumbnails,290).url,title:V.channelName?g.h9(V.channelName):"",metaInfo:[V.subscriberCountText?g.h9(V.subscriberCountText):""],url:ko({pause_on_navigation:!v.context.videoData.isLivePlayback,
target:"new",value:g.N(V.endpoint,g.ph).canonicalBaseUrl?g.N(V.endpoint,g.ph).canonicalBaseUrl:"/channel/"+g.N(V.endpoint,g.ph).browseId}),onClickCommand:null};WC(v,J)}else{var P;if((P=J.content)==null?0:P.playlistInfoCardContentRenderer){if(!J.cueRanges.length)return;V=(E=J.content)==null?void 0:E.playlistInfoCardContentRenderer;Y=J.teaser.simpleCardTeaserRenderer;E=J.icon?J.icon.infoCardIconRenderer:null;J={id:G,timestamp:v.j,type:"playlist",teaserText:g.h9(Y.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),
startMs:Number(J.cueRanges[0].startCardActiveMs),autoOpen:!!J.autoOpen,sessionData:Cw(v,G,J,V),sponsored:!1,kR:HC(V,Y,V.action),LF:V.trackingParams?g.lW(V.trackingParams):null,gG:Y.trackingParams?g.lW(Y.trackingParams):null,A0:E&&E.trackingParams?g.lW(E.trackingParams):null,kd:bX(V.playlistThumbnail.thumbnails,258).url,customMessage:V.customMessage?g.h9(V.customMessage):null,playlistVideoCount:g.h9(V.playlistVideoCount),title:V.playlistTitle?g.h9(V.playlistTitle):"",metaInfo:[V.channelName?g.h9(V.channelName):
"",V.videoCountText?g.h9(V.videoCountText):""],url:ko({pause_on_navigation:!v.context.videoData.isLivePlayback,target:"new",value:Qz_(V.action)}),onClickCommand:null};WC(v,J)}else{var D;if((D=J.content)==null?0:D.videoInfoCardContentRenderer){if(!J.cueRanges.length)return;var t;V=(t=J.content)==null?void 0:t.videoInfoCardContentRenderer;Y=J.teaser.simpleCardTeaserRenderer;E=J.icon?J.icon.infoCardIconRenderer:null;J={id:G,timestamp:v.j,type:"video",teaserText:g.h9(Y.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),
startMs:Number(J.cueRanges[0].startCardActiveMs),autoOpen:!!J.autoOpen,sessionData:Cw(v,G,J,V),sponsored:!1,kR:HC(V,Y,V.action),LF:V.trackingParams?g.lW(V.trackingParams):null,gG:Y.trackingParams?g.lW(Y.trackingParams):null,A0:E&&E.trackingParams?g.lW(E.trackingParams):null,kd:bX(V.videoThumbnail.thumbnails,258).url,videoDuration:V.lengthString?g.h9(V.lengthString):null,customMessage:V.customMessage?g.h9(V.customMessage):null,title:V.videoTitle?g.h9(V.videoTitle):"",metaInfo:[V.channelName?g.h9(V.channelName):
"",V.viewCountText?g.h9(V.viewCountText):""],isLiveNow:!!V.badge,url:ko({pause_on_navigation:!v.context.videoData.isLivePlayback,target:"new",value:Qz_(V.action)}),onClickCommand:null};WC(v,J)}}}}}v.j++},bX=function(v,J){for(var G=-1,K=-1,V=0;V<v.length;V++){if(v[V].height===J||v[V].width===290)return v[V];
((v[V].height||0)<J||(v[V].width||0)<290)&&(G<0||(v[G].height||0)<(v[V].height||0)||(v[G].width||0)<(v[V].width||0))?G=V:((v[V].height||0)>=J||(v[V].width||0)>=290)&&(K<0||(v[K].height||0)>(v[V].height||0)||(v[K].width||0)>(v[V].width||0))&&(K=V)}return v[K>=0?K:G]},Cw=function(v,J,G,K){return{feature:G.feature?G.feature:"cards",
src_vid:v.context.videoData.videoId,annotation_id:J,ei:v.context.videoData.eventId||"",itct:K.trackingParams||""}},ikN=function(v,J){if(J=j7Y(v,J))J===v.T&&(v.T=null),v.S.removeCueRange(J.uQ.id),g.tx(J.DH),g.j5(v.cards,J),v.i$(),jL(v)},Mw=function(v,J,G){if(!v.Z){v.BH.show();
v.Gi=new g.Qq(function(){g.Vj(v.context.S.getRootNode(),g.Hx.IV_DRAWER_OPEN)},0);
v.Gi.start();v.jl.G(v.X,"mousewheel",function(r){v.Ze.start();r.preventDefault();r=r||window.event;var E=0;r.type=="MozMousePixelScroll"?E=0==(r.axis==r.HORIZONTAL_AXIS)?r.detail:0:window.opera?E=r.detail:E=r.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?r.wheelDeltaY/-30:r.wheelDeltaY/-1.2:r.wheelDelta/-1.6:r.wheelDeltaY/-3;if(r=E)v.X.scrollTop+=r});
v.Z=!0;var K=g.LW();K&&v.Mr&&v.K&&g.oK(K,[v.Mr,v.K]);J={TRIGGER_TYPE:J};for(var V=g.n(v.cards),Y=V.next();!Y.done;Y=V.next())Y=Y.value,Y.UL||(Y.UL=!0,$iU(v.context.logger,Y.uQ.kR.Gp,J)),K&&g.oK(K,[Y.uQ.LF]);R6(v.S);G&&(v.J=new g.Qq(function(){v.qr=v.U;v.wh.focus()},330),v.J.start())}},Qo=function(v){v.Z&&(v.BH.hide(),g.O9(v.jl),g.rz(v.context.S.getRootNode(),g.Hx.IV_DRAWER_OPEN),v.Z=!1,R6(v.S),v.J&&v.J.stop(),v.J=new g.Qq(function(){v.qr&&(v.qr.focus(),v.qr=null)},330),v.J.start())},vy6=function(v){g.Yf(v.ZZ(),
[g.Hx.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.gr(v.S,v.L,5);v.jN();v.U=g.Gs("ytp-cards-button",v.S.getRootNode());v.wh=g.Gs("iv-drawer-close-button",v.L);v.isInitialized=!0},JqN=function(v){v.oY.push(g.Kr("iv-teaser-shown",v.Ok,v));
v.oY.push(g.Kr("iv-teaser-hidden",v.YRB,v));v.oY.push(g.Kr("iv-teaser-clicked",v.PB,v));v.d_=!0},GxG=function(v,J){var G;
return J.onClickCommand&&((G=g.N(J.onClickCommand,g.O86))==null?void 0:G.targetId)==="engagement-panel-error-corrections"?(v.Ti=J,!0):!1},oy8=function(v,J){v.Ti=J;
var G=v.S.getVideoData();if(!G)return!1;G=g.yE(G);if(G==null?0:G.markersMap)for(var K,V=0;((K=G)==null?void 0:K.markersMap.length)>V;V++){var Y=void 0,r=(Y=G)==null?void 0:Y.markersMap[V];if(r.key==="ERROR_CORRECTION_MARKERS"&&(Y=void 0,(r=(Y=r.value)==null?void 0:Y.markers)&&r.length>0))return K=void 0,J.startMs=((K=g.N(r[0],g.BV8))==null?void 0:K.timeRangeStartMillis)||0,v.Ti=null,!0}return!1},WC=function(v,J){if(!GxG(v,J)||oy8(v,J)){var G=Kxm(v,J);
if(G){var K={uQ:J,DH:G.element,UL:!1};if(J.onClickCommand)v.S.C("web_infocards_teaser_show_logging_fix")&&(v.d_||JqN(v),ikN(v,J.id),G=v.findLastIndex(K),g.K8(v.cards,G,0,K));else{v.isInitialized||vy6(v);ikN(v,J.id);var V=v.findLastIndex(K);g.K8(v.cards,V,0,K);G.vH(v.X,V);v.i$()}J.autoOpen?v.addCueRange(J.startMs,0x8000000000000,J.id,function(){v.Z||(v.T=K,jL(v),VKT(v,K),Mw(v,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(G=v.context.S.getCurrentTime()*1E3,G<5E3&&G>J.startMs&&YA_(v,K),v.addCueRange(J.startMs,
J.startMs+1,J.id,function(){YA_(v,K)}),jL(v))}}},Kxm=function(v,J){switch(J.type){case "simple":v=v.dh;
var G=J.displayDomain?{Y:"div",D:"iv-card-image-text",At:J.displayDomain}:void 0;var K=ANL(J);G={Y:"div",n7:["iv-card"],W:[{Y:"a",D:"iv-click-target",V:{href:J.url?X3(J.url)||"":""},W:[Nw(J.imageUrl,G),{Y:"div",D:"iv-card-content",W:[cC("h2",void 0,J.title),K]}]}]};G=new g.F(G);a6(v,g.vM("iv-click-target",G.element),J,J.url);J=G;break;case "collaborator":v=v.dh;G={Y:"div",n7:["iv-card","iv-card-channel"],W:[{Y:"a",n7:["iv-click-target"],V:{href:X3(J.url)||"","data-ytid":J.channelId},W:[Nw(J.profileImageUrl),
{Y:"div",D:"iv-card-content",W:[NR_(J),{Y:"h2",D:"iv-card-primary-link",At:J.title},a4Y(J)]}]}]};G=new g.F(G);a6(v,g.vM("iv-click-target",G.element),J,J.url);J=G;break;case "playlist":v=v.dh;G={Y:"div",n7:["iv-card","iv-card-playlist"],W:[{Y:"a",D:"iv-click-target",V:{href:X3(J.url)||""},W:[Nw(J.kd,{Y:"div",D:"iv-card-image-overlay",W:[{Y:"span",D:"iv-card-playlist-video-count",At:J.playlistVideoCount}]}),{Y:"div",D:"iv-card-content",W:[NR_(J),cC("h2","iv-card-primary-link",J.title),a4Y(J)]}]}]};
G=new g.F(G);a6(v,g.vM("iv-click-target",G.element),J,J.url);J=G;break;case "productListing":v=v.dh;var V=J.offers.length!=0;G=["iv-card"];K="";var Y=ANL(J);V&&(G.push("iv-card-product-listing"),K="iv-card-primary-link",Y=J.offers[0],V=[],Y.price&&V.push({Y:"div",D:"iv-card-offer-price",At:Y.price}),Y.merchant&&V.push({Y:"div",D:"iv-card-offer-merchant",At:Y.merchant}),Y={Y:"div",W:V});V=J.url?X3(J.url)||"":"";G={Y:"div",n7:G,V:{tabindex:"0"},W:[{Y:"a",n7:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
J.imageUrl+");",href:V,"aria-hidden":"true",tabindex:"-1"}},{Y:"div",D:"iv-card-content",W:[J.sponsored?{Y:"div",D:"iv-card-sponsored",W:["Sponsored",{Y:"div",D:"iv-ad-info-container",W:[{Y:"div",D:"iv-ad-info",At:"{{adInfo}}"},{Y:"div",D:"iv-ad-info-icon-container",W:[{Y:"div",D:"iv-ad-info-icon"},{Y:"div",D:"iv-ad-info-callout"}]}]}]}:"",{Y:"a",D:"iv-click-target",V:{href:V},W:[cC("h2",K,J.title),Y]}]}]};G=new g.F(G);K=g.qh("span");g.In(K,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
G.H1(K,"adInfo");a6(v,g.vM("iv-click-target",G.element),J,J.url);J=G;break;case "video":v=v.dh;K=J.videoDuration?{Y:"span",D:"iv-card-video-duration",At:J.videoDuration}:void 0;Y=J.isLiveNow?{Y:"span",n7:["yt-badge","yt-badge-live"],At:"LIVE NOW"}:null;V={Y:"div",n7:["iv-card","iv-card-video"],W:[{Y:"a",D:"iv-click-target",V:{href:((G=J.url)==null?void 0:X3(G))||""},W:[Nw(J.kd,K),{Y:"div",D:"iv-card-content",W:[NR_(J),cC("h2","iv-card-primary-link",J.title),a4Y(J),Y]}]}]};G=new g.F(V);a6(v,g.vM("iv-click-target",
G.element),J,J.url);J=G;break;default:return null}return J},rqN=function(v){if(v.T)return v.T.uQ.type==="productListing";
if(v.S.C("enable_wn_infocards")){var J;return!((J=v.cards)==null||!J.length)&&g.wn(v.cards,function(G){return G.uQ.type==="productListing"})}return g.wn(v.cards,function(G){return G.uQ.type==="productListing"})},jL=function(v){g.E3(v.S.getRootNode(),"ytp-cards-shopping-active",rqN(v))},YA_=function(v,J){if(!g.K7(v.S.getRootNode(),"ytp-cards-teaser-shown")){if(v.T!==J){var G=g.LW(),K=v.T?v.T.uQ.A0:v.A0;
G&&K&&g.KR(G,[K]);v.T=J;jL(v)}(G=v.isInitialized&&v.ZZ().style.display=="none")||(G=v.context.S.getPlayerState(),K=G===0&&v.context.S.getCurrentTime()===0,G=!(G===1||G===3||K));G||J.uQ.teaserDurationMs&&v.S.qE(!0,{teaserText:J.uQ.teaserText,durationMs:J.uQ.teaserDurationMs,onClickCommand:J.uQ.onClickCommand});v.WH.isActive()||((!v.Z||!v.Ze.isActive()&&v.YB)&&VKT(v,J),v.WH.start(910+J.uQ.teaserDurationMs))}},VKT=function(v,J){v.N.TG?(J=new yo([0,
v.X.scrollTop],[0,J.DH.offsetTop],600,tGG),v.context.Z.listen(J,"animate",function(G){v.X.scrollTop=G.y}),v.context.Z.listen(J,"finish",function(G){v.X.scrollTop=G.y}),J.play()):(v.N.tP(!0),v.X.scrollTop=J.DH.offsetTop,v.N.tP(!1))},iJ=function(v){return v.T&&v.T.uQ?v.T.uQ:v.cards[0]&&v.cards[0].uQ?v.cards[0].uQ:null},j7Y=function(v,J){return g.MS(v.cards,function(G){return G.uQ.id===J})},$7=function(v,J,G){AV.call(this,v,J);
this.annotation=G;this.isActive=!1},qAG=function(v){var J=v.annotation.data;
"start_ms"in J&&"end_ms"in J&&v.addCueRange(Number(J.start_ms),Number(J.end_ms),v.annotation.id,function(){v.show()},function(){v.hide()})},vP=function(v,J,G){$7.call(this,v,J,G);
this.X=null;this.K=!1;this.Z=null;this.L=!1;this.T=this.j=this.J=null},EyX=function(v,J){var G=G===void 0?0:G;
var K=Kc8(J).width;g.zK(J,K);G=new Pro(J,[K,J.offsetTop],[K-K-G,J.offsetTop],200,Dvo);g.k(v,G);v.context.Z.listen(G,"begin",function(){g.TK(J,!0)});
G.play()},DiU=function(v,J){if(J.channel_name){var G=v.createElement({Y:"div",
n7:["iv-branding-context-name"],At:J.channel_name}),K=v.createElement({Y:"div",n7:["iv-branding-context-subscribe"]}),V=J.standalone_subscribe_button_data;V&&(v.T=new g.cv(V.subscribeText,V.subscribeCount,V.unsubscribeText,V.unsubscribeCount,!!V.enabled,!!V.classic,J.channel_id,!!V.subscribed,V.feature,J.session_data.itct,v.context.S,!1),v.T.vH(K));var Y=v.createElement({Y:"div",n7:["iv-branding-context-subscribe-caret"]}),r=v.createElement({Y:"div",n7:["branding-context-container-inner"]});r.appendChild(Y);
r.appendChild(G);r.appendChild(K);g.TK(r,!1);var E=v.createElement({Y:"div",n7:["branding-context-container-outer"]});E.appendChild(r);g.ep(E,"right",J.image_width+"px");g.eA(v.ZZ(),E);v.Z=new g.Qq(function(){eXN(v,r,E)},500);
g.k(v,v.Z);v.context.T.listen(v.ZZ(),"mouseover",function(){PA6(v,r,E,Y,J.image_height)});
v.context.T.listen(v.ZZ(),"mouseout",function(){v.Z.start()})}},PA6=function(v,J,G,K,V){v.Z.stop();
if(!v.L){var Y=g.lt(J);v.T||(J.style.width=g.h4(Y.width,!0),G.style.width=g.h4(Y.width,!0));g.ep(K,"top",Y.height-Math.max(Math.min(Y.height,V)/2+10,20)+"px");g.ep(K,"right","1px");v.L=!0;g.TK(J,!0);v.J=new g.Qq(function(){g.Vj(this.ZZ(),"iv-branding-active")},0,v);
v.J.start()}},eXN=function(v,J,G){g.rz(v.ZZ(),"iv-branding-active");
v.j=new g.Qq(function(){g.TK(J,!1);v.T||(G.style.width=g.h4(0,!0))},250);
v.j.start();v.L=!1},tK6=function(v,J,G,K,V,Y,r){this.T=v;
this.Z=J;this.EB=G;this.videoData=K;this.logger=V;this.S=Y;this.X=r},BdG=function(v,J,G){$7.call(this,v,J,G);
var K=this;this.U=this.isCollapsed=this.N=!1;this.j=5E3;this.X=this.Z=this.T=this.L=null;this.K=this.createElement({Y:"div",n7:["iv-promo-contents"]});this.J=new g.Qq(function(){K.T.setAttribute("aria-hidden","true");g.TK(K.Z,!1);g.TK(K.X,!0)},700,this);
g.k(this,this.J)},hX8=function(v){var J=v.annotation.data;
if(v.annotation.style==="cta")var G=6;else if(v.annotation.style==="video"||v.annotation.style==="playlist")G=7;v.j=J.collapsedelay_ms||v.j;var K=["iv-promo","iv-promo-inactive"];v.ZZ().setAttribute("aria-hidden","true");v.ZZ().setAttribute("aria-label","Promotion");v.ZZ().tabIndex=0;var V=v.annotation.Dm(),Y=J.image_url;if(Y){var r=v.createElement({Y:"div",n7:["iv-promo-img","iv-click-target"]});Y=v.createElement({Y:"img",V:{src:Y,"aria-hidden":"true"}});r.appendChild(Y);J.video_duration&&!J.is_live?
(Y=v.createElement({Y:"span",D:"iv-promo-video-duration",At:J.video_duration}),r.appendChild(Y)):J.playlist_length&&(Y=v.createElement({Y:"span",D:"iv-promo-playlist-length",At:J.playlist_length.toString()}),r.appendChild(Y));V&&F3(v,r,V,v.annotation.id,J.session_data,void 0,G)}V?(Y=v.createElement({Y:"a",D:"iv-promo-txt"}),g.az(Y,X3(V)),v.T=Y):v.T=v.createElement({Y:"div",D:"iv-promo-txt"});switch(v.annotation.style){case "cta":case "website":var E=v.createElement({Y:"p",W:[{Y:"strong",At:J.text_line_1}]});
var e=v.createElement({Y:"p",W:[{Y:"span",D:"iv-promo-link",At:J.text_line_2}]});if(Y=J.text_line_3){K.push("iv-promo-website-card-cta-redesign");var P=v.createElement({Y:"button",n7:["iv-promo-round-expand-icon","ytp-button"]});Y=v.createElement({Y:"button",n7:["iv-button","iv-promo-button"],W:[{Y:"span",D:"iv-button-content",At:Y}]});var D=v.createElement({Y:"div",D:"iv-promo-button-container"});D.appendChild(Y);V&&F3(v,v.ZZ(),V,v.annotation.id,J.session_data,void 0,G)}g.Vj(v.T,"iv-click-target");
V&&F3(v,v.T,V,v.annotation.id,J.session_data,void 0,G);break;case "playlist":case "video":E=v.createElement({Y:"p",W:[{Y:"span",At:J.text_line_1}]}),e=v.createElement({Y:"p",W:[{Y:"strong",At:J.text_line_2}]}),J.is_live&&(E=e,e=v.createElement({Y:"span",n7:["yt-badge","iv-promo-badge-live"],At:"LIVE NOW"})),g.Vj(v.T,"iv-click-target"),V&&F3(v,v.T,V,v.annotation.id,J.session_data,void 0,G),K.push("iv-promo-video")}E&&v.T.appendChild(E);e&&v.T.appendChild(e);v.K.appendChild(v.T);D&&v.K.appendChild(D);
G=v.createElement({Y:"div",D:"iv-promo-actions"});v.X=v.createElement({Y:"button",n7:["iv-promo-expand","ytp-button"]});v.X.title="Expand";v.context.T.listen(v.X,"click",function(t){IpL(v,5E3,t)});
G.appendChild(v.X);g.TK(v.X,!1);v.context.T.listen(v.ZZ(),"mouseover",v.vBB,v);v.context.T.listen(v.ZZ(),"mouseout",v.Ml4,v);v.context.T.listen(v.ZZ(),"touchend",function(t){IpL(v,5E3,t)});
v.Z=v.createElement({Y:"button",n7:["iv-promo-close","ytp-button"]});v.Z.title="Close";v.context.T.listen(v.Z,"click",v.annotation.style==="cta"&&J.text_line_3?v.drU:v.eUl,v);G.appendChild(v.Z);g.Yf(v.ZZ(),K);r&&(g.eA(v.ZZ(),r),P&&r.appendChild(P));g.eA(v.ZZ(),v.K);g.eA(v.ZZ(),G)},IpL=function(v,J,G){G.stopPropagation();
zX8(v);ny8(v,J);v.T.focus()},dim=function(v){v.isCollapsed||v.U||v.L||(g.Vj(v.ZZ(),"iv-promo-collapsed"),v.isCollapsed=!0,v.J.start())},zX8=function(v){v.J.stop();
v.isCollapsed&&(g.qR(v.ZZ(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),v.isCollapsed=!1,v.T&&v.T.removeAttribute("aria-hidden"),g.TK(v.X,!1),g.TK(v.Z,!0))},ny8=function(v,J){v.L||(v.L=g.gQ(function(){s7T(this);
dim(this)},J,v))},s7T=function(v){v.L&&(g.X2.clearTimeout(v.L),v.L=null)},RXT=function(v){this.S=v},$iU=function(v,J,G){J&&(G?JT(v,J.map(function(K){return g.w0(K,G)})):JT(v,J))},JT=function(v,J,G,K){var V=1,Y=void 0,r=-1;
if(G){var E=!1;Y=function(){V--;V||E||(clearTimeout(r),E=!0,G())};
r=setTimeout(function(){E=!0;G()},1E3)}J=g.n(J||[]);
for(var e=J.next();!e.done;e=J.next())e=e.value,V++,g.cO(e,Y);K&&(V++,K!==0&&v.S.sendVideoStatsEngageEvent(K,Y))},lpX=function(v){g.YQ.call(this,v);
var J=this;this.oY=this.U=!1;this.loadNumber=0;this.j={};this.logger=new RXT(this.player);this.L=new g.Zs(this);this.J=this.K=null;this.events=new g.Zs(this);this.DI=this.N=this.T=null;this.Ti=[];g.k(this,this.L);this.L.G(this.player,"onVideoAreaChange",function(){J.publish("onVideoAreaChange")});
this.L.G(this.player,"onHideControls",function(){J.publish("onHideControls")});
this.L.G(this.player,"onShowControls",function(){J.publish("onShowControls")});
this.L.G(this.player,"resize",function(K){J.publish("resize",K)});
this.L.G(this.player,"presentingplayerstatechange",function(K){J.publish("presentingplayerstatechange",K)});
this.subscribe("presentingplayerstatechange",this.WB,this);this.subscribe("resize",this.aQ,this);this.player.B().qr.subscribe("vast_info_card_add",this.HR,this);g.k(this,this.events);this.dh=this.createElement({Y:"div",D:"video-custom-annotations"});this.X=new g.F({Y:"div",n7:["ytp-player-content","ytp-iv-player-content"]});g.k(this,this.X);g.gr(this.player,this.X.element,4);this.X.hide();this.Z=new g.F({Y:"div",n7:["ytp-iv-video-content"]});g.k(this,this.Z);v=this.createElement({Y:"div",D:"video-annotations"});
v.appendChild(this.dh);this.Z.element.appendChild(v);this.nB()&&this.load();var G=this.createElement({Y:"style"});(g.$t("HEAD")[0]||document.body).appendChild(G);this.addOnDisposeCallback(function(){g.tx(G)});
if(v=G.sheet)v.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),v.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),v.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),v.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),v.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),v.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),v.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),v.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),v.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),v.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},TdY=function(v){v=v.createElement({Y:"div",
n7:["annotation","annotation-type-custom"]});g.TK(v,!1);return v},pRG=function(v,J){J=!J.isCued()&&!g.H(J,1024);
v.X.tP(J);v.Z.tP(J)},LxS=function(v,J,G){v.U=!0;
v.J=g.pE(J,G)},yq_=function(v,J){for(var G={},K=g.n(J.attributes),V=K.next();!V.done;V=K.next())V=V.value,G[V.name]=V.nodeValue;
for(K=0;K<J.childNodes.length;K++)if(V=J.childNodes[K],g.ML(V)&&V.nodeType==1){if(G[V.tagName])var Y=G[V.tagName];else if(V.tagName==="data"){V.childNodes.length>0&&(Y=V.childNodes[0].nodeValue,G[V.tagName]=typeof Y==="string"?Y.trim():Y);continue}else Y=[],G[V.tagName]=Y;V&&V.tagName==="TEXT"?V.childNodes.length===1&&V.childNodes[0].nodeType===3?Y.push(V.childNodes[0].nodeValue):Y.push(""):V&&Y.push(yq_(v,V))}return G},xi6=function(v){var J=v.player.getVideoData();
if(J.BH){var G=v.player.B().qr.get(J.videoId);if(G){var K={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(V,Y,r){V=v.loadNumber;Y=J.videoId;v.loaded&&v.loadNumber===V&&v.player.getVideoData().videoId===Y&&(r=g.th(r)&&r.responseXML?r.responseXML:null)&&wR6(v,r)}};
g.v9()&&(K.onFinish=Okm(v,K.onFinish));K.postParams={ic_only:"1"};Ui8(K,G);v.U=!0;g.pE(J.BH,K)}}},Ui8=function(v,J){v.method="POST";
v.postParams=v.postParams||{};J.ai&&(v.postParams.ic_coll=J.ai);J.G1&&(v.postParams.ic_xml=J.G1);J.G7&&(v.postParams.ic_track=J.G7)},mi_=function(v){var J=new g.F({Y:"div"});
g.TK(J.element,!1);var G=new WcT(v.player,J.element,Gg(v));g.k(G,J);J.vH(v.X.element);G.eW();return G},fpo=function(v,J){var G,K;
if(J=(G=J.getWatchNextResponse())==null?void 0:(K=G.cards)==null?void 0:K.cardCollectionRenderer)v.oY=!0,SA_(v,J),J.headerText&&v.DI&&(G=g.h9(J.headerText),v.DI.setAttribute("title",G))},Gg=function(v){if(!v.N){var J=new BRS(v);
g.k(v,J);var G=new g.ZZ(v);g.k(v,G);v.N=new tK6(J,G,v.player.B(),v.player.getVideoData(),v.logger,v.player,v.b1)}return v.N},wR6=function(v,J){var G=!1,K=J.getElementsByTagName("annotations");
if(K&&!(K.length<1)&&(K=K[0].getAttribute("itct"))){var V=g.LW();if(V){var Y=g.pW();Y&&g.jk(g.MT)(void 0,V,Y,[g.lW(K)])}}J=J.getElementsByTagName("annotation");for(K=0;K<J.length;K++){Y=yq_(v,J[K]);V=null;try{if(Y){var r=Y.id,E=/.+/;var e=typeof r==="string"&&E!=null&&r!=null&&r.match(E)?r:"";var P=gV(Y.type,ZkA),D=gV(Y.style,ubo),t=xvm(Y.data),B=t.length!==0?JSON.parse(t):{};var I=Y.action;Y=guL;if(I==null)var h=null;else if(g.HF(I)){E=[];for(var R=g.n(I),T=R.next();!T.done;T=R.next()){var L=Y(T.value);
L&&E.push(L)}h=E}else{var O=Y(I);h=O?[O]:[]}V=e&&P?new XaF(e,P,D,h,B):null}else V=null}catch(Jw){}if(V)if(V.type==="branding"||V.type==="promotion"){Y=v;E=V;var x=TdY(Y),f=null;switch(E.type){case "branding":if(Y.player.B().Xm)break;Y.X.element.appendChild(x);f=new vP(x,Gg(Y),E);break;case "promotion":g.gr(Y.player,x,4),f=new BdG(x,Gg(Y),E)}f&&f.eW();if(Y=f)g.k(v,Y),v.j[V.id]=Y}else if(V.type==="card"||V.type==="drawer"){v.T||(v.T=mi_(v),g.k(v,v.T));if(V.type==="card"){x=v.T;var c=(G=V)&&G.data&&
G.data.card_type;V=G.data;if(c)switch(Y=V.tracking||{},Y={Gp:Y.impression,click:Y.click,close:Y.close,aM:Y.teaser_impression,JD:Y.teaser_click},E=V.tracking_params||{},f=null,c){case "collaborator":G={id:G.id,timestamp:V.timestamp||0,type:V.card_type,teaserText:V.teaser_text,teaserDurationMs:V.teaser_duration_ms,startMs:V.start_ms,autoOpen:V.auto_open||!1,sessionData:V.session_data||{},sponsored:V.sponsored||!1,kR:Y,LF:E.card?g.lW(E.card):null,gG:E.teaser?g.lW(E.teaser):null,A0:E.icon?g.lW(E.icon):
null,channelId:V.channel_id,customMessage:V.custom_message?V.custom_message:null,profileImageUrl:V.image_url,title:V.title,metaInfo:V.meta_info,url:ko({pause_on_navigation:V.pause_on_navigation,target:V.target||"new",value:V.url}),onClickCommand:null};WC(x,G);break;case "playlist":G={id:G.id,timestamp:V.timestamp||0,type:V.card_type,teaserText:V.teaser_text,teaserDurationMs:V.teaser_duration_ms,startMs:V.start_ms,autoOpen:V.auto_open||!1,sessionData:V.session_data||{},sponsored:V.sponsored||!1,kR:Y,
LF:E.card?g.lW(E.card):null,gG:E.teaser?g.lW(E.teaser):null,A0:E.icon?g.lW(E.icon):null,kd:V.image_url,playlistVideoCount:V.playlist_video_count,customMessage:V.custom_message?V.custom_message:null,title:V.title,metaInfo:V.meta_info,url:ko({pause_on_navigation:V.pause_on_navigation,target:V.target||"new",value:V.url}),onClickCommand:null};WC(x,G);break;case "productListing":V.signin_url&&(f=ko({target:"current",value:V.signin_url}));c=[];for(var b=V.offers||[],M=0;M<b.length;M++)c.push(new FcA(g.Yy(b[M].merchant),
g.Yy(b[M].price)));G={id:G.id,timestamp:V.timestamp||0,type:V.card_type,teaserText:V.teaser_text,teaserDurationMs:V.teaser_duration_ms,startMs:V.start_ms,autoOpen:V.auto_open||!1,sessionData:V.session_data||{},sponsored:V.sponsored||!1,kR:Y,LF:E.card?g.lW(E.card):null,gG:E.teaser?g.lW(E.teaser):null,A0:E.icon?g.lW(E.icon):null,imageUrl:V.image_url,displayDomain:V.display_domain?V.display_domain:null,showLinkIcon:!!V.show_link_icon,i5:V.button_icon_url?V.button_icon_url:null,title:V.title,customMessage:V.custom_message?
V.custom_message:null,url:ko({pause_on_navigation:V.pause_on_navigation,target:V.target||"new",value:V.url}),ZWi:f,pDb:V.signin_title?V.signin_title:void 0,gzU:V.signin_message?V.signin_message:void 0,offers:c,onClickCommand:null};WC(x,G);break;case "simple":G={id:G.id,timestamp:V.timestamp||0,type:V.card_type,teaserText:V.teaser_text,teaserDurationMs:V.teaser_duration_ms,startMs:V.start_ms,autoOpen:V.auto_open||!1,sessionData:V.session_data||{},sponsored:V.sponsored||!1,kR:Y,LF:E.card?g.lW(E.card):
null,gG:E.teaser?g.lW(E.teaser):null,A0:E.icon?g.lW(E.icon):null,imageUrl:V.image_url,displayDomain:V.display_domain?V.display_domain:null,showLinkIcon:!!V.show_link_icon,i5:V.button_icon_url?V.button_icon_url:null,title:V.title,customMessage:V.custom_message?V.custom_message:null,url:ko({pause_on_navigation:V.pause_on_navigation,target:V.target||"new",value:V.url}),onClickCommand:null};WC(x,G);break;case "video":G={id:G.id,timestamp:V.timestamp||0,type:V.card_type,teaserText:V.teaser_text,teaserDurationMs:V.teaser_duration_ms,
startMs:V.start_ms,autoOpen:V.auto_open||!1,sessionData:V.session_data||{},sponsored:V.sponsored||!1,kR:Y,LF:E.card?g.lW(E.card):null,gG:E.teaser?g.lW(E.teaser):null,A0:E.icon?g.lW(E.icon):null,kd:V.image_url,videoDuration:V.video_duration||null,customMessage:V.custom_message?V.custom_message:null,title:V.title,metaInfo:V.meta_info,isLiveNow:!!V.is_live_now,url:ko({pause_on_navigation:V.pause_on_navigation,target:V.target||"new",value:V.url}),onClickCommand:null},WC(x,G)}}else CrA(v.T,V);G=!0}}G&&
(R6(v.player),v.aQ())},SA_=function(v,J){var G=!1;
v.T||(v.T=mi_(v),g.k(v,v.T));for(var K=g.n(J.cards||[]),V=K.next();!V.done;V=K.next())V=V.value,V.cardRenderer&&(b_L(v.T,V.cardRenderer),G=!0);if(G){var Y;(Y=v.player.getVideoData())!=null&&g.mM(Y)||(G=v.T,K=J.headerText?g.h9(J.headerText):"",g.In(G.o$,K),G.U&&G.U.setAttribute("title",K),G.context.videoData.eventId&&(G.eventId=G.context.videoData.eventId),G.Mr=J.trackingParams?g.lW(J.trackingParams):null,G.K=J.closeButton.infoCardIconRenderer.trackingParams?g.lW(J.closeButton.infoCardIconRenderer.trackingParams):
null,G.A0=J.icon.infoCardIconRenderer.trackingParams?g.lW(J.icon.infoCardIconRenderer.trackingParams):null,v.aQ());R6(v.player)}},gy_=function(v,J,G,K,V){if(!v.player.B().Xm){var Y=[];
J.navigationEndpoint&&g.N(J.navigationEndpoint,g.ph)&&g.N(J.navigationEndpoint,g.ph).browseId&&Y.push(new f4X("openUrl","click",new mvY("/channel/"+g.N(J.navigationEndpoint,g.ph).browseId,"new",!0,!0)));var r=J.watermark.thumbnails[0];K={channel_name:J.channelName,end_ms:J.endTimeMs,image_height:r.height,image_type:1,image_url:r.url,image_width:r.width,is_mobile:!1,session_data:{annotation_id:G,ei:V,feature:"iv",itct:J.trackingParams,src_vid:K},start_ms:J.startTimeMs};if(J.subscribeButton&&g.N(J.subscribeButton,
g.Lh)){K.channel_id=g.N(J.subscribeButton,g.Lh).channelId;var E;J=g.N(J.subscribeButton,g.Lh);r=V=null;J.subscribed?(J.subscriberCountWithUnsubscribeText&&(V=g.h9(J.subscriberCountWithUnsubscribeText)),J.subscriberCountText&&(r=g.h9(J.subscriberCountText))):(J.subscriberCountText&&(V=g.h9(J.subscriberCountText)),J.subscriberCountWithSubscribeText&&(r=g.h9(J.subscriberCountWithSubscribeText)));var e,P=((e=g.N((E=J.signInEndpoint)==null?void 0:E.commandMetadata,g.Dh))==null?void 0:e.url)||"";E={subscribeText:g.h9(J.unsubscribedButtonText),
subscribeCount:V||"",unsubscribeText:g.h9(J.subscribedButtonText),unsubscribeCount:r||"",enabled:J.enabled||!1,classic:!1,subscribed:J.subscribed||!1,feature:"iv",signInUrl:P};K.standalone_subscribe_button_data=E}Y=new XaF(G,"branding","branding",Y,K);E=TdY(v);v.X.element.appendChild(E);Y=new vP(E,Gg(v),Y);Y.eW();g.k(Y,Y);v.j[G]=Y}},Okm=function(v,J){return function(){var G=g.Om.apply(0,arguments);
v.Sl()||v.Ti.push(g.cq.eD(function(){J.apply(null,g.l(G))}))}},XRF=function(v){return v==="annotation-editor"||v==="live-dashboard"};
g.wr.prototype.qE=g.rw(45,function(v,J){var G=g.sD(this.c$());G&&G.qE(v,J)});
var Tc={},pw=null;g.Jo(yo,g.ej);g.q=yo.prototype;g.q.getDuration=function(){return this.duration};
g.q.play=function(v){if(v||this.T==0)this.progress=0,this.coords=this.X;else if(this.isPlaying())return!1;Lw(this);this.startTime=v=g.$X();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.L=this.startTime;this.progress||this.KC();this.EV("play");this.isPaused()&&this.EV("resume");this.T=1;var J=g.Cf(this);J in Tc||(Tc[J]=this);rNU();qdL(this,v);return!0};
g.q.stop=function(v){Lw(this);this.T=0;v&&(this.progress=1);EuG(this,this.progress);this.onStop();this.xe()};
g.q.pause=function(){this.isPlaying()&&(Lw(this),this.T=-1,this.EV("pause"))};
g.q.X4=function(){this.T==0||this.stop(!1);this.EV("destroy");yo.Yr.X4.call(this)};
g.q.destroy=function(){this.dispose()};
g.q.gb=function(){this.EV("animate")};
g.q.EV=function(v){this.dispatchEvent(new eno(v,this))};
g.Jo(eno,g.FM);g.Jo(wV,yo);wV.prototype.Z=function(){};
wV.prototype.gb=function(){this.Z();wV.Yr.gb.call(this)};
wV.prototype.xe=function(){this.Z();wV.Yr.xe.call(this)};
wV.prototype.KC=function(){this.Z();wV.Yr.KC.call(this)};
g.Jo(Pro,wV);Pro.prototype.Z=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(BRS,g.X);g.q=BRS.prototype;g.q.listen=function(v,J,G,K){G=(0,g.bj)(G,K||this.X);v=g.RP(v,J,G);this.T.push(v);return v};
g.q.Ud=function(v,J,G,K){G=(0,g.bj)(G,K||this.X);v=VG8(v,J,G);this.T.push(v);return v};
g.q.YL=function(v){g.l$(v);g.j5(this.T,v)};
g.q.removeAll=function(){g.l$(this.T);this.T.length=0};
g.q.X4=function(){this.removeAll();g.X.prototype.X4.call(this)};g.z(znG,g.YQ);g.q=znG.prototype;g.q.load=function(){g.YQ.prototype.load.call(this);if(!xo(this)){var v=g.Vem(this.player.getVideoData());v?(v=hnm(v,nu_(this)),me(this,v,!1)):dvS(this)}};
g.q.unload=function(){me(this,null);this.L&&(this.L.abort(),this.L=null);g.YQ.prototype.unload.call(this)};
g.q.jJ=function(v,J){return xo(this)?v==="loadCustomEndscreenRenderer"?(v=hnm(J,"new"),me(this,v),!0):null:null};
g.q.getOptions=function(){return xo(this)?["loadCustomEndscreenRenderer"]:[]};
g.q.E$=function(){if(this.endscreen&&this.endscreen.elements){var v=this.player.getVideoContentRect();if(v&&v.width!==0&&v.height!==0){var J=this.player.getPlayerSize();if(J&&J.width!==0&&J.height!==0){var G=v.width/v.height;var K=0;for(var V=-1,Y=0;Y<kx8.length;Y++){var r=Math.abs(J.width-kx8[Y]);if(V===-1||K>=r)V=Y,K=r}K=cqU[V];this.Z&&g.ep(this.Z.element,"outline-width",Math.max(J.width,J.height)+"px");for(J=0;J<this.endscreen.elements.length;++J)if(Y=this.endscreen.elements[J].id,V=this.X[Y],
r=this.j[Y],V&&r){var E=r.width*G/r.aspectRatio,e=Math.round(r.width*v.width);Y=Math.round(E*v.height);var P=v.left+Math.round(r.left*v.width),D=v.top+Math.round(r.top*v.height);g.RY(V.element,e,Y);g.zK(V.element,P,D);g.qR(V.element,NdF);e>256||Y>256?g.Vj(V.element,"ytp-ce-large-round"):e>96||Y>96?g.Vj(V.element,"ytp-ce-medium-round"):g.Vj(V.element,"ytp-ce-small-round");g.qR(V.element,apU);e=r.left+r.width/2;r=r.top+E/2;g.Vj(V.element,e<=.5&&r<=.5?"ytp-ce-top-left-quad":e>.5&&r<=.5?"ytp-ce-top-right-quad":
e<=.5&&r>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.qR(V.element,cqU);g.Vj(V.element,K);(V=g.Jx(document,"div","ytp-ce-expanding-overlay-body",V.element)[0])&&g.ep(V,"height",Y+"px")}}}}};
g.q.onCueRangeEnter=function(v){if(this.endscreen)if(v.getId()==="ytp-ce-in-endscreen")uX(this,this.endscreen.impressionUrls),(v=g.LW())&&this.endscreen.visualElement&&g.G8(v,this.endscreen.visualElement),this.T&&(g.Vj(this.T,"ytp-ce-element-show"),this.T.removeAttribute("aria-hidden"),this.player.Cj()?g.Vj(this.T,"ytp-ce-hide-button-lower"):g.rz(this.T,"ytp-ce-hide-button-lower"));else{v=v.getId().substring(15);var J=this.X[v],G=this.j[v];g.Vj(J.element,"ytp-ce-element-show");J.element.removeAttribute("aria-hidden");
J=this.player.getRootNode();g.Vj(J,"ytp-ce-shown");uX(this,G.impressionUrls);(J=g.LW())&&g.G8(J,G.visualElement);this.player.B().K&&this.player.lw("endscreenelementshown",v)}};
g.q.onCueRangeExit=function(v){if(v.getId()==="ytp-ce-in-endscreen")this.T&&(g.rz(this.T,"ytp-ce-element-show"),this.T.setAttribute("aria-hidden","true"));else{v=v.getId().substring(15);var J=this.X[v];g.rz(J.element,"ytp-ce-element-show");J.element.setAttribute("aria-hidden","true");J=this.player.getRootNode();g.rz(J,"ytp-ce-shown");this.player.B().K&&this.player.lw("endscreenelementhidden",v)}};
g.q.a6B=function(v){var J=this;v.target===window&&(new g.Qq(function(){for(var G=g.n(Object.values(J.X)),K=G.next();!K.done;K=G.next())g.qR(K.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.q.tP=function(v){for(var J=g.n(Object.values(this.X)),G=J.next();!G.done;G=J.next())G=G.value,v?G.element.setAttribute("hidden",""):G.element.removeAttribute("hidden")};
g.q.p8B=function(v){this.T&&this.player.getRootNode().removeChild(this.T);v&&(g.Vj(v,"ytp-ce-hide-button-container"),this.T=v,g.gr(this.player,this.T,4))};
var kx8=[346,426,470,506,570,640,853,1280,1920],cqU="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),apU=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],NdF=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var SdT={MFw:"current",hj7:"new"};var Z_L={CLOSE:"close",t_4:"openUrl",SUBSCRIBE:"subscribe"},uam={NPB:"click",CLOSE:"close",nue:"hidden",a8B:"rollOut",V_B:"rollOver",bQr:"shown"};XaF.prototype.Dm=function(){var v=kNY(this,function(J){return J.type==="openUrl"&&J.url!=null});
return v?v.url:null};
var ubo={Xoi:"anchored",Zf:"branding",CHANNEL:"channel",Zj4:"cta",qA7:"highlightText",cSB:"label",PLAYLIST:"playlist",POPUP:"popup",ZQ7:"speech",SUBSCRIBE:"subscribe",JJe:"title",VIDEO:"video",Xai:"website"},ZkA={Zf:"branding",BPi:"card",Kc4:"drawer",yV7:"highlight",C2e:"marker",kx4:"promotion",TEXT:"text",rwY:"widget"};g.z(AV,g.X);g.q=AV.prototype;g.q.addCueRange=function(v,J,G,K,V){v=new g.o8(v,J,{id:G,namespace:"annotations_module"});K&&this.RY.set(v,K);V&&this.xB.set(v,V);this.context.S.oR([v],1)};
g.q.eW=function(){this.context.X.subscribe("resize",this.i$,this)};
g.q.ZZ=function(){return this.element};
g.q.p_=function(v,J,G,K,V,Y){if(this.Nr)return!1;Y&&(Y.stopPropagation(),Y.preventDefault());this.navigate(v,G,K,V);return!1};
g.q.show=function(){};
g.q.hide=function(){};
g.q.destroy=function(){g.tx(this.ZZ())};
g.q.i$=function(){};
g.q.navigate=function(v,J,G,K){var V=this,Y=X3(v);if(Y){var r=MGF(Y,v.target),E=function(){v.T&&V.context.S.pauseVideo();var e=V.context.videoData.aR||!1,P=g.oS(Y||"");e&&P&&(P.v||P.list)?V.context.S.Gx(P.v,J,P.list,!1):g.Ak(Y||"",r==="current"?"_top":void 0,J)};
r==="new"&&(E(),E=null);JT(this.context.logger,G,E,K);H_m(Y)||(G=g.LW(),K=J.itct,G&&K&&g.VF(G,g.lW(K)))}};
g.q.X4=function(){this.RY.clear();this.xB.clear();g.X.prototype.X4.call(this)};
g.q.createElement=function(v){v=new g.F(v);g.k(this,v);return v.element};g.z(WcT,AV);g.q=WcT.prototype;g.q.Q5=function(){this.Ti&&WC(this,this.Ti)};
g.q.isAvailable=function(){var v;if(v=!!this.cards.length)(v=this.S.getRootNode())?(v=g.lt(v),v=173<v.width&&173<v.height):v=!1;return v};
g.q.i$=function(){var v=this.isAvailable();g.TK(this.ZZ(),v);g.E3(this.context.S.getRootNode(),g.Hx.IV_DRAWER_ENABLED,v);R6(this.S)};
g.q.destroy=function(){this.S.qE(!1);try{this.S.getRootNode().removeChild(this.L)}catch(v){}g.Vy(this.oY);g.O9(this.jl);this.Gi&&this.Gi.dispose();this.J&&this.J.dispose();AV.prototype.destroy.call(this)};
g.q.jN=function(){var v=this;this.context.T.listen(g.Gs("iv-drawer-close-button",this.L),"click",this.ex,this);this.context.T.listen(this.X,"touchend",function(){v.Ze.start()});
this.context.T.listen(this.X,"scroll",this.rz,this);this.context.X.subscribe("onHideControls",function(){v.YB=!0});
this.context.X.subscribe("onShowControls",function(){v.YB=!1});
this.context.X.subscribe("onVideoAreaChange",function(){v.YB=g.K7(v.S.getRootNode(),"ytp-autohide")});
this.oY.push(g.Kr("iv-button-shown",this.nyB,this));this.oY.push(g.Kr("iv-button-hidden",this.LkY,this));JqN(this)};
g.q.findLastIndex=function(v){if(this.cards.length===0)return 0;var J=g.QY(this.cards,function(G){return v.uQ.startMs>G.uQ.startMs||v.uQ.startMs===G.uQ.startMs&&v.uQ.timestamp>=G.uQ.timestamp?!0:!1});
return J===-1?0:J+1};
g.q.ex=function(){if(this.Z){JT(this.context.logger,iJ(this).kR.close);var v=g.LW();v&&this.K&&g.VF(v,this.K);Qo(this)}};
g.q.rz=function(){g.E3(this.L,"iv-drawer-scrolled",this.X.scrollTop>0)};
g.q.nyB=function(){var v=g.LW(),J=iJ(this);J=J?J.A0:this.A0;v&&J&&g.oK(v,[J])};
g.q.LkY=function(){var v=g.LW(),J=iJ(this);J=J?J.A0:this.A0;v&&J&&g.KR(v,[J])};
g.q.Ok=function(){var v=iJ(this);JT(this.context.logger,v.kR.aM);var J=g.LW();if(J&&v)if(this.S.C("web_infocards_teaser_show_logging_fix")){var G=[];v.gG&&G.push(v.gG);v.A0&&G.push(v.A0);G.length>0&&g.oK(J,G)}else g.oK(J,[v.gG,v.A0])};
g.q.YRB=function(){var v=g.LW(),J=iJ(this);v&&J&&g.KR(v,[J.gG])};
g.q.PB=function(v){var J=iJ(this),G=g.LW();this.T?v?(v=this.context.logger,JT(v,J.kR.JD),v.S.sendVideoStatsEngageEvent(4,void 0),G&&J.gG&&g.VF(G,J.gG)):(v=this.context.logger,JT(v,J.kR.JD),v.S.sendVideoStatsEngageEvent(4,void 0),G&&J.A0&&g.VF(G,J.A0)):(v=this.context.logger,JT(v,J.kR.JD),v.S.sendVideoStatsEngageEvent(4,void 0),G&&this.A0&&g.VF(G,this.A0))};g.z($7,AV);$7.prototype.eW=function(){AV.prototype.eW.call(this);qAG(this)};
$7.prototype.show=function(){AV.prototype.show.call(this);var v=g.LW(),J=this.annotation.data;v&&J&&(J=J.session_data)&&g.oK(v,[g.lW(J.itct)])};
$7.prototype.hide=function(){AV.prototype.hide.call(this);var v=g.LW(),J=this.annotation.data;v&&J&&(J=J.session_data)&&g.KR(v,[g.lW(J.itct)])};g.z(vP,$7);
vP.prototype.show=function(){if(!this.isActive){$7.prototype.show.call(this);if(!this.K){g.Vj(this.ZZ(),"iv-branding");var v=this.annotation.data;this.X=this.createElement({Y:"img",n7:["branding-img","iv-click-target"],V:{"aria-label":"Channel watermark",src:v.image_url,width:v.image_width,height:v.image_height}});g.TK(this.X,!1);var J=this.createElement({Y:"button",n7:["branding-img-container","ytp-button"]});J.appendChild(this.X);this.ZZ().appendChild(J);var G=this.annotation.Dm();G&&F3(this,J,
G,this.annotation.id,v.session_data);this.context.S.C("disable_branding_context")||DiU(this,v);this.K=!0}g.TK(this.ZZ(),!0);this.isActive=!0;if(this.X){try{EyX(this,this.X)}catch(K){}g.Vj(this.context.S.getRootNode(),"ytp-branding-shown");this.context.S.getRootNode().style.setProperty("--branding-image-width",this.X.getAttribute("width")+"px")}}};
vP.prototype.hide=function(){this.isActive&&($7.prototype.hide.call(this),g.TK(this.ZZ(),!1),this.isActive=!1,g.rz(this.context.S.getRootNode(),"ytp-branding-shown"))};
vP.prototype.destroy=function(){this.T&&(this.T.dispose(),this.T=null);g.rz(this.context.S.getRootNode(),"ytp-branding-shown");$7.prototype.destroy.call(this)};g.z(BdG,$7);g.q=BdG.prototype;g.q.show=function(){this.isActive||($7.prototype.show.call(this),this.N||(hX8(this),this.N=!0),g.TK(this.ZZ(),!0),g.gQ(function(){g.rz(this.ZZ(),"iv-promo-inactive")},100,this),this.ZZ().removeAttribute("aria-hidden"),this.isActive=!0,s7T(this),zX8(this),ny8(this,this.j))};
g.q.hide=function(){this.isActive&&(g.Vj(this.ZZ(),"iv-promo-inactive"),this.isActive=!1,this.ZZ().setAttribute("aria-hidden","true"))};
g.q.p_=function(v,J,G,K,V,Y){return this.isCollapsed?!1:$7.prototype.p_.call(this,v,J,G,K,V,Y)};
g.q.vBB=function(v){this.U=!0;IpL(this,500,v)};
g.q.Ml4=function(){this.U=!1;dim(this)};
g.q.eUl=function(v){v.stopPropagation();this.hide()};
g.q.drU=function(v){v.stopPropagation();s7T(this);this.isCollapsed=!0;g.Vj(this.ZZ(),"iv-promo-collapsed-no-delay");this.J.start()};
g.q.destroy=function(){this.J.dispose();$7.prototype.destroy.call(this)};g.z(lpX,g.YQ);g.q=lpX.prototype;g.q.jJ=function(v,J){if(!XRF(this.player.B().playerStyle))return null;switch(v){case "loadCustomAnnotationsXml":return(v=g.NF(J))&&wR6(this,v),!0;case "removeCustomAnnotationById":return J&&this.T&&(ikN(this.T,J),R6(this.player)),!0}return null};
g.q.getOptions=function(){return XRF(this.player.B().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.q.nB=function(){var v=this.player.B(),J=this.player.getVideoData(),G=v.annotationsLoadPolicy||J.annotationsLoadPolicy;return g.GT(J)||this.player.isMutedByEmbedsMutedAutoplay()?!1:G===1&&!J.N3||v.qr.get(J.videoId)||g.S0(J)||g.fh(J)?!0:!1};
g.q.aQ=function(){if(this.Z){var v=this.player.f7().getVideoContentRect(!0);g.RY(this.Z.element,v.width,v.height);g.zK(this.Z.element,v.left,v.top)}if(this.T){var J=this.player.Tg();v=this.T;J=J.width;g.E3(v.L,"iv-drawer-small",J<=426);g.E3(v.L,"iv-drawer-big",J>=1280)}};
g.q.WB=function(v){pRG(this,v.state);g.H(v.state,2)&&(this.Cj()&&this.ZX()&&this.player.getPresentingPlayerType()!==2&&this.SB(!1),this.qE(!1))};
g.q.load=function(){function v(r){var E=J.loadNumber;J.J=null;J.loaded&&J.loadNumber===E&&J.player.getVideoData().videoId===K&&(r=g.th(r)&&r.responseXML?r.responseXML:null)&&(wR6(J,r),g.Vj(J.player.getRootNode(),"iv-module-loaded"))}
var J=this;g.YQ.prototype.load.call(this);pRG(this,this.player.getPlayerStateObject());this.loadNumber++;var G=this.player.getVideoData(),K=G.videoId;g.v9()&&(v=Okm(this,v));var V={format:"XML",onFinish:v,onError:function(){J.J=null},
urlParams:{}};G.isPharma&&(V.urlParams.pharma="1");V.method="POST";V.withCredentials=!0;var Y=this.player.B().qr.get(K);Y&&Ui8(V,Y);Y=Y&&(Y.G1||Y.ai);if(!G.TE||Y)G.BH?LxS(this,G.BH,V):(this.K=function(){if(!J.U)J.onVideoDataChange(V);var r=J.player.getVideoData();(r==null?0:g.mM(r))&&!J.oY&&fpo(J,r)},this.player.addEventListener("videodatachange",this.K));
g.gr(this.player,this.Z.element,4);this.aQ();(Y=g.S0(G))&&SA_(this,Y);(Y=g.fh(G))&&Y.featuredChannel&&gy_(this,Y.featuredChannel,Y.annotationId||"branding",G.videoId||null,G.eventId||null);this.DI=g.Gs("ytp-cards-button",this.player.getRootNode());g.mM(G)&&fpo(this,G)};
g.q.onVideoDataChange=function(v){var J=this.player.getVideoData();J.BH&&LxS(this,J.BH,v)};
g.q.unload=function(){this.player.RA("annotations_module");for(var v=g.n(Object.keys(this.j)),J=v.next();!J.done;J=v.next())this.j[J.value].destroy();this.N=null;this.T&&(this.T.destroy(),this.T=null,R6(this.player));this.U=!1;this.J&&(this.J.abort(),this.J=null);this.oY=!1;this.j={};this.X.hide();g.YQ.prototype.unload.call(this);this.Z.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.q.HR=function(v){v===this.player.getVideoData().videoId&&(this.loaded?xi6(this):this.load())};
g.q.Cj=function(){var v;return((v=this.T)==null?void 0:v.isAvailable())||this.oY};
g.q.ZX=function(){return!!this.T&&this.T.Z};
g.q.SB=function(v,J,G){J=J===void 0?!1:J;this.Cj();this.T&&(v?G?Mw(this.T,G,J):Mw(this.T,"YOUTUBE_DRAWER_AUTO_OPEN",J):Qo(this.T))};
g.q.qE=function(v,J){this.player.publish(v?"cardsteasershow":"cardsteaserhide",J)};
g.q.X4=function(){this.player.B().qr.unsubscribe("vast_info_card_add",this.HR,this);g.rz(this.player.getRootNode(),g.Hx.IV_DRAWER_OPEN);for(var v=this.Ti,J=g.cq,G=0,K=v.length;G<K;G++)J.GH(v[G]);this.Ti.length=0;g.YQ.prototype.X4.call(this)};
g.q.createElement=function(v){v=new g.F(v);g.k(this,v);return v.element};g.Vp("annotations_module",lpX);g.Vp("creatorendscreen",znG);})(_yt_player);
