(function(g){var window=this;'use strict';var HkL=function(v,J,G){g.m(function(K){v.T=g.pE(J,G);g.zX(K)})},oa=function(v){v.isActive()||v.start()},MKY=function(v,J){return J?v.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Q7X=function(v){return g.bh(v)||v.C("web_enable_caption_language_preference_stickiness")},Wx8=function(v,J){var G=new g.tW;
G.languageCode=v.languageCode;G.languageName=v.languageName;G.name=v.name;G.displayName=v.displayName;G.kind=v.kind;G.isDefault=!1;G.T=v.T;G.isTranslateable=v.isTranslateable;G.vssId=v.vssId;G.url=v.url;G.translationLanguage=J;v.xtags&&(G.xtags=v.xtags);v.captionId&&(G.captionId=v.captionId);return G},CAA=function(v,J){var G,K,V;
return g.m(function(Y){if(Y.T==1)return G=v+"|"+J,g.U(Y,g.jg(),2);if(Y.T!=3){K=Y.X;if(!K)throw g.sT("gct");return g.U(Y,g.m6(K),3)}V=Y.X;return Y.return(V.get("captions",G))})},bko=function(v,J,G){CAA(v,J).then(function(K){K&&G(K.trackData,new g.tW(K.metadata))})},$h8=function(v){if(!jnT.test(v))throw Error("'"+v+"' is not a valid hex color");
v.length==4&&(v=v.replace(iIG,"#$1$1$2$2$3$3"));v=v.toLowerCase();v=parseInt(v.slice(1),16);return[v>>16,v>>8&255,v&255]},vtL=function(){var v=void 0;
v=v===void 0?{}:v;var J="suggest_correction"in g.sEN?g.sEN.suggest_correction:"Edit caption";J=J||"";var G={},K;for(K in v){G={jE:G.jE};G.jE=K;var V=function(Y){return function(){return String(v[Y.jE])}}(G);
J=J.replace(new RegExp("\\$\\{"+G.jE+"\\}","gi"),V);J=J.replace(new RegExp("\\$"+G.jE,"gi"),V)}return J},JxA=function(){return g.fq("yt-player-caption-display-settings")},KK=function(){this.segments=[]},Gsm=function(v,J){var G=g.YY(v.segments,J);
G>=0||G<0&&(-G-1)%2===1||(G=-G-1,G>0&&J-v.segments[G-1]===1&&G<v.segments.length&&v.segments[G]-J===1?(g.bU(v.segments,G),g.bU(v.segments,G-1)):G>0&&J-v.segments[G-1]===1?v.segments[G-1]=J:G<v.segments.length&&v.segments[G]-J===1?v.segments[G]=J:(g.K8(v.segments,G,0,J),g.K8(v.segments,G+1,0,J)))},otG=function(v,J,G,K,V,Y){g.X.call(this);
this.policy=v;this.player=J;this.oY=G;this.U=K;this.J=V;this.N=Y;this.L=new KK;this.j=-1;this.Z=this.X=this.T=null;this.Ti=0;this.K=new g.Qq(this.Jq,1E3,this);this.events=new g.Zs(this);g.k(this,this.K);g.k(this,this.events);this.events.G(J,"SEEK_COMPLETE",this.Wm);this.Wm();this.Jq()},K2m=function(v){return v.T&&v.T.j?v.T.j+v.player.B$()<v.player.getCurrentTime():!1},VAF=function(v,J){if(v.policy.IE&&v.player.Md()){var G=g.Af(J,v.policy,{});
G.set("pot",v.player.Md());G=G.Dm()}else G=g.Af(J,v.policy,{}).Dm();var K={format:"RAW",withCredentials:!0};if(v.policy.qr){K.method="POST";var V=J.L;V&&Object.keys(V).length>0?K.postBody=g.Cp(V,g.vk):K.postBody=(0,g.Th)([120,0])}v.J&&(K.responseType="arraybuffer");var Y=++v.Ti,r=(0,g.yR)();v.Z=g.Oi(G,K,3,100).then(function(E){if(v.policy.ZY&&Y%100===1){var e=(0,g.yR)();v.player.uw("caprsp",{rn:Y,ms:e-r,kb:(E.xhr.responseText.length/1024).toFixed()})}a:{E=E.xhr;v.Sl();if(v.X){var P=!(v.J?E.response:
E.responseText)||E.status>=400;if(e=g.UGm(E)){E=g.Af(v.X,v.policy,{});v.X.Vt(E,e);VAF(v,v.X);break a}P?v.player.uw("capfail",{status:E.status}):(v.player.Gl().D0("fcb_r"),e=v.X.Vb[0].yb,v.U!=null&&v.j!==e&&(P=v.X.Vb[0],v.J?v.U(E.response,(P.startTime+v.player.B$())*1E3):v.U(E.responseText,(P.startTime+v.player.B$())*1E3),v.j=e))}v.X=null;v.Z=null}}).pj(function(E){v.X=null;
v.Z=null;var e;v.player.uw("capfail",{rn:Y,status:(e=E.xhr)==null?void 0:e.status})});
v.X=J;Gsm(v.L,v.X.Vb[0].yb)},VS=function(v,J){g.q6.call(this,J);
this.T=v;this.S=J;this.Z=null;this.j=!1;this.logger=new g.rZ("caps");this.K=g.pX(this.S.B())&&!this.T.isManifestless},rxX=function(v,J){var G=[],K;
for(K in v.T.T)if(v.T.T.hasOwnProperty(K)){var V=v.T.T[K];if(g.e6(V,J||null)){var Y=V.info.id,r=Y,E="."+Y,e="",P="";if(V=V.info.captionTrack)Y=V.languageCode,r=V.displayName,E=V.vssId,e=V.kind,P=V.id;else{V=Y;var D=g.McL.get(V);D==null&&(D=YoL[V]||YoL[V.replace(/-/g,"_")],g.McL.set(V,D));V=D;r=V||r}G.push(new g.tW({id:K,languageCode:Y,languageName:r,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:e,captionId:P}))}}return G},qoX=function(v,J){return J!=null&&J in v.T.T?v.T.T[J]:null},
EtY=function(v,J,G){var K=[],V;
for(V in v.T.T)if(v.T.T.hasOwnProperty(V)){var Y=v.T.T[V];if(g.e6(Y,G||null)){var r=Y.info.captionTrack;r&&r.languageCode===J&&K.push(Y)}}return K.length?K[0]:null},Y7=function(v,J,G,K,V,Y,r,E,e,P){var D=P.isInline()&&!0,t={};
Object.assign(t,J);Object.assign(t,v.params);Object.assign(t,G);var B={};Object.assign(B,J.dJ);v.params.dJ&&Object.assign(B,v.params.dJ);Object.assign(B,G.dJ);D&&(t.windowOpacity=.6,B.backgroundOpacity=0);t.dJ=B;var I=t.Ah===1,h=[{Y:"span",D:"captions-text",V:{style:"word-wrap: normal; display: block;"}}],R,T,L;(E=E.OB("caption_edit_on_hover")&&((R=P.getVideoData().getPlayerResponse())==null?void 0:(T=R.captions)==null?void 0:(L=T.playerCaptionsTracklistRenderer)==null?void 0:L.openTranscriptCommand))&&
h.unshift({Y:"button",D:"caption-edit",V:{tabindex:"0","aria-label":vtL()},W:[{Y:"svg",V:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},W:[{Y:"path",V:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.F.call(this,{Y:"div",D:"caption-window",V:{id:"caption-window-"+v.id,dir:I?"rtl":"ltr",tabindex:"0",lang:t.lang},W:h});var O=
this;this.K=[];this.Mr=!1;this.X=v;this.YB=this.qr=null;this.playerWidth=Y;this.playerHeight=r;this.U=null;this.maxWidth=Y*.96;this.maxHeight=r*.96;this.T=t;this.Vn=G;this.Ti=J;this.L=this.p7("captions-text");this.R$=this.L.style.getPropertyValue("box-decoration-break")!==""||this.L.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Gi=eMT(K,V,Y,r);this.a$=e;E&&(this.j=this.p7("caption-edit"),this.G(this.j,"click",function(){O.a$()}));
this.type=0;this.BH=this.Gi*PZ8(B);this.g_=D;v=new g.Si(this.element,!0);g.k(this,v);v.subscribe("dragstart",this.VZ,this);v.subscribe("dragmove",this.ac,this);v.subscribe("dragend",this.lL,this);this.Nr=this.WH=this.o$=this.wh=0;v="";this.T.windowOpacity&&(v=$h8(this.T.windowColor),v="rgba("+v[0]+","+v[1]+","+v[2]+","+this.T.windowOpacity+")");J={"background-color":v,display:this.T.isVisible===!1?"none":"","text-align":DhU[this.T.textAlign]};this.R$&&(J["border-radius"]=v?this.BH/8+"px":"");(this.Z=
this.X.params.Ah===2||this.X.params.Ah===3)&&tAL(this,this.element);g.ep(this.element,J);if(D){var x;(x=this.element.parentElement)==null||x.style.setProperty("--caption-window-color",v)}switch(this.T.xN){case 0:case 1:case 2:g.Vj(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Vj(this.element,"ytp-caption-window-bottom")}},tAL=function(v,J){var G="vertical-rl";
v.T.PK===1&&(G="vertical-lr");g.tz&&(G=G==="vertical-lr"?"tb-lr":"tb-rl");g.ep(J,"-o-writing-mode",G);g.ep(J,"-webkit-writing-mode",G);g.ep(J,"writing-mode",G);g.ep(J,"text-orientation","upright");g.Vj(J,"ytp-vertical-caption");v.X.params.Ah===3&&(g.ep(J,"text-orientation",""),g.ep(J,"transform","rotate(180deg)"))},PZ8=function(v){var J=1+.25*(v.fontSizeIncrement||0);
if(v.offset===0||v.offset===2)J*=.8;return J},BAm=function(v,J){var G={},K=J.background?J.background:v.T.dJ.background;
if(J.backgroundOpacity!=null||J.background){var V=J.backgroundOpacity!=null?J.backgroundOpacity:v.T.dJ.backgroundOpacity;K=$h8(K);G.background="rgba("+K[0]+","+K[1]+","+K[2]+","+V+")";v.R$&&(G["box-decoration-break"]="clone",G["border-radius"]=v.BH/8+"px")}if(J.fontSizeIncrement!=null||J.offset!=null)G["font-size"]=v.Gi*PZ8(J)+"px";K=1;V=J.color||v.T.dJ.color;if(J.color||J.textOpacity!=null)V=$h8(V),K=J.textOpacity==null?v.T.dJ.textOpacity:J.textOpacity,V="rgba("+V[0]+","+V[1]+","+V[2]+","+K+")",
G.color=V,G.fill=V;var Y=J.charEdgeStyle;Y===0&&(Y=void 0);if(Y){V="rgba(34, 34, 34, "+K+")";var r="rgba(204, 204, 204, "+K+")";J.Ry&&(r=V=J.Ry);var E=v.Gi/16/2,e=Math.max(E,1),P=Math.max(2*E,1),D=Math.max(3*E,1),t=Math.max(5*E,1);K=[];switch(Y){case 4:for(;D<=t;D+=E)K.push(P+"px "+P+"px "+D+"px "+V);break;case 1:P=window.devicePixelRatio>=2?.5:1;for(Y=e;Y<=D;Y+=P)K.push(Y+"px "+Y+"px "+V);break;case 2:K.push(e+"px "+e+"px "+r);K.push("-"+e+"px -"+e+"px "+V);break;case 3:for(D=0;D<5;D++)K.push("0 0 "+
P+"px "+V)}G["text-shadow"]=K.join(", ")}V="";switch(J.fontFamily){case 1:V='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:V='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:V='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:V='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:V='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:V=g.FX()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:V='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}V&&(G["font-family"]=V);V=J.offset;V==null&&(V=v.T.dJ.offset);switch(V){case 0:G["vertical-align"]="sub";break;case 2:G["vertical-align"]="super"}J.fontFamily===7&&(G["font-variant"]="small-caps");J.bold&&(G["font-weight"]="bold");J.italic&&(G["font-style"]="italic");J.underline&&(G["text-decoration"]=
"underline");J.IeB&&(G.visibility="hidden");J.DF===1&&v.Z&&(G["text-combine-upright"]="all",G["text-orientation"]="mixed",V=g.$g||g.nP,v.X.params.Ah===3?G.transform=V?"rotate(90deg)":"rotate(180deg)":V&&(G.transform="rotate(-90deg)"));if(J.textEmphasis===1||J.textEmphasis===2||J.textEmphasis===3||J.textEmphasis===4||J.textEmphasis===5)if(g.$g)G["font-weight"]="bold";else switch(G["text-emphasis-style"]="filled circle",G["text-emphasis-color"]="currentcolor",G["webkit-text-emphasis"]="filled circle",
J.textEmphasis){case 4:case 3:G["text-emphasis-position"]="under left";G["webkit-text-emphasis-position"]="under left";break;case 5:case 2:G["text-emphasis-position"]="over right",G["webkit-text-emphasis-position"]="over right"}return G},r$=function(v){v=v.split("px");
return v.length>0?(v=Number(v[0]))?v:0:0},Iy8=function(v){v.U=g.qh("SPAN");
g.ep(v.U,{display:"block"});g.Vj(v.U,"caption-visual-line");v.L.appendChild(v.U)},hMS=function(v,J){var G=g.qh("SPAN");
g.ep(G,{display:"inline-block","white-space":"pre-wrap"});g.ep(G,BAm(v,J));G.classList.add("ytp-caption-segment");v.U.appendChild(G);G.previousElementSibling&&(g.ep(G.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ep(G,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return G},zMX=function(v,J,G){v.Mr=v.Mr||!!G;
var K={};Object.assign(K,v.T.dJ);Object.assign(K,G||J.T);Object.assign(K,v.Vn.dJ);(G=!v.U)&&Iy8(v);for(var V=v.qr&&v.YB&&g.cR(K,v.YB)?v.qr:hMS(v,K),Y=typeof J.text==="string",r=Y?J.text.split("\n"):[J.text],E=0;E<r.length;E++){var e=E>0||!J.append,P=r[E];e&&!G?(Iy8(v),V=hMS(v,K)):e&&G&&(G=!1);P&&(V.appendChild(Y?g.Eo(P):P),Y||P.tagName!=="RUBY"||P.childElementCount!==4||g.$g||!g.t4(P.children[2],"text-emphasis")||(e=v.Z?"padding-right":"padding-top",g.t4(P.children[2],"text-emphasis-position")&&(e=
v.Z?"padding-left":"padding-bottom"),g.KI?g.ep(V,e,"1em"):g.ep(V,e,"0.5em")))}v.YB=K;v.qr=V;v.K.push(J)},eMT=function(v,J,G,K){var V=J/360*16;
J>=v&&(v=640,K>G*1.3&&(v=480),V=G/v*16);return V},dhN=function(){this.Z=this.time=this.mode=this.X=0;
this.L=new ntX(this);this.J=new ntX(this);this.T=[];this.clear()},RMA=function(v,J,G){if(v===255&&J===255||!v&&!J)return{Fx:v,
G2:J,result:0};v=snL[v];J=snL[J];if(v&128){var K;if(K=!(J&128))K=J,K=G.B1()&&G.G2===K;if(K)return{Fx:v,G2:J,result:1}}else if(J&128&&1<=v&&v<=31)return{Fx:v,G2:J,result:2};return{Fx:v,G2:J,result:3}},TA_=function(v,J,G,K){J===255&&G===255||!J&&!G?(++v.Z===45&&v.reset(),v.L.X.clear(),v.J.X.clear()):(v.Z=0,lyX(v.L,J,G,K))},pMU=function(v,J){v.T.sort(function(V,Y){var r=V.time-Y.time;
return r===0?V.order-Y.order:r});
for(var G=g.n(v.T),K=G.next();!K.done;K=G.next())K=K.value,v.time=K.time,K.type===0?TA_(v,K.vc,K.sC,J):K.type===1&&v.X&496&&lyX(v.J,K.vc,K.sC,J);v.T.length=0},qP=function(){this.type=0},EJ=function(){this.state=this.G2=this.Fx=0},L26=function(){this.timestamp=this.T=0},eL=function(v){this.J=v;
this.Z=[];this.T=this.X=this.row=0;this.style=new qP;for(v=this.L=0;v<=15;v++){this.Z[v]=[];for(var J=0;J<=32;J++)this.Z[v][J]=new L26}},PP=function(v,J){if(v.style.type===3){for(var G=0,K=0,V=v.J.time+0,Y="",r="",E=V,e=1;e<=15;++e){for(var P=!1,D=K?K:1;D<=32;++D){var t=v.Z[e][D];
if(t.T!==0){G===0&&(G=e,K=D);P=String.fromCharCode(t.T);var B=t.timestamp;B<V&&(V=B);t.timestamp=E;r&&(Y+=r,r="");Y+=P;P=!0}if((t.T===0||D===32)&&P){r="\n";break}else if(K&&!P)break}if(G&&!P)break}Y&&J.L(G,K,V,E,Y)}else for(K=G=0,Y=V=v.J.time+0,r=1;r<=15;++r)for(E="",e=1;e<=32;++e)if(D=v.Z[r][e],t=D.T,t!==0&&(G===0&&(G=r,K=e),P=String.fromCharCode(t),B=D.timestamp,B<=V&&(V=B),E+=P,D.reset()),e===32||t===0)E&&J.L(G,K,V,Y,E),V=Y,E="",K=G=0},xhA=function(v,J){switch(v){case 0:return yx8[(J&127)-32];
case 1:return wMF[J&15];case 2:return OIY[J&31];case 3:return UhY[J&31]}return 0},Dn=function(v){return v.Z[v.row][v.X]},tT=function(v,J,G){J>=2&&v.X>1&&(--v.X,Dn(v).T=0);
var K=Dn(v);K.timestamp=v.J.time+0;K.T=xhA(J,G);v.X<32&&v.X++},mh8=function(v,J,G,K){for(var V=0;V<K;V++)for(var Y=0;Y<=32;Y++){var r=v.Z[J+V][Y],E=v.Z[G+V][Y];
r.T=E.T;r.timestamp=E.timestamp}},BP=function(v,J,G){for(var K=0;K<G;K++)for(var V=0;V<=32;V++)v.Z[J+K][V].reset()},SoF=function(v){v.row=v.T>0?v.T:1;
v.X=1;BP(v,0,15)},fym=function(v){this.Z=v;
this.J=0;this.style=new qP;this.j=new eL(this.Z);this.K=new eL(this.Z);this.text=new eL(this.Z);this.X=this.j;this.L=this.K;this.T=this.X},ZIN=function(v,J,G){var K=v.X,V=!1;
switch(v.style.get()){case 4:case 1:case 2:v.style.get()===4&&K.T>0||(PP(K,G),SoF(v.X),SoF(v.L),K.row=15,K.T=J,V=!0)}v.style.set(3);v.T=K;v.T.style=v.style;v.Z.mode=1<<K.L;V?K.X=1:K.T!==J&&(K.T>J?(PP(K,G),BP(K,K.row-K.T,J)):K.row<J&&(J=K.T),K.T=J)},uMN=function(v){v.style.set(1);
v.T=v.L;v.T.T=0;v.T.style=v.style;v.Z.mode=1<<v.T.L},gtY=function(v){v.style.set(4);
v.T=v.text;v.T.style=v.style;v.Z.mode=1<<v.T.L},ntX=function(v){this.T=v;
this.J=0;this.Z=new fym(this.T);this.j=new fym(this.T);this.X=new EJ;this.L=this.Z},lyX=function(v,J,G,K){v.X.update();
J=RMA(J,G,v.X);switch(J.result){case 0:return;case 1:case 2:return}var V=J.Fx;G=J.G2;if(32<=V||!V)v.T.mode&v.T.X&&(J=V,J&128&&(J=127),G&128&&(G=127),v=v.L.T,J&96&&tT(v,0,J),G&96&&tT(v,0,G),J!==0&&G!==0&&v.style.type===3&&PP(v,K));else if(V&16)a:if(!v.X.matches(V,G)&&(J=v.X,J.Fx=V,J.G2=G,J.state=2,J=V&8?v.j:v.Z,v.L=J,v.T.mode=1<<(v.J<<2)+(J.J<<1)+(J.style.type===4?1:0),(v.T.mode|1<<(v.J<<2)+(J.J<<1)+(J.style.type!==4?1:0))&v.T.X))if(G&64){K=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(V&7)<<1|G>>5&1];
v=G&16?((G&14)>>1)*4:0;G=J.T;switch(J.style.get()){case 4:K=G.row;break;case 3:if(K!==G.row){if(K<G.T&&(K=G.T,K===G.row))break;var Y=1+G.row-G.T,r=1+K-G.T;mh8(G,r,Y,G.T);J=Y;V=G.T;r<Y?(Y=r+V-Y,Y>0&&(J+=Y,V-=Y)):(Y=Y+V-r,Y>0&&(V-=Y));BP(G,J,V)}}G.row=K;G.X=v+1}else switch(V&7){case 1:switch(G&112){case 32:tT(J.T,0,32);break a;case 48:G===57?(K=J.T,Dn(K).T=0,K.X<32&&K.X++):tT(J.T,1,G&15)}break;case 2:G&32&&tT(J.T,2,G&31);break;case 3:G&32&&tT(J.T,3,G&31);break;case 4:case 5:if(32<=G&&G<=47)switch(G){case 32:uMN(J);
break;case 33:K=J.T;K.X>1&&(--K.X,Dn(K).T=0);break;case 36:K=J.T;J=Dn(K);for(v=0;v<=15;v++)for(G=0;G<=32;G++)if(K.Z[v][G]===J){for(;G<=32;G++)K.Z[v][G].reset();break}break;case 37:ZIN(J,2,K);break;case 38:ZIN(J,3,K);break;case 39:ZIN(J,4,K);break;case 40:tT(J.T,0,32);break;case 41:J.style.set(2);J.T=J.X;J.T.T=0;J.T.style=J.style;J.Z.mode=1<<J.T.L;break;case 42:K=J.text;K.T=15;K.style.set(4);SoF(K);gtY(J);break;case 43:gtY(J);break;case 44:v=J.X;switch(J.style.get()){case 1:case 2:case 3:PP(v,K)}BP(v,
0,15);break;case 45:b:{v=J.T;switch(J.style.get()){default:case 2:case 1:break b;case 4:if(v.row<15){++v.row;v.X=1;break b}break;case 3:}v.T<2&&(v.T=2,v.row<v.T&&(v.row=v.T));J=v.row-v.T+1;PP(v,K);mh8(v,J,J+1,v.T-1);BP(v,v.row,1)}break;case 46:BP(J.L,0,15);break;case 47:PP(J.X,K),J.L.updateTime(J.Z.time+0),K=J.L,J.L=J.X,J.X=K,uMN(J)}break;case 7:switch(G){case 33:case 34:case 35:K=J.T,(K.X+=G&3)>32&&(K.X=32)}}},XMo=function(){},Ia=function(v,J,G,K,V,Y,r){Y=Y===void 0?!1:Y;
r=r===void 0?null:r;g.o8.call(this,v,v+J,{priority:G,namespace:"captions"});this.windowId=K;this.text=V;this.append=Y;this.T=r},cx6=function(v,J,G,K,V,Y,r){var E=Y[0],e=r[E.getAttribute("p")];
if(e.Kq===1){var P=Y[1],D=Y[2];Y=Y[3];E.getAttribute("t");P.getAttribute("t");D.getAttribute("t");Y.getAttribute("t");E.getAttribute("p");P.getAttribute("p");Y.getAttribute("p");r=r[D.getAttribute("p")];E=ksS(E.textContent,P.textContent,D.textContent,Y.textContent,r);return new Ia(v,J,V,G,E,K,e)}switch(e.Kq){case 9:case 10:e.textEmphasis=1;break;case 11:e.textEmphasis=2;break;case 12:e.textEmphasis=3;break;case 13:e.textEmphasis=4;break;case 14:e.textEmphasis=5}return new Ia(v,J,V,G,E.textContent||
"",K,e)},ksS=function(v,J,G,K,V){var Y=g.FX(),r=Y?g.qh("DIV"):g.qh("RUBY"),E=g.qh("SPAN");
E.textContent=v;r.appendChild(E);v=Y?g.qh("DIV"):g.qh("RP");v.textContent=J;r.appendChild(v);J=Y?g.qh("DIV"):g.qh("RT");J.textContent=G;r.appendChild(J);G=V.Kq;if(G===10||G===11||G===12||G===13||G===14)if(g.ep(J,"text-emphasis-style","filled circle"),g.ep(J,"text-emphasis-color","currentcolor"),g.ep(J,"webkit-text-emphasis","filled circle"),V.Kq===11||V.Kq===13)g.ep(J,"webkit-text-emphasis-position","under left"),g.ep(J,"text-emphasis-position","under left");G=!0;if(V.Kq===4||V.Kq===7||V.Kq===12||
V.Kq===14)g.ep(r,"ruby-position","over"),g.ep(r,"-webkit-ruby-position","before");else if(V.Kq===5||V.Kq===6||V.Kq===11||V.Kq===13)g.ep(r,"ruby-position","under"),g.ep(r,"-webkit-ruby-position","after"),G=!1;V=Y?g.qh("DIV"):g.qh("RP");V.textContent=K;r.appendChild(V);Y&&(K=G,g.ep(r,{display:"inline-block",position:"relative"}),Y=r.firstElementChild.nextElementSibling,g.ep(Y,"display","none"),Y=Y.nextElementSibling,g.ep(Y,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ep(r.lastElementChild,"display","none"),K?(g.ep(r,"padding-top","0.6em"),g.ep(Y,"top","0")):(g.ep(r,"padding-bottom","0.6em"),g.ep(Y,"bottom","0")));return r},hT=function(){g.X.apply(this,arguments)},zg=function(v,J,G,K,V){g.o8.call(this,v,v+J,{priority:G,
namespace:"captions"});this.id=K;this.params=V;this.T=[]},NAX=function(v){var J="_"+nK++;
return new zg(0,0x8000000000000,0,J,v)},d$=function(v){hT.call(this);
this.Z=v;this.pens={};this.K={};this.U={};this.L="_"+nK++;this.j={};this.X=this.T=null;this.J=!0},sJ=function(v,J){v=v.getAttribute(J);
if(v!=null)return Number(v)},Ra=function(v,J){v=v.getAttribute(J);
if(v!=null)return v==="1"},lJ=function(v,J){v=sJ(v,J);
return v!==void 0?v:null},pK=function(v,J){v=v.getAttribute(J);
if(v!=null)return Tg.test(v),v},ayN=function(v,J){var G={},K=J.getAttribute("ws");
Object.assign(G,K?v.U[K]:v.Z);v=lJ(J,"mh");v!=null&&(G.D4=v);v=lJ(J,"ju");v!=null&&(G.textAlign=v);v=lJ(J,"pd");v!=null&&(G.Ah=v);v=lJ(J,"sd");v!=null&&(G.PK=v);v=pK(J,"wfc");v!=null&&(G.windowColor=v);J=sJ(J,"wfo");J!==void 0&&(G.windowOpacity=J/255);return G},Axm=function(v,J){var G={},K=J.getAttribute("wp");
K&&Object.assign(G,v.K[K]);v=lJ(J,"ap");v!=null&&(G.xN=v);v=sJ(J,"cc");v!=null&&(G.z2=v);v=sJ(J,"ah");v!=null&&(G.Tk=v);v=sJ(J,"rc");v!=null&&(G.oO=v);J=sJ(J,"av");J!=null&&(G.lr=J);return G},F2N=function(v,J,G,K){var V={};
Object.assign(V,Axm(v,J));Object.assign(V,ayN(v,J));K?g.cR(V,v.Z)?(K=v.L,V=v.Z):K="_"+nK++:K=J.getAttribute("id")||"_"+nK++;v=sJ(J,"t")+G;J=sJ(J,"d")||0x8000000000000;if(V.Ah===2||V.Ah===3)G=V.oO,V.oO=V.z2,V.z2=G;return new zg(v,J,0,K,V)},LK=function(v){hT.call(this);
this.J=v;this.T=new Map;this.Z=new Map;this.L=new Map;this.X=new Map},yS=function(v){v=g.nk(Math.round(v),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-v.length)+v},HIF=function(v,J,G,K,V){K===0&&(K=0x8000000000000);
var Y={};J.wpWinPosId&&Object.assign(Y,v.Z.get(J.wpWinPosId));J.wsWinStyleId&&Object.assign(Y,v.L.get(J.wsWinStyleId));v=J.rcRowCount;v!==void 0&&(Y.oO=v);J=J.ccColCount;J!==void 0&&(Y.z2=J);if(Y.Ah===2||Y.Ah===3)J=Y.oO,Y.oO=Y.z2,Y.z2=J;return new zg(G,K,0,V,Y)},w$=function(v,J,G){g.q6.call(this,v);
this.videoData=J;this.audioTrack=G;this.J=J.AB},OJ=function(v,J,G,K,V,Y,r,E,e,P){Y7.call(this,v,J,G,K,V,Y,r,E,e,P);
this.type=1},UJ=function(v,J,G){this.trackData=v;
this.j=G;this.version=this.J=this.Z=this.byteOffset=0;this.X=[];this.T=new DataView(this.trackData)},x7=function(v){var J=v.byteOffset;
v.byteOffset+=1;return v.T.getUint8(J)},mA=function(v){var J=v.byteOffset;
v.byteOffset+=4;return v.T.getUint32(J)},SL=function(v,J){hT.call(this);
this.X=v;this.Z=J;this.track=this.Z.languageName==="CC3"?4:0;this.T=new dhN;this.T.X=1<<this.track},Qn8=function(v){if(typeof v==="string")return!1;
v=new UJ(v,8,0);return MA6(v)},MA6=function(v){if(!(v.byteOffset<v.T.byteLength)||mA(v)!==1380139777)return!1;
v.version=x7(v);if(v.version>1)return!1;x7(v);x7(v);x7(v);return!0},fK=function(v,J,G,K,V,Y,r,E,e,P){Y7.call(this,v,J,G,K,V,Y,r,E,e,P);
var D=this;this.type=2;this.dh=[];this.oY=this.N=this.jl=0;this.Ze=NaN;this.UR=0;this.OR=null;this.xB=new g.Qq(this.Oc,433,this);this.RY=!1;this.j&&(P.createClientVe(this.j,this,167342),this.G(this.j,"click",function(){P.logClick(D.j)}),v=new g.Si(this.element,!0),g.k(this,v),v.subscribe("hoverstart",function(){P.logVisibility(D.j,!0)},this));
g.Vj(this.element,"ytp-caption-window-rollup");g.k(this,this.xB);this.RY=E.OB("html5_rollup_caption_window_enable_transition_end_listener");g.ep(this.element,"overflow","hidden")},W28=function(v,J){if(!J)return"";
v.Z&&v.X.params.PK!==1&&(J*=-1);return"translate"+(v.Z?"X":"Y")+"("+J+"px)"},CZ8=function(v){v.dh=Array.from(v.element.getElementsByClassName("caption-visual-line"));
for(var J=v.X.params.oO,G=0,K=0,V=v.dh.length-1;G<J&&V>-1;){var Y=v.dh[V];K+=v.Z?Y.offsetWidth:Y.offsetHeight;G++;V--}v.N=K;J=Math;G=J.max;isNaN(v.Ze)&&((K=v.T.z2)?(V=g.qh("SPAN"),g.In(V,"\u2013".repeat(K)),g.ep(V,BAm(v,v.T.dJ)),v.L.appendChild(V),v.Ze=V.offsetWidth,v.L.removeChild(V)):v.Ze=0);K=v.L;v.oY=G.call(J,v.Ze,v.UR,(v.Z?K.offsetHeight:K.offsetWidth)+1)},bIm=function(v,J){CZ8(v);
var G=v.dh.reduce(function(Y,r){return(v.Z?r.offsetWidth:r.offsetHeight)+Y},0);
G=v.N-G;if(G!==v.jl){var K=G>0&&v.jl===0,V=G<v.jl;J||isNaN(G)||K||!V||(g.Vj(v.element,"ytp-rollup-mode"),v.RY?v.G(v.element,"transitionend",v.Oc):g.Wq(v.xB));g.ep(v.L,"transform",W28(v,G));v.jl=G}CZ8(v)},jpo=function(v,J,G,K){var V=this;
this.S=v;this.Z=J;this.logger=G;this.yn=K;this.f0=[];this.Z8=[];this.T=null;this.cO={FBl:function(){return V.T},
dK:function(){return V.f0}};
v=g.DI(this.S.B().experiments,"html5_override_micro_discontinuities_threshold_ms");this.X=v>0?v:10},vbo=function(v,J){v.T=function(G,K){if(G.info.J){var V=G;
if(v.Z8.length>0){for(V=v.Z8.shift();v.Z8.length>0;)V=g.vZ(V,v.Z8.shift());V=g.vZ(V,G)}if(V){G=V;try{var Y=g.J1(G)*1E3}catch(P){Y=G.info.startTime*1E3}try{var r=g.dGf(G)*1E3}catch(P){r=G.info.duration*1E3}if(Y<0||r<0)Y<0&&(Y=G.info.startTime*1E3),r<0&&(r=G.info.duration*1E3);G.info.startTime=Y/1E3;G.info.L=Y/1E3;G.info.duration=r/1E3;G.info.U=r/1E3;Y=v.xb(V);r=Y.yb;Y={formatId:Y.formatId,startTimeMs:Y.startTimeMs,durationMs:Y.durationMs,S4:r,XF:r};r=iQX(v.f0,Y.startTimeMs);var E=(G=r>=0?v.f0[r]:null)?
G.startTimeMs+G.durationMs:0,e=Y.startTimeMs+Y.durationMs;!G||Y.startTimeMs-E>v.X?v.f0.splice(r+1,0,Y):(G.durationMs=Math.max(E,e)-G.startTimeMs,G.XF=Math.max(G.XF,Y.XF));K(v.f0);K=V.s1();$Co(v.Z,K.buffer.slice(K.byteOffset,K.byteLength+K.byteOffset),J,V.info.L)}else v.logger.T(350058965,"Empty slice")}else v.Z8.push(G)};
v.S.addEventListener("sabrCaptionsDataLoaded",v.T)},iQX=function(v,J){v=g.YY(v,{startTimeMs:J},function(G,K){return G.startTimeMs-K.startTimeMs});
return v>=0?v:-v-2},JGU=function(v,J){g.q6.call(this,J);
this.T=v;this.S=J;this.logger=new g.rZ("caps");this.Z=this.j=null;this.K=new jpo(this.S,this,this.logger,this.T.yn)},$Co=function(v,J,G,K){v.logger.debug(function(){return"SABR captions data received for "+K});
v.j?v.Z==null?v.logger.T(350058965,"Null loaded track meta data at captions data received"):G.HL(J,v.Z,K*1E3):v.logger.T(350058965,"Null Representation at captions data received")},GDA=function(v,J){var G=[],K;
for(K in v.T.T)if(v.T.T.hasOwnProperty(K)){var V=v.T.T[K];if(g.e6(V,J||null)){var Y=V.info.id,r=Y,E="."+Y,e="",P="";if(V=V.info.captionTrack)Y=V.languageCode,r=V.displayName,E=V.vssId,e=V.kind,P=V.id;G.push(new g.tW({id:K,languageCode:Y,languageName:r,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:e,captionId:P}))}}return G},obU=function(v,J,G){var K=[],V;
for(V in v.T.T)if(v.T.T.hasOwnProperty(V)){var Y=v.T.T[V];if(g.e6(Y,G||null)){var r=Y.info.captionTrack;r&&r.languageCode===J&&K.push(Y)}}return K.length?K[0]:null},KKG=function(v,J){if(!g.qrm(v)||v.T!=null&&g.pX(J.B())&&!v.T.isManifestless&&v.T.T.rawcc!=null)return!1;
J=!!v.T&&v.T.isManifestless&&Object.values(v.T.T).some(function(G){return g.e6(G,"386")});
v=!!v.T&&!v.T.isManifestless&&g.fow(v.T);return J||v},Zn=function(){hT.call(this)},VCX=function(v,J,G,K,V,Y,r,E,e){switch(r.tagName){case "b":E.bold=!0;
break;case "i":E.italic=!0;break;case "u":E.underline=!0}for(var P=0;P<r.childNodes.length;P++){var D=r.childNodes[P];if(D.nodeType===3)D=new Ia(J,G,K,V.id,D.nodeValue,Y||P>0,g.Xb(E)?void 0:E),e.push(D),V.T.push(D);else{var t={};Object.assign(t,E);VCX(v,J,G,K,V,!0,D,t,e)}}},YFm=function(v){var J=v.split(":");
v=0;J=g.n(J);for(var G=J.next();!G.done;G=J.next())v=v*60+Number(G.value);return v*1E3},rGX=function(v,J,G,K){K=Object.assign({D4:0},K);
return new zg(v,J,G,"_"+nK++,K)},uJ=function(v,J){g.X.call(this);
this.S=v;this.EB=J;this.T=null;this.X=this.S.gH();this.logger=new g.rZ("caps")},EbX=function(v,J,G){if(typeof J==="string"||Qn8(J))return[{trackData:J,
RZ:G}];var K=new DataView(J);if(K.byteLength<=8||K.getUint32(4)!==1718909296)return[];var V=g.wEt(K);if(v.X&&V){var Y=g.d9f(V),r=g.s$s(V);V=V.iz;Y&&V&&v.X.Rx(V,Y,r)}v=g.Jf(K,1835295092);if(!v||!v.length||!v[0].size)return[];Y=[];for(r=0;r<v.length;r++)V=v[r],V=new Uint8Array(J,V.dataOffset,V.size-(V.dataOffset-V.offset)),V=g.yA(V),Y.push({trackData:V,RZ:G+r*1E3});qFS(K,Y,G);return Y=Y.filter(function(E){return!!E.trackData})},qFS=function(v,J,G){var K=g.MB(v,0,1836476516),V=9E4;
K&&(V=g.Qa(K)||9E4);K=0;for(var Y=g.Jf(v,1836019558),r=0;r<Y.length;r++){var E=Y[r];r<J.length&&(E=g.MB(v,E.dataOffset,1953653094))&&(E=g.MB(v,E.dataOffset,1952867444))&&(E=g.$x(E)/V*1E3,r===0&&(K=E),J[r].RZ=E-K+G||G*r*1E3)}},ebT=function(v){var J={};
if(v=g.hW(v))J.lang=v,g.i8m.test(v)&&(J.Ah=1);return J},g$=function(v){g.YQ.call(this,v);
var J=this;this.S=v;this.qr=[];this.dh={};this.RY={};this.U=!1;this.L="NONE";this.T=this.N=this.oY=this.Gi=this.Nr=null;this.g_={Tb:function(){J.Tb()},
HL:function(Y,r,E,e){J.HL(Y,r,E,e)}};
this.X=null;this.EB=this.S.B();this.videoData=this.S.getVideoData();this.wh=this.S.f7();var G;this.WH=(G=this.S.getVideoData(1))==null?void 0:g.WG(G);this.Z={dJ:{}};this.j={dJ:{}};g.im(this.videoData)?this.L="OFFLINE":KKG(this.videoData,this.S)?this.L="SABR_LIVE":g.icw(this.videoData,this.S)?this.L="LIVE":this.videoData.captionTracks.length?this.L="INNERTUBE":this.videoData.Bv&&(this.L="TTS");this.xB=this.EB.controlsType==="3";this.BH=new uJ(this.S,this.EB);this.Ze=new g.Zs(this);this.K=new g.F({Y:"div",
D:"ytp-caption-window-container",V:{id:"ytp-caption-window-container"}});this.Ti={top:0,right:0,bottom:0,left:0,width:1,height:1};G=null;var K=g.u6("yt-html5-player-modules::subtitlesModuleData");K&&(G=new g.yj(K));this.storage=G;var V;this.o$=!((V=v.LY())==null||!V.jW());this.J=Pi_(this);this.Mr=!this.J&&this.xB&&this.o$&&(this.L==="LIVE"||this.L==="SABR_LIVE");g.k(this,this.BH);this.J?this.jl=this.YB=null:(this.YB=new g.M3(this.uE,void 0,this),g.k(this,this.YB),this.jl=new g.Qq(this.I0l,2E3,this),
g.k(this,this.jl));g.k(this,this.Ze);g.gr(this.player,this.K.element,4);g.k(this,this.K);this.J||this.Ze.G(v,"resize",this.Qx);(this.d_=g.fY(this.EB)&&!g.hD()&&!this.S.isFullscreen()&&!this.J&&!this.Mr)&&this.Ze.G(v,"resize",this.lvB);this.Ze.G(v,"onPlaybackAudioChange",this.APB);this.Ze.G(v,g.VG("captions"),function(Y){J.onCueRangeEnter(Y)});
this.Ze.G(v,g.YM("captions"),function(Y){J.onCueRangeExit(Y)});
this.WH&&this.Ze.G(v,"videodatachange",function(Y,r){J.onVideoDataChange(Y,r)});
DC8(this,JxA()||{});this.player.Tr("onCaptionsModuleAvailable")},IJm=function(v){if(v.EB.o$===1||v.videoData.y8===1||g.Rv(v.videoData,"yt:cc")==="alwayson")return!0;
if(v.videoData.captionTracks.length)var J=v.getAudioTrack().X;if(v.EB.o$===2){if(g.bh(v.EB))var G=tC8(v);else if(v.storage)try{G=v.storage.get("module-enabled")}catch(V){v.storage.remove("module-enabled")}else G=null;if(G!=null)return!!G}G=MKY(v.player.getAudioTrack(),g.bh(v.EB));var K=g.Rv(v.videoData,"yt:cc");if(BQ8(v)===void 0){if(G==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return K?K==="on":!0;if(G==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return K==="on"}else return K==="on";return J==="ON"||
g.Rv(v.videoData,"yt:cc")==="on"},Xh=function(v,J){if(v.X&&(J===void 0||!J)||!v.videoData.captionTracks.length)return!1;
v=v.getAudioTrack();return!!v.T||v.X==="FORCED_ON"},BQ8=function(v){var J=void 0,G=g.Nk(g.c8(),65);
if(g.bh(v.EB)&&G!=null){if(tC8(v)!=null)return!1;J=!G}return J},cP=function(v,J){if(!v.T)return null;
if(v.N&&v.N.L)return v.N.L;J=hbY(v,J);J=g.WT(v.T.X,J);var G=null;if(Q7X(v.EB)){var K=v.S.isInline()?void 0:g.fq("yt-player-caption-sticky-language");for(var V=[K,v.videoData.captionsLanguagePreference,v.EB.captionsLanguagePreference,g.Rv(v.videoData,"yt:cc_default_lang")],Y=!1,r=0;r<V.length;r++){var E=V[r];if(E){Y=!0;for(var e=0;e<J.length;e++)if(g.hW(J[e])===E)return J[e];for(e=0;e<J.length;e++)if(g.hW(J[e]).split("-")[0]===E.split("-")[0])return J[e]}}if(Y&&v.T&&(V=v.T.J,V.length))for(V=g.n(V),
Y=V.next();!Y.done;Y=V.next())if(Y=Y.value,Y.languageCode===K){G=Y;break}}else for(K=[v.videoData.captionsLanguagePreference,v.EB.captionsLanguagePreference,g.Rv(v.videoData,"yt:cc_default_lang")],V=0;V<K.length;V++)for(Y=0;Y<J.length;Y++)if(g.hW(J[Y])===K[V])return J[Y];K=null;v.N&&v.N.Z&&(K=v.N.Z);K||(K=J.find(function(P){return P.isDefault})||null);
K||(K=J[0]||k7(v));K&&G&&g.hW(K).split("-")[0]!==G.languageCode.split("-")[0]&&(K=Wx8(K,G));return K},k7=function(v){return v.N&&v.N.T},NP=function(v){var J=k7(v);
return!!J&&v.X===J},zbT=function(v,J){var G=v.S.LY().ZZ().textTracks;
v=v.X.toString();for(var K=0;K<G.length;K++){var V=G[K];V.id===v&&(J?V.mode!=="showing"&&(V.mode="showing"):V.mode==="showing"&&(V.mode="disabled"))}},Fh=function(v,J,G){v.loaded&&v.unload();
G!=null&&(v.U=G,v.U&&(g.bh(v.EB)?aa(v,!!J):AT(v,!!J)));nbU(v,v.X,J,v.U,!1);v.X=J;Xh(v)&&(J=k7(v),nbU(v,v.X,J,v.U,!0),v.X=J);var K;dCL(v,(K=v.X)!=null?K:void 0);v.load()},RbU=function(v,J){if(J instanceof zg){var G=v.dh[J.id];
G&&G.X!==J&&(G.dispose(),delete v.dh[J.id],G=null);G||(G=spm(v,J))&&(v.dh[J.id]=G)}else G=J.windowId,v.RY[G]||(v.RY[G]=[]),v.RY[G].push(J)},spm=function(v,J){var G=lJX(v);
if(!G)return null;var K=v.X?g.hW(v.X):null;K&&g.i8m.test(K)&&(J.params.Ah=1);var V=v.wh.getPlayerSize();K=V.height*v.Ti.height;V=V.width*v.Ti.width;v.EB.playerStyle!=="google-live"||v.Z.isDefault||Object.assign(J.params,v.Z);switch(J.params.D4!=null?J.params.D4:J.T.length>1?1:0){case 1:return new OJ(J,v.Z,v.j,G.width,G.height,V,K,v.EB.experiments,v.ZC.bind(v),v.S);case 2:return new fK(J,v.Z,v.j,G.width,G.height,V,K,v.EB.experiments,v.ZC.bind(v),v.S);default:return new Y7(J,v.Z,v.j,G.width,G.height,
V,K,v.EB.experiments,v.ZC.bind(v),v.S)}},DC8=function(v,J,G){G=G===void 0?!1:G;
var K=HP.dJ;v.Z={};Object.assign(v.Z,HP);v.Z.dJ={};Object.assign(v.Z.dJ,K);v.j={dJ:{}};var V=J.backgroundOverride?v.j:v.Z,Y=J.background||K.background;Tg.test(Y);V.dJ.background=Y;V=J.colorOverride?v.j:v.Z;Y=J.color||K.color;Tg.test(Y);V.dJ.color=Y;V=J.windowColorOverride?v.j:v.Z;Y=J.windowColor||HP.windowColor;Tg.test(Y);V.windowColor=Y;V=J.backgroundOpacityOverride?v.j:v.Z;Y=J.backgroundOpacity;Y==null&&(Y=K.backgroundOpacity);V.dJ.backgroundOpacity=Y;V=J.fontSizeIncrementOverride?v.j:v.Z;Y=J.fontSizeIncrement;
Y==null&&(Y=K.fontSizeIncrement);V.dJ.fontSizeIncrement=Y;Y=J.fontStyleOverride?v.j:v.Z;V=J.fontStyle;V==null&&(V=K.bold&&K.italic?3:K.bold?1:K.italic?2:0);Y=Y.dJ;switch(V){case 1:Y.bold=!0;delete Y.italic;break;case 2:delete Y.bold;Y.italic=!0;break;case 3:Y.bold=!0;Y.italic=!0;break;default:delete Y.bold,delete Y.italic}V=J.textOpacityOverride?v.j:v.Z;Y=J.textOpacity;Y==null&&(Y=K.textOpacity);V.dJ.textOpacity=Y;V=J.windowOpacityOverride?v.j:v.Z;Y=J.windowOpacity;Y==null&&(Y=HP.windowOpacity);V.windowOpacity=
Y;V=J.charEdgeStyleOverride?v.j:v.Z;Y=J.charEdgeStyle;Y==null&&(Y=K.charEdgeStyle);V.dJ.charEdgeStyle=Y;V=J.fontFamilyOverride?v.j:v.Z;Y=J.fontFamily;Y==null&&(Y=K.fontFamily);V.dJ.fontFamily=Y;v.loaded&&v.Qx();G&&g.SW("yt-player-caption-display-settings",J,2592E3)},TQ6=function(v,J){if(!v.T)return{};
if(J){g.Xb(J)||v.ZM(J.vss_id,"m");if(v.J||!g.ML(J))return;if(g.Xb(J)){Fh(v,null,!0);return}for(var G,K=g.WT(v.T.X,!0),V=0;V<K.length;V++){var Y=K[V];Y.languageCode!==J.languageCode||G&&(Y.languageName!==J.languageName||(Y.captionId||"")!==(J.captionId||"")||g.BG(Y)!==J.displayName)||(G=J.translationLanguage?Wx8(Y,J.translationLanguage):Y)}v.W3(J.position);!G||G===v.X&&v.loaded||(J=g.An(),K=g.hW(G),J.length&&K===J[J.length-1]||(J.push(K),g.SW("yt-player-caption-language-preferences",J)),Q7X(v.EB)&&
!v.S.isInline()&&g.SW("yt-player-caption-sticky-language",K,2592E3),Fh(v,G,!0))}else return v.loaded&&v.X&&!NP(v)?g.IG(v.X):{};return""},LKm=function(v,J,G){J&&!v.oY?(J=NAX({Ah:0,
lang:"en"}),v.oY=[J,new Ia(J.start,J.end-J.start,0,J.id,G!=null?G:"Captions look like this")],v.player.oR(v.oY)):!J&&v.oY&&(ppF(v,v.oY),v.oY=null)},ppF=function(v,J){v.player.yS(J);
J=g.n(J);for(var G=J.next();!G.done;G=J.next())g.j5(v.qr,G.value);oa(v.YB)},dCL=function(v,J){v.EB.C("html5_modify_caption_vss_logging")&&(v.videoData.YE=J)},lJX=function(v){var J=v.wh.getVideoContentRect(!0).height,G=v.wh.getVideoContentRect(!0).width;
if(!J||!G)return null;J*=v.Ti.height;G*=v.Ti.width;return{width:G,height:J}},AT=function(v,J){if(v.storage)try{v.storage.set("module-enabled",J)}catch(G){}},aa=function(v,J){v.S.isInline()||g.SW("yt-player-sticky-caption",J,2592E3)},tC8=function(v){if(!v.S.isInline())return g.fq("yt-player-sticky-caption")},Pi_=function(v){if(v.EB.C("safari_live_drm_captions_fix")&&v.videoData.cw()&&v.videoData.yn()&&g.nP)return!0;
var J,G=!((J=v.S.LY())==null||!J.Fg());return v.xB&&G&&v.L!=="LIVE"&&v.L!=="SABR_LIVE"},hbY=function(v,J){g.ug(v.videoData)&&(J=!0);
J||(J=v.L==="TTS"?!1:v.L==="INNERTUBE"?!1:!0);return J||v.EB.C("web_deprecate_always_includes_asr_setting")&&g.bh(v.EB)?!0:!!g.Nk(g.c8(),66)},nbU=function(v,J,G,K,V){V?v.ya(G,!0,"g"):K?J?v.ya(G,!!G,"m"):G&&v.ya(G,!0,"m"):!J&&G&&v.ya(G,!0,"s")};
g.q6.prototype.SV=g.rw(77,function(){return!1});
g.q6.prototype.Kz=g.rw(76,function(){});
g.ED.prototype.Kz=g.rw(75,function(v,J,G){var K=this;this.Sl();J=this.cD(v,J);var V=this.kB.B().C("html5_report_captions_ctmp_qoe"),Y=(0,g.yR)();this.V1();HkL(this,J,{format:"RAW",onSuccess:function(r){K.T=null;if(V){var E=(r.responseText.length/1024).toFixed(),e=(0,g.yR)();K.videoData.uw("capresp",{ms:e-Y,kb:E})}G.HL(r.responseText,v)},
onError:V?function(r){var E;r=(E=r==null?void 0:r.status)!=null?E:0;K.videoData.uw("capfail",{status:r})}:void 0,
withCredentials:!0})});
g.Pv.prototype.Kz=g.rw(74,function(v,J,G){var K=this;this.Sl();J=this.cD(v,J);this.V1();this.T=g.pE(J,{format:"RAW",onSuccess:function(V){K.T=null;G.HL(V.responseText,v)},
withCredentials:!0})});
g.Nu.prototype.Vd=g.rw(73,function(){for(var v=g.Jx(document,"track",void 0,this.T),J=0;J<v.length;J++)g.tx(v[J])});
g.Ls.prototype.Vd=g.rw(72,function(){this.mediaElement.Vd()});
g.Nu.prototype.jW=g.rw(71,function(){return!(!this.T.textTracks||!this.T.textTracks.addEventListener)});
g.Ls.prototype.jW=g.rw(70,function(){return this.mediaElement.jW()});
g.Nu.prototype.Fg=g.rw(69,function(){return!!this.T.textTracks});
g.Ls.prototype.Fg=g.rw(68,function(){return this.mediaElement.Fg()});
g.Nu.prototype.Rj=g.rw(67,function(v){for(var J=0;J<v.length;J++)this.T.appendChild(v[J])});
g.Ls.prototype.Rj=g.rw(66,function(v){this.mediaElement.Rj(v)});
g.F$.prototype.Rx=g.rw(65,function(v,J,G){this.zS.Rx(v,J,G)});
g.gL.prototype.Rx=g.rw(64,function(v,J,G){this.X.set(v,{iU:J,C4:G})});
g.XW.prototype.Rx=g.rw(63,function(v,J,G){this.YB.Rx(v,J,G)});
g.F$.prototype.GL=g.rw(62,function(v){return this.zS.GL(v)});
g.XW.prototype.GL=g.rw(61,function(v){var J=2;this.U.has(v)?J=0:g.UsU(this,v)&&(J=1);return J});
g.wr.prototype.Uq=g.rw(49,function(v){var J=this.app.oH();return J?J.Uq(v):!1});
g.AK.prototype.Uq=g.rw(48,function(v){return this.HH.CJ.Uq(v)});
g.OO.prototype.Uq=g.rw(47,function(v){return this.kP().some(function(J){return J.namespace===v})});
g.xF.prototype.Uq=g.rw(46,function(){return!1});
g.wr.prototype.ZM=g.rw(44,function(v,J){var G;(G=this.app.zi())==null||G.ZM(v,J)});
g.AK.prototype.ZM=g.rw(43,function(v,J){this.HH.ZM(v,J)});
g.EO.prototype.ZM=g.rw(42,function(v,J){v=[v,J];g.qa(this,g.AO(this.provider),"cfi",v)});
g.Ll.prototype.ZM=g.rw(41,function(v,J){this.qoe&&this.qoe.ZM(v,J)});
g.iT.prototype.ZM=g.rw(40,function(v,J){this.zG().ZM(v,J)});
g.xF.prototype.ZM=g.rw(39,function(){});
g.wr.prototype.ya=g.rw(38,function(v,J,G){var K;(K=this.app.zi())==null||K.ya(v,J,G)});
g.AK.prototype.ya=g.rw(37,function(v,J,G){this.HH.ya(v,J,G)});
g.EO.prototype.ya=g.rw(36,function(v,J,G){if(this.jl!==v||this.a$!==J)J=J==="rawcc"?"":J,G=[v,J,this.jl,G],g.qa(this,g.AO(this.provider),"cfs",G),this.jl=v,this.a$=J});
g.Ll.prototype.ya=g.rw(35,function(v,J,G){this.qoe&&this.qoe.ya(v,J,G)});
g.iT.prototype.ya=g.rw(34,function(v,J,G){this.zG().ya(v,J,G)});
g.xF.prototype.ya=g.rw(33,function(){});
g.Nj.prototype.wC=g.rw(20,function(){return this.U});
g.eo.prototype.wC=g.rw(19,function(){var v;return((v=this.zi())==null?void 0:v.gH())||null});
g.wr.prototype.gH=g.rw(18,function(){return this.app.wC()});
g.AK.prototype.gH=g.rw(17,function(){return this.HH.gH()});
g.iT.prototype.gH=g.rw(16,function(){var v;return((v=this.Qb)==null?void 0:v.wC())||null});
g.xF.prototype.gH=g.rw(15,function(){return null});
g.mL.prototype.uC=g.rw(1,function(v){return(v=this.Q1(v))?v.T:0});
g.V7.prototype.uC=g.rw(0,function(){return 0});
var iIG=/#(.)(.)(.)/,jnT=/^#(?:[0-9a-f]{3}){1,2}$/i,YoL={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};KK.prototype.contains=function(v){v=g.YY(this.segments,v);return v>=0||v<0&&(-v-1)%2===1};
KK.prototype.length=function(){return this.segments.length/2};
g.z(otG,g.X);g.q=otG.prototype;g.q.X4=function(){g.X.prototype.X4.call(this);this.Z&&this.Z.cancel()};
g.q.Wm=function(){this.seekTo(this.player.getCurrentTime())};
g.q.seekTo=function(v){v-=this.player.B$();var J=this.T;this.T=g.F8(this.oY.Zk(v).Vb);J!==this.T&&this.N&&this.N()};
g.q.reset=function(){this.L=new KK;this.j=-1;this.Z&&(this.Z.cancel(),this.Z=null)};
g.q.Jq=function(){this.Sl();var v;if(v=this.T!=null)v=this.T,v=v.T.Ji(v);if(v&&!this.Z&&!(this.T&&this.T.startTime-this.player.getCurrentTime()>30)){v=this.T;v=v.T.zQ(v);var J=v.Vb[0],G;if((G=this.player.getVideoData())==null?0:G.enableServerStitchedDai)if(G=this.player.gH()){var K=J.T.info.id,V=J.yb,Y=v.Vb[0].L;if(this.policy.qr){if(G=G.Q6(Y,V,K,3))v.L=G}else if(K=G.q2(Y,V,K,3))if(G=G.GL(V),G===0)K&&(v.T=new g.TV(K));else if(G===2){this.K.start();K2m(this)&&this.seekTo(this.player.getCurrentTime());
return}}J.T.index.QI(J.yb)?(this.L.contains(v.Vb[0].yb)||VAF(this,v),this.T=g.F8(v.Vb)):K2m(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()};
g.z(VS,g.q6);g.q=VS.prototype;g.q.Kz=function(v,J,G){var K=this;this.V1();J=qoX(this,v.getId());J||(J=v.languageCode,J=this.T.isManifestless?EtY(this,J,"386"):EtY(this,J));if(J){var V=(J.index.uC(J.index.eU())-J.index.getStartTime(J.index.eU()))*1E3,Y=this.S.B(),r=new g.JMs(Y),E=function(){K.Z&&K.Z.reset();K.j=!0};
Y.C("html5_keep_caption_data_after_seek")&&(E=null);this.Z=new otG(r,this.S,J,function(e,P){G.HL(e,v,P,V)},this.K||g.bD(J.info),E)}};
g.q.SV=function(){var v=this.j;this.j=!1;return v};
g.q.rT=function(v){var J=this.S.B().C("html5_fallback_if_rawcc_missing");var G=this.T.T.rawcc!=null;if(!this.K||!G&&J)J=this.T.isManifestless?rxX(this,"386"):rxX(this);else{if(!G){this.logger.T(386248249,"rawcc used but unavailable");return}J=[new g.tW({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.tW({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}J=g.n(J);
for(G=J.next();!G.done;G=J.next())g.rP(this.X,G.value);v.Tb()};
g.q.V1=function(){this.Z&&(this.Z.dispose(),this.Z=null)};
g.q.cD=function(){return""};
g.q.CU=function(){this.Z&&(this.Z.reset(),this.S.RA("captions"))};
var Tg=/^#(?:[0-9a-f]{3}){1,2}$/i;var DhU=["left","right","center","justify"];g.z(Y7,g.F);g.q=Y7.prototype;g.q.VZ=function(v,J){this.WH=v;this.Nr=J;var G=g.sG(this.element,this.element.parentElement);this.wh=v-G.x;this.o$=J-G.y};
g.q.ac=function(v,J){if(v!==this.WH||J!==this.Nr){g.K7(this.element,"ytp-dragging")||g.Vj(this.element,"ytp-dragging");var G=g.lt(this.element);v=v-this.wh-.02*this.playerWidth;var K=J-this.o$-.02*this.playerHeight,V=(v+G.width/2)/this.maxWidth*3;V=Math.floor(g.nk(V,0,2));var Y=(K+G.height/2)/this.maxHeight*3;Y=Math.floor(g.nk(Y,0,2));J=V+Y*3;v=(v+V/2*G.width)/this.maxWidth;v=g.nk(v,0,1)*100;G=(K+Y/2*G.height)/this.maxHeight;G=g.nk(G,0,1)*100;this.X.params.xN=J;this.X.params.lr=G;this.X.params.Tk=
v;this.X.params.isDefault=!1;this.T.xN=J;this.T.lr=G;this.T.Tk=v;this.T.isDefault=!1;this.Ti.xN=J;this.Ti.lr=G;this.Ti.Tk=v;this.Ti.isDefault=!1;this.V0()}};
g.q.lL=function(){g.rz(this.element,"ytp-dragging")};
g.q.V0=function(){this.mF(this.K)};
g.q.getType=function(){return this.type};
g.q.mF=function(v){var J=this.g_?0:Math.min(this.GD(),this.maxWidth),G=this.mw(),K=this.g_;if(K){var V=getComputedStyle(this.L.parentNode);V=r$(V.borderLeftWidth)+r$(V.borderRightWidth)+r$(V.paddingLeft)+r$(V.paddingRight)}else V=0;var Y=V;V="";this.X.params.Ah===3&&(V="rotate(180deg)");var r=K?"calc(96% - "+Y+"px)":"96%";g.ep(this.element,{top:0,left:0,right:"",bottom:"",width:J?J+"px":"",height:G?G+"px":"","max-width":r,"max-height":r,margin:"",transform:""});this.pk(v);V={transform:V,top:"",left:"",
width:J?J+"px":"",height:G?G+"px":"","max-width":"","max-height":""};var E=this.T.Tk*.96+2;r=this.T.xN;switch(r){case 0:case 3:case 6:(K=this.T.dJ.fontSizeIncrement)&&K>0&&this.T.Ah!==2&&this.T.Ah!==3&&(E=Math.max(E/(1+K*2),2));V.left=E+"%";break;case 1:case 4:case 7:V.left=E+"%";E=this.L.offsetWidth;J||E?(J=J||E+1,V.width=J+"px",V["margin-left"]=K?J/-2-Y/2+"px":J/-2+"px"):V.transform+=" translateX(-50%)";break;case 2:case 5:case 8:V.right=100-E+"%"}K=this.T.lr*.96+2;switch(r){case 0:case 1:case 2:V.top=
K+"%";break;case 3:case 4:case 5:V.top=K+"%";(G=G||this.element.clientHeight)?(V.height=G+"px",V["margin-top"]=G/-2+"px"):V.transform+=" translateY(-50%)";break;case 6:case 7:case 8:V.bottom=100-K+"%"}g.ep(this.element,V);if(this.j){G=this.L.offsetHeight;K=1;for(J=0;J<v.length;J++)V=v[J],typeof V.text==="string"&&(K+=V.text.split("\n").length-1,V.append||J===0||K++);G/=K;this.j.style.height=G+"px";this.j.style.width=G+"px";this.element.style.paddingLeft=G+5+"px";this.element.style.paddingRight=G+
5+"px";v=Number(this.element.style.marginLeft.replace("px",""))-G-5;G=Number(this.element.style.marginRight.replace("px",""))-G-5;this.element.style.marginLeft=v+"px";this.element.style.marginRight=G+"px"}};
g.q.pk=function(v){var J;for(J=0;J<v.length&&v[J]===this.K[J];J++);if(this.Mr||this.K.length>J)J=0,this.Mr=!1,this.K=[],this.U=this.YB=this.qr=null,g.PM(this.L);for(;J<v.length;J++)zMX(this,v[J])};
g.q.GD=function(){return 0};
g.q.mw=function(){return 0};
g.q.toString=function(){return g.F.prototype.toString.call(this)};dhN.prototype.clear=function(){this.Z=this.time=this.mode=0;this.T=[];this.reset()};
dhN.prototype.reset=function(){this.mode=0;this.L.reset(0);this.J.reset(1)};
var snL=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];qP.prototype.set=function(v){this.type=v};
qP.prototype.get=function(){return this.type};
EJ.prototype.clear=function(){this.state=0};
EJ.prototype.update=function(){this.state=this.state===2?1:0};
EJ.prototype.B1=function(){return this.state!==0};
EJ.prototype.matches=function(v,J){return this.B1()&&v===this.Fx&&J===this.G2};
L26.prototype.reset=function(){this.timestamp=this.T=0};
eL.prototype.updateTime=function(v){for(var J=1;J<=15;++J)for(var G=1;G<=32;++G)this.Z[J][G].timestamp=v};
eL.prototype.debugString=function(){for(var v="\n",J=1;J<=15;++J){for(var G=1;G<=32;++G){var K=this.Z[J][G];v=K.T===0?v+"_":v+String.fromCharCode(K.T)}v+="\n"}return v};
eL.prototype.reset=function(v){for(var J=0;J<=15;J++)for(var G=0;G<=32;G++)this.Z[J][G].reset();this.L=v;this.T=0;this.X=this.row=1};
var yx8=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],wMF=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],OIY=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],UhY=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];fym.prototype.reset=function(v,J){this.J=J;this.style.set(2);this.X=this.j;this.L=this.K;this.T=this.X;var G=(v<<2)+(J<<1);this.j.reset(G);this.K.reset(G);this.text.reset((v<<2)+(J<<1)+1)};
ntX.prototype.reset=function(v){this.J=v;this.X.clear();this.L=this.Z;this.Z.reset(v,0);this.j.reset(v,1)};XMo.prototype.L=function(){};g.z(Ia,g.o8);Ia.prototype.toString=function(){return g.o8.prototype.toString.call(this)};g.z(hT,g.X);hT.prototype.R3=function(){return[]};
hT.prototype.reset=function(){};g.z(zg,g.o8);zg.prototype.toString=function(){return g.o8.prototype.toString.call(this)};
var nK=0;g.z(d$,hT);d$.prototype.reset=function(){this.j={};this.X=this.T=null;this.J=!0};
d$.prototype.R3=function(v,J){v=v.firstChild;v.getAttribute("format");J=J||0;Number.isFinite(J);v=Array.from(v.childNodes);v=g.n(v);for(var G=v.next();!G.done;G=v.next())if(G=G.value,G.nodeType===1)switch(G.tagName){case "head":var K=G;break;case "body":var V=G}if(K)for(K=Array.from(K.childNodes),K=g.n(K),v=K.next();!v.done;v=K.next())if(v=v.value,v.nodeType===1)switch(v.tagName){case "pen":G=v.getAttribute("id");var Y=this.pens,r={},E=v.getAttribute("p");E&&Object.assign(r,this.pens[E]);E=Ra(v,"b");
E!=null&&(r.bold=E);E=Ra(v,"i");E!=null&&(r.italic=E);E=Ra(v,"u");E!=null&&(r.underline=E);E=lJ(v,"et");E!=null&&(r.charEdgeStyle=E);E=lJ(v,"of");E!=null&&(r.offset=E);E=pK(v,"bc");E!=null&&(r.background=E);E=pK(v,"ec");E!=null&&(r.Ry=E);E=pK(v,"fc");E!=null&&(r.color=E);E=lJ(v,"fs");E!=null&&E!==0&&(r.fontFamily=E);E=sJ(v,"sz");E!==void 0&&(r.fontSizeIncrement=E/100-1);E=sJ(v,"bo");E!==void 0&&(r.backgroundOpacity=E/255);E=sJ(v,"fo");E!==void 0&&(r.textOpacity=E/255);E=lJ(v,"rb");E!=null&&E!==10&&
E!==0&&(r.Kq=E>10?E-1:E);v=lJ(v,"hg");v!=null&&(r.DF=v);Y[G]=r;break;case "ws":G=v.getAttribute("id");this.U[G]=ayN(this,v);break;case "wp":G=v.getAttribute("id"),this.K[G]=Axm(this,v)}if(V){K=[];V=Array.from(V.childNodes);V=g.n(V);for(v=V.next();!v.done;v=V.next())if(v=v.value,v.nodeType===1)switch(v.tagName){case "w":this.T=F2N(this,v,J,!1);(v=this.j[this.T.id])&&v.end>this.T.start&&(v.end=this.T.start);this.j[this.T.id]=this.T;K.push(this.T);break;case "p":var e=v;E=J;G=[];Y=e.getAttribute("w")||
this.L;r=!!Ra(e,"a");E=(sJ(e,"t")||0)+E;var P=sJ(e,"d")||5E3;r||(!this.J&&this.X&&this.X.windowId===Y&&this.X.end>E&&(this.X.end=E),this.X&&this.X.text==="\n"&&(this.X.text=""));var D=r?6:5,t=e.getAttribute("p");t=t?this.pens[t]:null;var B=Array.from(e.childNodes);B.length&&(this.J=e.getAttribute("d")!=null);for(e=0;e<B.length;e++){var I=B[e],h=void 0;e>0&&(r=!0);var R=void 0;I.nodeType===1&&(R=I);if(R&&R.tagName==="s"){if((I=(I=R.getAttribute("p"))?this.pens[I]:null)&&I.Kq&&(I.Kq===1?(I=B.slice(e,
e+4),I.length===4&&(h=cx6(E,P,Y,r,D,I,this.pens),e+=3)):h=cx6(E,P,Y,r,D,[R],this.pens)),!h){var T=R;h=E;R=P;I=Y;var L=r,O=D,x=T.textContent?T.textContent:"",f=T.getAttribute("p");f=f?this.pens[f]:null;T=sJ(T,"t")||0;h=new Ia(h+T,R-T,O,I,x,L,f)}}else h=new Ia(E,P,D,Y,I.textContent||"",r,t);G.push(h);this.X=h}if(G.length>0)for(G[0].windowId===this.L&&(this.T=F2N(this,v,J,!0),K.push(this.T)),v=g.n(G),G=v.next();!G.done;G=v.next())G=G.value,G.windowId=this.T.id,this.T.T.push(G),K.push(G)}J=K}else J=[];
return J};var yGL=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.z(LK,hT);LK.prototype.reset=function(){this.X.clear()};
LK.prototype.R3=function(v,J){var G=JSON.parse(v);if(!G)return[];if(G.pens){v=0;for(var K=g.n(G.pens),V=K.next();!V.done;V=K.next()){V=V.value;var Y={},r=V.pParentId;r&&Object.assign(Y,this.T.get(r));V.bAttr&&(Y.bold=!0);V.iAttr&&(Y.italic=!0);V.uAttr&&(Y.underline=!0);r=V.ofOffset;r!=null&&(Y.offset=r);V.szPenSize!==void 0&&(Y.fontSizeIncrement=V.szPenSize/100-1);r=V.etEdgeType;r!=null&&(Y.charEdgeStyle=r);V.ecEdgeColor!==void 0&&(Y.Ry=yS(V.ecEdgeColor));r=V.fsFontStyle;r!=null&&r!==0&&(Y.fontFamily=
r);V.fcForeColor!==void 0&&(Y.color=yS(V.fcForeColor));V.foForeAlpha!==void 0&&(Y.textOpacity=V.foForeAlpha/255);V.bcBackColor!==void 0&&(Y.background=yS(V.bcBackColor));V.boBackAlpha!==void 0&&(Y.backgroundOpacity=V.boBackAlpha/255);(r=V.rbRuby)&&r!==10&&(Y.Kq=r>10?r-1:r,Y.textEmphasis=yGL.get(Y.Kq));V.hgHorizGroup&&(Y.DF=V.hgHorizGroup);this.T.set(v++,Y)}}if(G.wsWinStyles)for(v=0,K=g.n(G.wsWinStyles),V=K.next();!V.done;V=K.next())V=V.value,Y={},(r=V.wsParentId)?Object.assign(Y,this.L.get(r)):Object.assign(Y,
this.J),V.mhModeHint!==void 0&&(Y.D4=V.mhModeHint),V.juJustifCode!==void 0&&(Y.textAlign=V.juJustifCode),V.pdPrintDir!==void 0&&(Y.Ah=V.pdPrintDir),V.sdScrollDir!==void 0&&(Y.PK=V.sdScrollDir),V.wfcWinFillColor!==void 0&&(Y.windowColor=yS(V.wfcWinFillColor)),V.wfoWinFillAlpha!==void 0&&(Y.windowOpacity=V.wfoWinFillAlpha/255),this.L.set(v++,Y);if(G.wpWinPositions)for(v=0,K=g.n(G.wpWinPositions),V=K.next();!V.done;V=K.next())V=V.value,Y={},(r=V.wpParentId)&&Object.assign(Y,this.Z.get(r)),V.ahHorPos!==
void 0&&(Y.Tk=V.ahHorPos),V.apPoint!==void 0&&(Y.xN=V.apPoint),V.avVerPos!==void 0&&(Y.lr=V.avVerPos),V.ccCols!==void 0&&(Y.z2=V.ccCols),V.rcRows!==void 0&&(Y.oO=V.rcRows),this.Z.set(v++,Y);if(G.events){v=[];G=g.n(G.events);for(K=G.next();!K.done;K=G.next()){var E=K.value;V=(E.tStartMs||0)+J;Y=E.dDurationMs||0;if(E.id)r=String(E.id),K=HIF(this,E,V,Y,r),v.push(K),this.X.set(r,K);else{E.wWinId?r=E.wWinId.toString():(r="_"+nK++,K=HIF(this,E,V,Y,r),v.push(K),this.X.set(r,K));K=v;var e=E;Y===0&&(Y=5E3);
E=this.X.get(r);var P=!!e.aAppend,D=P?6:5,t=e.segs,B=null;e.pPenId&&(B=this.T.get(e.pPenId));for(e=0;e<t.length;e++){var I=t[e],h=I.utf8;if(h){var R=I.tOffsetMs||0,T=null;I.pPenId&&(T=this.T.get(I.pPenId));if((E.params.D4!=null?E.params.D4:E.T.length>1?1:0)===2&&P&&h==="\n")continue;I=null;var L=[],O;if(O=T&&T.Kq===1){O=t;var x=e;if(x+3>=O.length||!O[x+1].pPenId||!O[x+2].pPenId||!O[x+3].pPenId)O=!1;else{var f=O[x+1].pPenId;(f=this.T.get(f))&&f.Kq&&f.Kq===2?(f=O[x+2].pPenId,f=this.T.get(f),!f||!f.Kq||
f.Kq<3?O=!1:(f=O[x+3].pPenId,O=(f=this.T.get(f))&&f.Kq&&f.Kq===2?!0:!1)):O=!1}}if(O)R=t[e+1].utf8,I=t[e+3].utf8,O=t[e+2].utf8,x=this.T.get(t[e+2].pPenId),h=ksS(h,R,O,I,x),I=new Ia(V,Y,D,r,h,P,T),e+=3;else{if(h.indexOf("<")>-1){var c=void 0;L=T;O=B;x=V;f=Y;var b=R,M=D,Jw=P,Kf=[],j8=g.NF("<html>"+h+"</html>");if(!j8.getElementsByTagName("parsererror").length&&((c=j8.firstChild)==null?0:c.childNodes.length))for(c=g.n(j8.firstChild.childNodes),j8=c.next();!j8.done;j8=c.next()){j8=j8.value;var a=void 0,
C=void 0,d=(C=(a=j8.textContent)==null?void 0:a.replace(/\n/g,""))!=null?C:"";if(j8.nodeType!==3||d&&d.match(/^ *$/)==null){a={};Object.assign(a,L||O);C=void 0;switch((C=j8)==null?void 0:C.tagName){case "b":a.bold=!0;break;case "i":a.italic=!0;break;case "u":a.underline=!0}Kf.push(new Ia(x+b,f-b,M,E.id,d,Jw,a))}}L=Kf}L.length||(L=[new Ia(V+R,Y-R,D,E.id,h,P,T||B)])}if(L.length)for(P=g.n(L),T=P.next();!T.done;T=P.next())T=T.value,K.push(T),E.T.push(T);else I&&(K.push(I),E.T.push(I))}P=!0}}}J=v}else J=
[];return J};g.z(w$,g.q6);w$.prototype.Kz=function(v,J,G){bko(this.videoData.videoId,v.vssId,G.HL)};
w$.prototype.rT=function(v){if(this.audioTrack)for(var J=g.n(this.audioTrack.captionTracks),G=J.next();!G.done;G=J.next())g.rP(this.X,G.value);v.Tb()};g.z(OJ,Y7);OJ.prototype.pk=function(v){var J=this.X.T;Y7.prototype.pk.call(this,v);for(v=v.length;v<J.length;v++){var G=J[v];if(Y&&G.T===V)var K=Y;else{K={};Object.assign(K,G.T);Object.assign(K,wp_);var V=G.T;var Y=K}zMX(this,G,K)}};
var wp_={IeB:!0};g.z(UJ,XMo);UJ.prototype.L=function(v,J,G,K,V){if(G<K){var Y="_"+nK++;G=G/1E3-this.j;K=K/1E3-this.j;v=new zg(G,K-G,5,Y,{textAlign:0,xN:0,Tk:J*2.5,lr:v*5.33});V=new Ia(G,K-G,5,Y,V);this.X.push(v);this.X.push(V)}};
g.z(SL,hT);SL.prototype.R3=function(v){v=new UJ(v,v.byteLength,this.X);if(MA6(v)){for(;v.byteOffset<v.T.byteLength;)for(v.version===0?v.Z=mA(v)*(1E3/45):v.version===1&&(v.Z=mA(v)*4294967296+mA(v)),v.J=x7(v);v.J>0;v.J--){var J=x7(v),G=x7(v),K=x7(v);J&4&&(J&3)===this.track&&(this.track===0||this.track===1)&&(J=this.T,J.T.push({time:v.Z,type:this.track,vc:G,sC:K,order:J.T.length}))}pMU(this.T,v);return v.X}return[]};
SL.prototype.reset=function(){this.T.clear()};g.z(fK,Y7);g.q=fK.prototype;g.q.V0=function(){g.CM(this.xB)};
g.q.Oc=function(){this.RY&&this.element.removeEventListener("transitionend",this.Oc,!1);g.rz(this.element,"ytp-rollup-mode");this.mF(this.OR,!0)};
g.q.mw=function(){return this.Z?this.oY:this.N};
g.q.GD=function(){return this.Z?this.N:this.oY};
g.q.mF=function(v,J){this.OR=v;if(this.X.params.oO){for(var G=0,K=0;K<this.K.length&&G<v.length;K++)this.K[K]===v[G]&&G++;G>0&&G<v.length&&(v=this.K.concat(v.slice(G)));this.UR=this.oY;this.N=this.oY=0;Y7.prototype.mF.call(this,v);bIm(this,J)}Y7.prototype.mF.call(this,v)};jpo.prototype.unload=function(){this.T!=null&&(this.S.removeEventListener("sabrCaptionsDataLoaded",this.T),this.T=null);this.f0=[];this.S.publish("sabrCaptionsBufferedRangesUpdated",this.f0)};
jpo.prototype.xb=function(v){return{formatId:g.iS(v.info.T.info,this.yn),yb:v.info.yb+(this.yn?0:1),startTimeMs:v.info.L*1E3,durationMs:v.info.U*1E3}};g.z(JGU,g.q6);g.q=JGU.prototype;g.q.Kz=function(v,J,G){this.V1();J=v.getId();J=J!=null&&J in this.T.T?this.T.T[J]:null;J||(J=v.languageCode,J=this.T.isManifestless?obU(this,J,"386"):obU(this,J));J&&(this.Z=v,this.j=J,vbo(this.K,G),this.S.publish("sabrCaptionsTrackChanged",g.iS(J.info,this.T.yn)))};
g.q.rT=function(v){var J=this.T.isManifestless?GDA(this,"386"):GDA(this);J=g.n(J);for(var G=J.next();!G.done;G=J.next())g.rP(this.X,G.value);v.Tb()};
g.q.V1=function(){this.Z&&(this.Z=this.j=null,this.K.unload(),this.S.publish("sabrCaptionsTrackChanged",null))};
g.q.cD=function(){return""};
g.q.CU=function(){this.S.RA("captions")};g.z(Zn,hT);
Zn.prototype.R3=function(v,J){var G=[];v=v.split(OQL);for(var K=1;K<v.length;K++){var V=v[K],Y=J;if(V!==""&&!UCG.test(V)){var r=xCU.exec(V);if(r&&r.length>=4){var E=YFm(r[1]),e=YFm(r[2])-E;E+=Y;var P=(r=r[3])?r.split(" "):[];r={};var D=null;var t="";var B=null,I="";P=g.n(P);for(var h=P.next();!h.done;h=P.next())if(h=h.value.split(":"),h.length===2){var R=h[1];switch(h[0]){case "line":h=R.split(",");h[0].endsWith("%")&&(D=h[0],r.lr=Number.parseInt(D,10),h.length===2&&(t=h[1].trim()));break;case "position":h=
R.split(",");B=h[0];r.Tk=Number.parseInt(B,10);h.length===2&&(I=h[1].trim());break;case "align":switch(R){case "start":r.textAlign=0;break;case "middle":r.textAlign=2;break;case "end":r.textAlign=1}}}D||t||(t="end");if(!B)switch(r.textAlign){case 0:r.Tk=0;break;case 1:r.Tk=100;break;case 2:r.Tk=50}if(r.textAlign!=null){D=0;switch(t){case "center":D+=3;break;case "end":D+=6;break;default:D+=0}switch(I){case "line-left":D+=0;break;case "center":D+=1;break;case "line-right":D+=2;break;default:switch(r.textAlign){case 0:D+=
0;break;case 2:D+=1;break;case 1:D+=2}}t=D<0||D>8?7:D;r.xN=t}V=V.substring(xCU.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");I=r;r=V;V={};if(r.indexOf("<")<0&&r.indexOf("&")<0)Y=rGX(E,e,5,I),e=new Ia(E,e,5,Y.id,r,!1,g.Xb(V)?void 0:V),G.push(Y),G.push(e),Y.T.push(e);else for(t=r.split(mCS),t.length===1?(r=5,I=rGX(E,e,r,I)):(D=r=6,I=Object.assign({z2:32},I),I=new zg(E,e,D,"_"+nK++,I)),G.push(I),D=E,B=0;B<t.length;B++)P=t[B],B%2===0?(h=g.NF("<html>"+P+"</html>"),h.getElementsByTagName("parsererror").length?
(R=h.createElement("span"),R.appendChild(h.createTextNode(P))):R=h.firstChild,VCX(this,D,e-(D-E),r,I,B>0,R,V,G)):D=YFm(P)+Y}xCU.lastIndex=0}}return G};
var UCG=/^NOTE/,OQL=/(?:\r\n|\r|\n){2,}/,xCU=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),mCS=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.ys.FZ(Zn,{R3:"wvppt"});g.z(uJ,g.X);
uJ.prototype.R3=function(v,J,G,K){K=K||0;G=EbX(this,v,G||0);v=[];try{for(var V=g.n(G),Y=V.next();!Y.done;Y=V.next()){var r=Y.value,E=r.trackData,e=r.RZ;if(typeof E!=="string"){G=v;var P=G.concat,D=J,t=E,B=e,I=K;if(!Qn8(t))throw Error("Invalid binary caption track data");this.T||(this.T=new SL(I,D));var h=this.T.R3(t,B);var R=P.call(G,h)}else{if(E.substring(0,6)==="WEBVTT"){G=v;var T=G.concat;this.T||(this.T=new Zn);var L=this.T.R3(E,e);Math.random()<.01&&g.Zl(Error("Deprecated subtitles format in web player: WebVTT"));var O=
T.call(G,L)}else{G=v;var x=G.concat;a:{D=J;if(E[0]==="{")try{this.T||(this.T=new LK(ebT(D)));var f=this.T.R3(E,e);break a}catch(j8){g.fW(j8);f=[];break a}var c=g.NF(E);if(!c||!c.firstChild){var b=Error("Invalid caption track data");b.params=E;throw b;}if(c.firstChild.tagName==="timedtext"){if(Number(c.firstChild.getAttribute("format"))===3){t=c;this.T||(this.T=new d$(ebT(D),this.EB));f=this.T.R3(t,e);break a}var M=Error("Unsupported subtitles format in web player (Format2)");M.params=E;throw M;}if(c.firstChild.tagName===
"transcript"){var Jw=Error("Unsupported subtitles format in web player (Format1)");Jw.params=E;throw Jw;}var Kf=Error("Invalid caption track data");Kf.params=E;throw Kf;}O=x.call(G,f)}R=O}v=R}return v}catch(j8){return this.logger.T(187101178,"Captions parsing failed: "+j8.message+". "),this.clear(),[]}};
uJ.prototype.clear=function(){this.T&&this.T.dispose();this.T=null};
uJ.prototype.reset=function(){this.T&&this.T.reset()};
uJ.prototype.X4=function(){g.X.prototype.X4.call(this);this.clear()};var HP={windowColor:"#080808",windowOpacity:0,textAlign:2,xN:7,Tk:50,lr:100,isDefault:!0,dJ:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.z(g$,g.YQ);g.q=g$.prototype;g.q.X4=function(){if(this.J||this.Mr){var v=this.S.LY();v&&!v.Sl()&&v.Vd()}else LKm(this,!1);g.YQ.prototype.X4.call(this)};
g.q.YF=function(){return this.EB.C("html5_honor_caption_availabilities_in_audio_track")&&this.L!=="LIVE"&&this.L!=="SABR_LIVE"};
g.q.nB=function(){if(this.xB)return this.J||this.Mr;var v=this.getAudioTrack();if(this.YF()){if(!v.captionTracks.length)return!1;if(!this.T)return!0}v=MKY(v,g.bh(this.EB));return v==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:v==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?Xh(this):BQ8(this)||Xh(this)?!0:IJm(this)};
g.q.load=function(){g.YQ.prototype.load.call(this);this.N=this.getAudioTrack();if(this.T)this.X&&(this.BH.clear(),this.J?zbT(this,!0):this.player.getPresentingPlayerType()!==3&&this.T.Kz(this.X,"json3",this.g_),this.J||this.Mr||NP(this)||this.player.Tr("captionschanged",g.IG(this.X)));else{var v;this.L==="OFFLINE"?v=new w$(this.player,this.videoData,this.getAudioTrack()):this.L==="SABR_LIVE"?v=new JGU(this.videoData.T,this.player):this.L==="LIVE"?v=new VS(this.videoData.T,this.player):this.L==="INNERTUBE"?
v=new g.ED(this.player,this.videoData,this.getAudioTrack()):v=new g.Pv(this.player,this.videoData.Bv,this.videoData.videoId,g.DWX(this.videoData),this.videoData.Uj,this.videoData.eventId);this.T=v;g.k(this,this.T);this.T.rT(this.g_)}};
g.q.unload=function(){this.J&&this.X?zbT(this,!1):(this.jl&&g.b4(this.jl),this.player.RA("captions"),this.qr=[],this.T&&this.T.V1(),this.BH.clear(),this.oY&&this.player.oR(this.oY),this.Qx());g.YQ.prototype.unload.call(this);this.player.qw();this.player.Tr("captionschanged",{})};
g.q.create=function(){this.nB()&&this.load();var v;a:{var J,G,K;if(this.EB.C("web_player_nitrate_promo_tooltip")&&((J=this.videoData.getPlayerResponse())==null?0:(G=J.captions)==null?0:(K=G.playerCaptionsTracklistRenderer)==null?0:K.enableTouchCaptionsNitrate)){var V,Y;if(J=(v=this.videoData.getPlayerResponse())==null?void 0:(V=v.captions)==null?void 0:(Y=V.playerCaptionsTracklistRenderer)==null?void 0:Y.captionTracks)for(v=g.n(J),V=v.next();!V.done;V=v.next())if(V=V.value,V.kind==="asr"&&V.languageCode===
"en"){v=!0;break a}}v=!1}v&&this.S.publish("showpromotooltip",this.K.element)};
g.q.Tb=function(){var v=MKY(this.player.getAudioTrack(),g.bh(this.EB));var J=v==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?cP(this,this.U):v==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&Xh(this)?k7(this):BQ8(this)||this.U||IJm(this)?cP(this,this.U):Xh(this)?k7(this):null;if(this.J||this.Mr){var G=g.WT(this.T.X,!0);v=[];for(var K=0;K<G.length;K++){var V=G[K],Y=g.qh("TRACK");Y.setAttribute("kind","subtitles");Y.setAttribute("label",g.BG(V));Y.setAttribute("srclang",g.hW(V));Y.setAttribute("id",V.toString());
this.Mr||Y.setAttribute("src",this.T.cD(V,"vtt"));V===J&&Y.setAttribute("default","1");v.push(Y)}J=this.S.LY();J.Rj(v);v=J.ZZ();this.o$&&this.Ze.G(v.textTracks,"change",this.rIe)}else!this.X&&J&&Fh(this,J),this.player.Tr("onCaptionsTrackListChanged"),this.player.UN("onApiChange")};
g.q.rIe=function(){for(var v=this.S.LY().ZZ().textTracks,J=null,G=0;G<v.length;G++)if(v[G].mode==="showing")a:{J=g.WT(this.T.X,!0);for(var K=0;K<J.length;K++)if(J[K].toString()===v[G].id){J=J[K];break a}J=null}(this.loaded?this.X:null)!==J&&Fh(this,J,!0)};
g.q.vPb=function(){!this.X&&this.J||this.unload()};
g.q.HL=function(v,J,G,K){if(v){var V;dCL(this,(V=this.X)!=null?V:void 0);this.T.SV()&&(this.qr=[],this.S.RA("captions"),oa(this.YB),this.BH.reset());if(this.videoData.Mj){var Y;G=((Y=G)!=null?Y:0)+this.videoData.Mj}v=this.BH.R3(v,J,G,K);if(this.WH)for(J=g.n(v),G=J.next();!G.done;G=J.next())G=G.value,G.Z=this.videoData.clientPlaybackNonce,G.Z7=this.videoData.Mj;J=!this.EB.C("html5_keep_caption_data_after_seek")&&(this.L==="LIVE"||this.L==="SABR_LIVE");this.player.oR(v,void 0,J);!this.U||this.Mr||NP(this)||
g.yW(this.EB)||g.uh(this.EB)||g.gy(this.EB)||this.EB.Mr==="shortspage"||this.player.isInline()||(g.b4(this.jl),v=NAX({xN:0,Tk:5,lr:5,oO:2,textAlign:0,Ah:0,lang:"en"}),this.Gi=[v],J=["Click "," for settings"],this.Nr||(G=new g.en(g.ON()),g.k(this,G),this.Nr=G.element),G=v.end-v.start,(K=g.BG(this.X))&&this.Gi.push(new Ia(v.start,G,0,v.id,K)),this.Gi.push(new Ia(v.start,G,0,v.id,J[0]),new Ia(v.start,G,0,v.id,this.Nr,!0),new Ia(v.start,G,0,v.id,J[1],!0)),this.player.oR(this.Gi),g.Wq(this.jl));!this.U||
this.Mr||NP(this)||(g.bh(this.EB)?aa(this,!0):AT(this,!0),this.N&&(this.N.L=this.X),this.player.qw());this.U=!1}};
g.q.onCueRangeEnter=function(v){this.qr.push(v);oa(this.YB)};
g.q.onCueRangeExit=function(v){g.j5(this.qr,v);this.T instanceof VS&&this.T.K&&this.player.yS([v]);oa(this.YB)};
g.q.getCaptionWindowContainerId=function(){return this.K.element.id};
g.q.I0l=function(){ppF(this,this.Gi);this.Gi=null};
g.q.uE=function(){var v=this;if(!this.d_||!this.J){this.YB.stop();g.AAU(this.RY);this.qr.sort(g.KT);var J=this.qr;if(this.oY){var G=g.E_(J,function(Y){return this.oY.indexOf(Y)===-1},this);
G.length&&(J=G)}J=g.n(J);for(G=J.next();!G.done;G=J.next())RbU(this,G.value);J=g.n(Object.entries(this.dh));var K=J.next();for(G={};!K.done;G={VW:void 0,va:void 0},K=J.next()){var V=g.n(K.value);K=V.next().value;V=V.next().value;G.VW=K;G.va=V;this.RY[G.VW]?(G.va.element.parentNode||(G.va instanceof fK||G.va instanceof OJ||g.UA(this.dh,function(Y){return function(r,E){E!==Y.VW&&r.X.params.xN===Y.va.X.params.xN&&r.X.params.Tk===Y.va.X.params.Tk&&r.X.params.lr===Y.va.X.params.lr&&(r.dispose(),delete v.dh[E]);
return E===Y.VW}}(G),this),this.K.element.appendChild(G.va.element)),G.va.mF(this.RY[G.VW])):(G.va.dispose(),delete this.dh[G.VW])}}};
g.q.Oqw=function(){DC8(this,{},!0);this.player.Tr("captionssettingschanged")};
g.q.h8=function(){var v=HP.dJ;v={background:v.background,backgroundOpacity:v.backgroundOpacity,charEdgeStyle:v.charEdgeStyle,color:v.color,fontFamily:v.fontFamily,fontSizeIncrement:v.fontSizeIncrement,fontStyle:v.bold&&v.italic?3:v.bold?1:v.italic?2:0,textOpacity:v.textOpacity,windowColor:HP.windowColor,windowOpacity:HP.windowOpacity};var J=JxA()||{};J.background!=null&&(v.background=J.background);J.backgroundOverride!=null&&(v.backgroundOverride=J.backgroundOverride);J.backgroundOpacity!=null&&(v.backgroundOpacity=
J.backgroundOpacity);J.backgroundOpacityOverride!=null&&(v.backgroundOpacityOverride=J.backgroundOpacityOverride);J.charEdgeStyle!=null&&(v.charEdgeStyle=J.charEdgeStyle);J.charEdgeStyleOverride!=null&&(v.charEdgeStyleOverride=J.charEdgeStyleOverride);J.color!=null&&(v.color=J.color);J.colorOverride!=null&&(v.colorOverride=J.colorOverride);J.fontFamily!=null&&(v.fontFamily=J.fontFamily);J.fontFamilyOverride!=null&&(v.fontFamilyOverride=J.fontFamilyOverride);J.fontSizeIncrement!=null&&(v.fontSizeIncrement=
J.fontSizeIncrement);J.fontSizeIncrementOverride!=null&&(v.fontSizeIncrementOverride=J.fontSizeIncrementOverride);J.fontStyle!=null&&(v.fontStyle=J.fontStyle);J.fontStyleOverride!=null&&(v.fontStyleOverride=J.fontStyleOverride);J.textOpacity!=null&&(v.textOpacity=J.textOpacity);J.textOpacityOverride!=null&&(v.textOpacityOverride=J.textOpacityOverride);J.windowColor!=null&&(v.windowColor=J.windowColor);J.windowColorOverride!=null&&(v.windowColorOverride=J.windowColorOverride);J.windowOpacity!=null&&
(v.windowOpacity=J.windowOpacity);J.windowOpacityOverride!=null&&(v.windowOpacityOverride=J.windowOpacityOverride);return v};
g.q.K6=function(v,J){var G={};Object.assign(G,JxA());Object.assign(G,v);DC8(this,G,J);this.player.Tr("captionssettingschanged")};
g.q.Qx=function(){!this.J&&this.loaded&&(g.y2(this.dh,function(v,J){v.dispose();delete this.dh[J]},this),this.uE())};
g.q.jJ=function(v,J){switch(v){case "fontSize":if(isNaN(J))break;v=g.nk(J,-2,4);this.K6({fontSizeIncrement:v});return v;case "reload":J&&!this.J&&Fh(this,this.X,!0);break;case "stickyLoading":J!==void 0&&this.EB.K&&(g.bh(this.EB)?aa(this,!!J):AT(this,!!J));break;case "track":return TQ6(this,J);case "tracklist":return this.T?g.yn(g.WT(this.T.X,!(!J||!J.includeAsr)),function(G){return g.IG(G)}):[];
case "translationLanguages":return this.T?this.T.J.map(function(G){return Object.assign({},G)}):[];
case "sampleSubtitles":this.J||J===void 0||LKm(this,!!J);break;case "sampleSubtitlesCustomized":this.J||LKm(this,!!J,J);break;case "recommendedTranslationLanguages":return g.An();case "defaultTranslationSourceTrackIndices":return this.T?this.T.U:[]}};
g.q.getOptions=function(){var v="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.EB.K&&v.push("stickyLoading");return v};
g.q.M_=function(){var v=this.X;if(this.S.Uq("captions")){if(this.EB.C("html5_modify_caption_vss_logging")){var J;return(v=(J=this.videoData.YE)!=null?J:null)?{cc:g.mJX(v)}:{}}if(v)return J=v.vssId,v.translationLanguage&&J&&(J="t"+J+"."+g.hW(v)),{cc:J}}return{}};
g.q.Tpi=function(){this.isSubtitlesOn()?(g.bh(this.EB)?aa(this,!1):AT(this,!1),dCL(this),Fh(this,null,!0)):this.QU()};
g.q.QU=function(){var v=NP(this)||!this.X?cP(this,!0):this.X;v&&this.ZM(v.vssId,"m");this.isSubtitlesOn()||Fh(this,NP(this)||!this.X?cP(this,!0):this.X,!0)};
g.q.isSubtitlesOn=function(){return!!this.loaded&&!!this.X&&!NP(this)};
g.q.APB=function(){var v=NP(this);Xh(this,v)?Fh(this,this.getAudioTrack().T,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.YF()&&(this.U=!1,this.X=null,this.T&&(this.T.dispose(),this.T=null)),this.nB()&&(v?Fh(this,cP(this,!1),!1):this.load()))};
g.q.W3=function(v){v&&(this.Ti={top:v.top,right:v.right,bottom:v.bottom,left:v.left,width:1-v.left-v.right,height:1-v.top-v.bottom},this.K.element.style.top=this.Ti.top*100+"%",this.K.element.style.left=this.Ti.left*100+"%",this.K.element.style.width=this.Ti.width*100+"%",this.K.element.style.height=this.Ti.height*100+"%",this.K.element.style.position="absolute",v=lJX(this))&&(this.K.element.style.width=v.width+"px",this.K.element.style.height=v.height+"px")};
g.q.onVideoDataChange=function(v,J){v==="newdata"&&(this.videoData=J,this.loaded&&this.unload(),this.U=!1,this.X=null,this.T&&(this.T.dispose(),this.T=null,this.player.Tr("captionschanged",{})),this.nB()&&this.load())};
g.q.getAudioTrack=function(){return this.WH&&this.player.getPresentingPlayerType()===2?this.videoData.Vu:this.player.getAudioTrack()};
g.q.lvB=function(){var v=this.S.LY();v&&!v.Sl()&&v.Vd();this.S.isFullscreen()?(this.J=this.xB=!0,this.loaded&&this.Tb()):(this.xB=this.EB.controlsType==="3",this.J=Pi_(this));Fh(this,this.X)};
g.q.ZC=function(){var v,J,G,K=(v=this.videoData.getPlayerResponse())==null?void 0:(J=v.captions)==null?void 0:(G=J.playerCaptionsTracklistRenderer)==null?void 0:G.openTranscriptCommand;K&&this.player.lw("innertubeCommand",K)};
g.q.ya=function(v,J,G){var K=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,V="";v&&(V=v.vssId,V=V.replace(K,""));var Y="";v&&v.getId()&&(Y=v.getId()||"");v&&v.getXtags()&&(v=v.getXtags(),v=v.replace(K,""),Y=Y.concat(";"+v));this.S.ya(J?V:"",J?Y:"",G)};
g.q.ZM=function(v,J){v=(v||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");v.length>0&&this.S.ZM(v,J)};
g.q.CU=function(){this.T&&this.T.CU()};
g.ys.FZ(g$,{uE:"smucd"});g.Vp("captions",g$);})(_yt_player);
