(function(g){var window=this;'use strict';var ol8=function(v){v.publish("autonavvisibility")},KRL=function(v,J){v.lw("onAutonavCoundownStarted",J)},V7F=function(v){var J,G,K;
return v==null?void 0:(J=v.playerOverlays)==null?void 0:(G=J.playerOverlayRenderer)==null?void 0:(K=G.autoplay)==null?void 0:K.playerOverlayAutoplayRenderer},ve=function(v,J,G){g.E3(v.element,"ytp-suggestion-set",!!J.videoId);
var K=J.playlistId;G=J.Us(G?G:"mqdefault.jpg");var V=null,Y=null;J instanceof g.pS&&(J.lengthText?(V=J.lengthText||null,Y=J.Rk||null):J.lengthSeconds&&(V=g.T$(J.lengthSeconds),Y=g.T$(J.lengthSeconds,!0)));var r=!!K;K=r&&g.ls(K).type==="RD";var E=J instanceof g.pS?J.isLivePlayback:null,e=J instanceof g.pS?J.isUpcoming:null,P=J.author,D=J.shortViewCount,t=J.publishedTimeText,B=[],I=[];P&&B.push(P);D&&(B.push(D),I.push(D));t&&I.push(t);G={title:J.title,author:P,author_and_views:B.join(" \u2022 "),aria_label:J.ariaLabel||
g.h6("Watch $TITLE",{TITLE:J.title}),duration:V,timestamp:Y,url:J.lh(),is_live:E,is_upcoming:e,is_list:r,is_mix:K,background:G?"background-image: url("+G+")":"",views_and_publish_time:I.join(" \u2022 "),autoplayAlternativeHeader:J.mL};J instanceof g.T3&&(G.playlist_length=J.playlistLength);v.update(G)},JH=function(v){var J=v.B(),G=J.L;
g.F.call(this,{Y:"a",D:"ytp-autonav-suggestion-card",V:{href:"{{url}}",target:G?J.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{Y:"div",n7:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],V:{style:"{{background}}"},W:[{Y:"div",V:{"aria-label":"{{timestamp}}"},n7:["ytp-autonav-timestamp"],At:"{{duration}}"},{Y:"div",n7:["ytp-autonav-live-stamp"],At:"Live"},{Y:"div",
n7:["ytp-autonav-upcoming-stamp"],At:"Upcoming"},{Y:"div",D:"ytp-autonav-list-overlay",W:[{Y:"div",D:"ytp-autonav-mix-text",At:"Mix"},{Y:"div",D:"ytp-autonav-mix-icon"}]}]},{Y:"div",n7:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],At:"{{title}}"},{Y:"div",n7:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],At:"{{author}}"},{Y:"div",n7:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],At:"{{views_and_publish_time}}"}]});this.S=v;this.suggestion=
null;this.T=G;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},Gi=function(v,J){J=J===void 0?!1:J;
g.F.call(this,{Y:"div",D:"ytp-autonav-endscreen-countdown-overlay"});var G=this;this.K=J;this.cancelCommand=this.j=void 0;this.Z=0;this.container=new g.F({Y:"div",D:"ytp-autonav-endscreen-countdown-container"});g.k(this,this.container);this.container.vH(this.element);J=v.B();var K=J.L;this.S=v;this.suggestion=null;this.onVideoDataChange("newdata",this.S.getVideoData());this.G(v,"videodatachange",this.onVideoDataChange);this.T=new g.F({Y:"div",D:"ytp-autonav-endscreen-upnext-container",V:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{Y:"div",D:"ytp-autonav-endscreen-upnext-header"},{Y:"div",D:"ytp-autonav-endscreen-upnext-alternative-header",At:"{{autoplayAlternativeHeader}}"},{Y:"a",D:"ytp-autonav-endscreen-link-container",V:{href:"{{url}}",target:K?J.N:""},W:[{Y:"div",D:"ytp-autonav-endscreen-upnext-thumbnail",V:{style:"{{background}}"},W:[{Y:"div",V:{"aria-label":"{{timestamp}}"},n7:["ytp-autonav-timestamp"],
At:"{{duration}}"},{Y:"div",n7:["ytp-autonav-live-stamp"],At:"Live"},{Y:"div",n7:["ytp-autonav-upcoming-stamp"],At:"Upcoming"}]},{Y:"div",D:"ytp-autonav-endscreen-video-info",W:[{Y:"div",D:"ytp-autonav-endscreen-premium-badge"},{Y:"div",D:"ytp-autonav-endscreen-upnext-title",At:"{{title}}"},{Y:"div",D:"ytp-autonav-endscreen-upnext-author",At:"{{author}}"},{Y:"div",D:"ytp-autonav-view-and-date",At:"{{views_and_publish_time}}"},{Y:"div",D:"ytp-autonav-author-and-view",At:"{{author_and_views}}"}]}]}]});
g.k(this,this.T);this.T.vH(this.container.element);K||this.G(this.T.p7("ytp-autonav-endscreen-link-container"),"click",this.IV);this.S.createClientVe(this.container.element,this,115127);this.S.createClientVe(this.T.p7("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.F({Y:"div",D:"ytp-autonav-overlay"});g.k(this,this.overlay);this.overlay.vH(this.container.element);this.X=new g.F({Y:"div",D:"ytp-autonav-endscreen-button-container"});g.k(this,this.X);this.X.vH(this.container.element);
this.cancelButton=new g.F({Y:"button",n7:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",J.C("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],V:{"aria-label":"Cancel autoplay"},At:"Cancel"});g.k(this,this.cancelButton);this.cancelButton.vH(this.X.element);this.cancelButton.listen("click",this.Eg,this);this.S.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.F({Y:"a",n7:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
J.C("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],V:{href:"{{url}}",role:"button","aria-label":"Play next video"},At:"Play Now"});g.k(this,this.playButton);this.playButton.vH(this.X.element);this.playButton.listen("click",this.IV,this);this.S.createServerVe(this.playButton.element,this.playButton,!0);(J=this.S.getVideoData())&&YZ_(this,J);this.L=new g.Qq(function(){riA(G)},500);
g.k(this,this.L);this.zZ();this.G(v,"autonavvisibility",this.zZ);this.S.C("web_autonav_color_transition")&&(this.G(v,"autonavchange",this.NU),this.G(v,"onAutonavCoundownStarted",this.XOi))},or=function(v){var J=v.S.Tg(!0,v.S.isFullscreen());
g.E3(v.container.element,"ytp-autonav-endscreen-small-mode",v.Ls(J));g.E3(v.container.element,"ytp-autonav-endscreen-is-premium",!!v.suggestion&&!!v.suggestion.SsH);g.E3(v.S.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!v.S.D6());g.E3(v.S.getRootNode(),"countdown-running",v.Hx());g.E3(v.container.element,"ytp-player-content",v.S.D6());g.ep(v.overlay.element,{width:J.width+"px"});if(!v.Hx()){v.S.D6()?qZG(v,Math.round(Elo(v)/1E3)):qZG(v);J=!!v.suggestion&&!!v.suggestion.mL;var G=v.S.D6()||
!J;g.E3(v.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!G&&J);g.E3(v.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",G&&!J);v.X.tP(v.S.D6());g.E3(v.element,"ytp-enable-w2w-color-transitions",epN(v))}},riA=function(v){var J=Elo(v),G=Math,K=G.min;
var V=v.Z?Date.now()-v.Z:0;G=K.call(G,V,J);qZG(v,Math.ceil((J-G)/1E3));J-G<=500&&v.Hx()?v.select(!0):v.Hx()&&v.L.start()},Elo=function(v){if(v.S.isFullscreen()){var J;
v=(J=v.S.getVideoData())==null?void 0:J.Ak;return v===-1||v===void 0?8E3:v}return v.S.wg()>=0?v.S.wg():g.DI(v.S.B().experiments,"autoplay_time")||1E4},YZ_=function(v,J){J=J.getWatchNextResponse();
var G,K;J=(G=V7F(J))==null?void 0:(K=G.nextButton)==null?void 0:K.buttonRenderer;v.j=J==null?void 0:J.navigationEndpoint;G=J==null?void 0:J.trackingParams;v.playButton&&G&&v.S.setTrackingParams(v.playButton.element,G)},epN=function(v){var J;
return!((J=v.S.getVideoData())==null||!J.watchToWatchTransitionRenderer)},qZG=function(v,J){J=J===void 0?-1:J;
v=v.T.p7("ytp-autonav-endscreen-upnext-header");g.PM(v);if(J>=0){J=String(J);var G="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],K="Up next in $SECONDS".indexOf(G);if(K>=0){v.appendChild(g.Eo("Up next in $SECONDS".slice(0,K)));var V=g.qh("span");g.Jz(V,"ytp-autonav-endscreen-upnext-header-countdown-number");g.In(V,J);v.appendChild(V);v.appendChild(g.Eo("Up next in $SECONDS".slice(K+G.length)));return}}g.In(v,"Up next")},Kx=function(v,J){g.F.call(this,{Y:"div",
n7:["html5-endscreen","ytp-player-content",J||"base-endscreen"]});this.created=!1;this.player=v},VN=function(v){g.F.call(this,{Y:"div",
n7:["ytp-upnext","ytp-player-content"],V:{"aria-label":"{{aria_label}}"},W:[{Y:"div",D:"ytp-cued-thumbnail-overlay-image",V:{style:"{{background}}"}},{Y:"span",D:"ytp-upnext-top",W:[{Y:"span",D:"ytp-upnext-header",At:"Up Next"},{Y:"span",D:"ytp-upnext-title",At:"{{title}}"},{Y:"span",D:"ytp-upnext-author",At:"{{author}}"}]},{Y:"a",D:"ytp-upnext-autoplay-icon",V:{role:"button",href:"{{url}}","aria-label":"Play next video"},W:[{Y:"svg",V:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
W:[{Y:"circle",D:"ytp-svg-autoplay-circle",V:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{Y:"circle",D:"ytp-svg-autoplay-ring",V:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{Y:"path",D:"ytp-svg-fill",V:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{Y:"span",D:"ytp-upnext-bottom",W:[{Y:"span",D:"ytp-upnext-cancel"},{Y:"span",D:"ytp-upnext-paused",
At:"Autoplay is paused"}]}]});this.api=v;this.cancelButton=null;this.j=this.p7("ytp-svg-autoplay-ring");this.Z=this.notification=this.T=this.suggestion=null;this.L=new g.Qq(this.h6,5E3,this);this.X=0;var J=this.p7("ytp-upnext-cancel");this.cancelButton=new g.F({Y:"button",n7:["ytp-upnext-cancel-button","ytp-button"],V:{tabindex:"0","aria-label":"Cancel autoplay"},At:"Cancel"});g.k(this,this.cancelButton);this.cancelButton.listen("click",this.Hb,this);this.cancelButton.vH(J);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.k(this,this.L);this.api.createClientVe(this.element,this,18788);J=this.p7("ytp-upnext-autoplay-icon");this.G(J,"click",this.uW);this.api.createClientVe(J,this,115130);this.Bk();this.G(v,"autonavvisibility",this.Bk);this.G(v,"mdxnowautoplaying",this.Vui);this.G(v,"mdxautoplaycanceled",this.fvt);g.E3(this.element,"ytp-upnext-mobile",this.api.B().X)},P78=function(v,J){if(J)return J;
if(v.api.isFullscreen()){var G;v=(G=v.api.getVideoData())==null?void 0:G.Ak;return v===-1||v===void 0?8E3:v}return v.api.wg()>=0?v.api.wg():g.DI(v.api.B().experiments,"autoplay_time")||1E4},DMT=function(v,J){J=P78(v,J);
var G=Math,K=G.min;var V=(0,g.yR)()-v.X;G=K.call(G,V,J);J=J===0?1:Math.min(G/J,1);v.j.setAttribute("stroke-dashoffset",""+-211*(J+1));J>=1&&v.Hx()&&v.api.getPresentingPlayerType()!==3?v.select(!0):v.Hx()&&v.T.start()},Yh=function(v){Kx.call(this,v,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.F({Y:"div",D:"ytp-suggestion-panel",W:[{Y:"div",n7:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],At:"More videos"}]});this.U=new g.F({Y:"div",D:"ytp-suggestions-container"});this.videos=[];this.Z=null;this.j=this.K=!1;this.X=new Gi(this.player);g.k(this,this.X);this.X.vH(this.element);v.getVideoData().Hv?this.T=this.X:(this.T=new VN(v),g.gr(this.player,this.T.element,4),g.k(this,this.T));this.overlay=new g.F({Y:"div",
D:"ytp-autonav-overlay-cancelled-state"});g.k(this,this.overlay);this.overlay.vH(this.element);this.L=new g.Zs(this);g.k(this,this.L);g.k(this,this.table);this.table.vH(this.element);this.table.show();g.k(this,this.U);this.U.vH(this.table.element);this.hide()},rY=function(v){var J=v.D6();
J!==v.j&&(v.j=J,ol8(v.player),v.j?(v.X!==v.T&&v.X.hide(),v.table.hide()):(v.X!==v.T&&v.X.show(),v.table.show()))},qs=function(v,J){g.F.call(this,{Y:"button",
n7:["ytp-watch-on-youtube-button","ytp-button"],At:"{{content}}"});this.S=v;this.buttonType=this.buttonType=J;this.FA();this.buttonType===2&&g.Vj(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.FA);this.tP(!0)},EW=function(v,J){Kx.call(this,v,"embeds-lite-endscreen");
this.S=v;this.T=J;this.S.createClientVe(this.element,this,156943);this.watchButton=new qs(v,2);g.k(this,this.watchButton);this.watchButton.vH(this.element);this.hide()},eq=function(v){var J=v.B(),G=g.x4||g.y5?{style:"will-change: opacity"}:void 0,K=J.L,V=["ytp-modern-videowall-still"];
J.X&&V.push("ytp-videowall-show-text");g.F.call(this,{Y:"a",n7:V,V:{href:"{{url}}",target:K?J.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{Y:"div",D:"ytp-modern-videowall-still-image",V:{style:"{{background}}"},W:[{Y:"span",D:"ytp-modern-videowall-still-info-duration",At:"{{duration}}"}]},{Y:"span",D:"ytp-modern-videowall-still-info",V:{"aria-hidden":"true"},W:[{Y:"span",D:"ytp-modern-videowall-still-info-bg",W:[{Y:"span",
D:"ytp-modern-videowall-still-info-content",V:G,W:[{Y:"span",D:"ytp-modern-videowall-still-info-title",At:"{{title}}"},{Y:"span",D:"ytp-modern-videowall-still-info-author",At:"{{author_and_views}}"},{Y:"span",D:"ytp-modern-videowall-still-info-live",At:"Live"}]}]}]},{Y:"span",n7:["ytp-modern-videowall-still-listlabel-regular","ytp-modern-videowall-still-listlabel"],V:{"aria-hidden":"true"},W:[{Y:"span",D:"ytp-modern-videowall-still-listlabel-icon"},"Playlist",{Y:"span",D:"ytp-modern-videowall-still-listlabel-length",
W:[" (",{Y:"span",At:"{{playlist_length}}"},")"]}]},{Y:"span",n7:["ytp-modern-videowall-still-listlabel-mix","ytp-modern-videowall-still-listlabel"],V:{"aria-hidden":"true"},W:[{Y:"span",D:"ytp-modern-videowall-still-listlabel-mix-icon"},"Mix",{Y:"span",D:"ytp-modern-videowall-still-listlabel-length",At:" (50+)"}]}]});this.suggestion=null;this.X=K;this.api=v;this.T=new g.Zs(this);g.k(this,this.T);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.T.G(v,"videodatachange",
this.onVideoDataChange);v.createServerVe(this.element,this);this.onVideoDataChange()},t7F=function(v){Kx.call(this,v,"videowall-endscreen");
var J=this;this.S=v;this.stills=[];this.Z=this.videoData=null;this.L=this.K=!1;this.U=null;g.Vj(this.element,"modern-videowall-endscreen");this.X=new g.Zs(this);g.k(this,this.X);this.j=new g.Qq(function(){g.Vj(J.element,"ytp-show-tiles")},0);
g.k(this,this.j);this.table=new g.en({Y:"div",D:"ytp-modern-endscreen-content"});g.k(this,this.table);this.table.vH(this.element);v.getVideoData().Hv?this.T=new Gi(v,!0):this.T=new VN(v);g.k(this,this.T);g.gr(this.player,this.T.element,4);v.createClientVe(this.element,this,158789);this.hide()},Pe=function(v){return g.X5(v.player)&&v.qC()&&!v.Z},Dj=function(v){var J=v.D6();
J!==v.K&&(v.K=J,ol8(v.player))},B5F=function(v){Kx.call(this,v,"subscribecard-endscreen");
this.T=new g.F({Y:"div",D:"ytp-subscribe-card",W:[{Y:"img",D:"ytp-author-image",V:{src:"{{profilePicture}}"}},{Y:"div",D:"ytp-subscribe-card-right",W:[{Y:"div",D:"ytp-author-name",At:"{{author}}"},{Y:"div",D:"html5-subscribe-button-container"}]}]});g.k(this,this.T);this.T.vH(this.element);var J=v.getVideoData();this.subscribeButton=new g.cv("Subscribe",null,"Unsubscribe",null,!0,!1,J.kN,J.subscribed,"trailer-endscreen",null,v,!1);g.k(this,this.subscribeButton);this.subscribeButton.vH(this.T.p7("html5-subscribe-button-container"));
this.G(v,"videodatachange",this.De);this.De();this.hide()},tH=function(v){var J=v.B(),G=g.x4||g.y5?{style:"will-change: opacity"}:void 0,K=J.L,V=["ytp-videowall-still"];
J.X&&V.push("ytp-videowall-show-text");g.F.call(this,{Y:"a",n7:V,V:{href:"{{url}}",target:K?J.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{Y:"div",D:"ytp-videowall-still-image",V:{style:"{{background}}"}},{Y:"span",D:"ytp-videowall-still-info",V:{"aria-hidden":"true"},W:[{Y:"span",D:"ytp-videowall-still-info-bg",W:[{Y:"span",D:"ytp-videowall-still-info-content",V:G,W:[{Y:"span",D:"ytp-videowall-still-info-title",At:"{{title}}"},
{Y:"span",D:"ytp-videowall-still-info-author",At:"{{author_and_views}}"},{Y:"span",D:"ytp-videowall-still-info-live",At:"Live"},{Y:"span",D:"ytp-videowall-still-info-duration",At:"{{duration}}"}]}]}]},{Y:"span",n7:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},W:[{Y:"span",D:"ytp-videowall-still-listlabel-icon"},"Playlist",{Y:"span",D:"ytp-videowall-still-listlabel-length",W:[" (",{Y:"span",At:"{{playlist_length}}"},")"]}]},{Y:"span",n7:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},W:[{Y:"span",D:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{Y:"span",D:"ytp-videowall-still-listlabel-length",At:" (50+)"}]}]});this.suggestion=null;this.X=K;this.api=v;this.T=new g.Zs(this);g.k(this,this.T);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.T.G(v,"videodatachange",this.onVideoDataChange);v.createServerVe(this.element,this);this.onVideoDataChange()},Be=function(v){Kx.call(this,v,"videowall-endscreen");
var J=this;this.S=v;this.Z=0;this.stills=[];this.L=this.videoData=null;this.j=this.U=!1;this.N=null;this.X=new g.Zs(this);g.k(this,this.X);this.K=new g.Qq(function(){g.Vj(J.element,"ytp-show-tiles")},0);
g.k(this,this.K);var G=new g.F({Y:"button",n7:["ytp-button","ytp-endscreen-previous"],V:{"aria-label":"Previous"},W:[g.d8()]});g.k(this,G);G.vH(this.element);G.listen("click",this.AK,this);this.table=new g.en({Y:"div",D:"ytp-endscreen-content"});g.k(this,this.table);this.table.vH(this.element);G=new g.F({Y:"button",n7:["ytp-button","ytp-endscreen-next"],V:{"aria-label":"Next"},W:[g.sN()]});g.k(this,G);G.vH(this.element);G.listen("click",this.bW,this);v.getVideoData().Hv?this.T=new Gi(v,!0):this.T=
new VN(v);g.k(this,this.T);g.gr(this.player,this.T.element,4);v.createClientVe(this.element,this,158789);this.hide()},Ir=function(v){return g.X5(v.player)&&v.qC()&&!v.L},hH=function(v){var J=v.D6();
J!==v.U&&(v.U=J,ol8(v.player))},zi=function(v){Kx.call(this,v,"watch-again-on-youtube-endscreen");
this.watchButton=new qs(v,1);g.k(this,this.watchButton);this.watchButton.vH(this.element);g.t88(v)&&(this.T=new g.AF(v),g.k(this,this.T),this.X=new g.F({Y:"div",n7:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],V:{tabIndex:"-1"},W:[this.T]}),g.k(this,this.X),this.T.vH(this.X.element),this.X.vH(this.element));v.createClientVe(this.element,this,156914);this.hide()},nl_=function(v){g.YQ.call(this,v);
var J=this;this.endScreen=null;this.X=this.T=this.Z=this.L=!1;this.listeners=new g.Zs(this);g.k(this,this.listeners);var G=v.B(),K=v.getVideoData();K=K&&K.limitedPlaybackDurationInSeconds!==0;g.E9(g.X9(G))&&K&&!g.SI(v)?(this.X=!0,this.endScreen=new EW(v,g.zT(v))):v.isEmbedsShortsMode()?this.endScreen=new zi(v):ID8(v)?(this.L=!0,hpF(this),this.T?this.endScreen=new Yh(v):G.C("delhi_modern_endscreen")?this.endScreen=new t7F(v):this.endScreen=new Be(v)):G.Es?this.endScreen=new B5F(v):this.endScreen=new Kx(v);
g.k(this,this.endScreen);g.gr(v,this.endScreen.element,4);zpo(this);this.listeners.G(v,"videodatachange",this.onVideoDataChange,this);this.listeners.G(v,g.VG("endscreen"),function(V){J.onCueRangeEnter(V)});
this.listeners.G(v,g.YM("endscreen"),function(V){J.onCueRangeExit(V)})},hpF=function(v){var J=v.player.getVideoData();
if(!J||v.T===J.rE&&v.Z===J.Hv)return!1;v.T=J.rE;v.Z=J.Hv;return!0},ID8=function(v){v=v.B();
return v.Vy&&!v.Es&&!v.disableOrganicUi},zpo=function(v){v.player.RA("endscreen");
var J=v.player.getVideoData();J=new g.o8(Math.max((J.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var G=new g.o8(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});v.player.oR([J,G])};
g.wr.prototype.wg=g.rw(14,function(){return this.app.wg()});
g.eo.prototype.wg=g.rw(13,function(){return this.getVideoData().FJ});
g.TT.prototype.Ai=g.rw(12,function(v){this.N$().Ai(v)});
g.ox.prototype.Ai=g.rw(11,function(v){this.T!==v&&(this.T=v,this.De())});
g.RO.prototype.Ai=g.rw(10,function(v){this.overflowButton&&this.overflowButton.Ai(v)});
g.TT.prototype.XD=g.rw(9,function(v){this.N$().XD(v)});
g.qg.prototype.XD=g.rw(8,function(v){this.X!==v&&(this.X=v,this.De())});
g.RO.prototype.XD=g.rw(7,function(v){this.shareButton&&this.shareButton.XD(v)});
g.TT.prototype.Cb=g.rw(6,function(v){this.N$().Cb(v)});
g.S6.prototype.Cb=g.rw(5,function(v){this.Ao!==v&&(this.Ao=v,this.UF())});
g.TT.prototype.Ju=g.rw(4,function(v){this.N$().Ju(v)});
g.RO.prototype.Ju=g.rw(3,function(v){this.bG!==v&&(this.bG=v,this.mZ())});g.z(JH,g.F);JH.prototype.select=function(){this.S.Gx(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.pX||void 0)&&this.S.logClick(this.element)};
JH.prototype.onClick=function(v){g.qI(v,this.S,this.T,this.suggestion.sessionData||void 0)&&this.select()};
JH.prototype.onKeyPress=function(v){switch(v.keyCode){case 13:case 32:v.defaultPrevented||(this.select(),v.preventDefault())}};g.z(Gi,g.F);g.q=Gi.prototype;g.q.FV=function(v){this.suggestion!==v&&(this.suggestion=v,ve(this.T,v),this.playButton.updateValue("url",this.suggestion.lh()),or(this))};
g.q.Hx=function(){return this.Z>0};
g.q.qp=function(){this.Hx()||(this.Z=Date.now(),riA(this),KRL(this.S,Elo(this)),g.E3(this.S.getRootNode(),"countdown-running",this.Hx()))};
g.q.AN=function(){this.PU();riA(this);var v=this.T.p7("ytp-autonav-endscreen-upnext-header");v&&g.In(v,"Up next")};
g.q.PU=function(){this.Hx()&&(this.L.stop(),this.Z=0)};
g.q.select=function(v){this.S.nextVideo(!1,v===void 0?!1:v);this.PU()};
g.q.IV=function(v){g.qI(v,this.S)&&(v.currentTarget===this.playButton.element?this.S.logClick(this.playButton.element):v.currentTarget===this.T.p7("ytp-autonav-endscreen-link-container")&&(v=this.T.p7("ytp-autonav-endscreen-link-container"),this.S.logVisibility(v,!0),this.S.logClick(v)),this.j?(this.S.lw("innertubeCommand",this.j),this.PU()):this.select())};
g.q.Eg=function(){this.S.logClick(this.cancelButton.element);g.UM(this.S,!0);this.cancelCommand&&this.S.lw("innertubeCommand",this.cancelCommand)};
g.q.onVideoDataChange=function(v,J){YZ_(this,J);v=J.getWatchNextResponse();var G,K;v=(G=V7F(v))==null?void 0:(K=G.cancelButton)==null?void 0:K.buttonRenderer;this.cancelCommand=v==null?void 0:v.command};
g.q.XOi=function(v){if(epN(this)){var J=this.S.getVideoData().watchToWatchTransitionRenderer,G=J==null?void 0:J.fromColorPaletteDark;J=J==null?void 0:J.toColorPaletteDark;if(G&&J){var K=this.element;K.style.setProperty("--w2w-start-background-color",g.kp(G.surgeColor));K.style.setProperty("--w2w-start-primary-text-color",g.kp(G.primaryTitleColor));K.style.setProperty("--w2w-start-secondary-text-color",g.kp(G.secondaryTitleColor));K.style.setProperty("--w2w-end-background-color",g.kp(J.surgeColor));
K.style.setProperty("--w2w-end-primary-text-color",g.kp(J.primaryTitleColor));K.style.setProperty("--w2w-end-secondary-text-color",g.kp(J.secondaryTitleColor));K.style.setProperty("--w2w-animation-duration",v+"ms")}g.E3(this.element,"ytp-w2w-animate",!0)}};
g.q.NU=function(v){this.S.C("web_autonav_color_transition")&&v!==2&&g.E3(this.element,"ytp-w2w-animate",!1)};
g.q.zZ=function(){var v=this.S.D6();this.K&&this.TG!==v&&this.tP(v);or(this);this.S.logVisibility(this.container.element,v);this.S.logVisibility(this.cancelButton.element,v);this.S.logVisibility(this.T.p7("ytp-autonav-endscreen-link-container"),v);this.S.logVisibility(this.playButton.element,v)};
g.q.Ls=function(v){return v.width<400||v.height<459};g.z(Kx,g.F);g.q=Kx.prototype;g.q.create=function(){this.created=!0};
g.q.destroy=function(){this.created=!1};
g.q.qC=function(){return!1};
g.q.D6=function(){return!1};
g.q.nu=function(){return!1};g.z(VN,g.F);g.q=VN.prototype;g.q.h6=function(){this.notification&&(this.L.stop(),this.YL(this.Z),this.Z=null,this.notification.close(),this.notification=null)};
g.q.FV=function(v){this.suggestion=v;ve(this,v,"hqdefault.jpg")};
g.q.Bk=function(){this.tP(this.api.D6());this.api.logVisibility(this.element,this.api.D6());this.api.logVisibility(this.p7("ytp-upnext-autoplay-icon"),this.api.D6());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.D6())};
g.q.o5B=function(){window.focus();this.h6()};
g.q.qp=function(v){var J=this;this.Hx()||(g.YZ("a11y-announce","Up Next "+this.suggestion.title),this.X=(0,g.yR)(),this.T=new g.Qq(function(){DMT(J,v)},25),DMT(this,v),KRL(this.api,P78(this,v)));
g.rz(this.element,"ytp-upnext-autoplay-paused")};
g.q.hide=function(){g.F.prototype.hide.call(this)};
g.q.Hx=function(){return!!this.T};
g.q.AN=function(){this.PU();this.X=(0,g.yR)();DMT(this);g.Vj(this.element,"ytp-upnext-autoplay-paused")};
g.q.PU=function(){this.Hx()&&(this.T.dispose(),this.T=null)};
g.q.select=function(v){v=v===void 0?!1:v;if(this.api.B().C("autonav_notifications")&&v&&window.Notification&&typeof document.hasFocus==="function"){var J=Notification.permission;J==="default"?Notification.requestPermission():J!=="granted"||document.hasFocus()||(this.h6(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Us()}),this.Z=this.G(this.notification,"click",this.o5B),this.L.start())}this.PU();this.api.nextVideo(!1,v)};
g.q.uW=function(v){!g.BM(this.cancelButton.element,v.target)&&g.qI(v,this.api)&&(this.api.D6()&&this.api.logClick(this.p7("ytp-upnext-autoplay-icon")),this.select())};
g.q.Hb=function(){this.api.D6()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.UM(this.api,!0)};
g.q.Vui=function(v){this.api.getPresentingPlayerType();this.show();this.qp(v)};
g.q.fvt=function(){this.api.getPresentingPlayerType();this.PU();this.hide()};
g.q.X4=function(){this.PU();this.h6();g.F.prototype.X4.call(this)};g.z(Yh,Kx);g.q=Yh.prototype;g.q.create=function(){Kx.prototype.create.call(this);this.L.G(this.player,"appresize",this.S0);this.L.G(this.player,"onVideoAreaChange",this.S0);this.L.G(this.player,"videodatachange",this.onVideoDataChange);this.L.G(this.player,"autonavchange",this.rY);this.L.G(this.player,"onAutonavCancelled",this.oN);this.onVideoDataChange()};
g.q.show=function(){Kx.prototype.show.call(this);(this.K||this.Z&&this.Z!==this.videoData.clientPlaybackNonce)&&g.UM(this.player,!1);g.X5(this.player)&&this.qC()&&!this.Z?(rY(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.qp():this.videoData.autonavState===3&&this.T.AN()):(g.UM(this.player,!0),rY(this));this.S0()};
g.q.hide=function(){Kx.prototype.hide.call(this);this.T.AN();rY(this)};
g.q.S0=function(){var v=this.player.Tg(!0,this.player.isFullscreen());rY(this);or(this.X);g.E3(this.element,"ytp-autonav-cancelled-small-mode",this.Ls(v));g.E3(this.element,"ytp-autonav-cancelled-tiny-mode",this.m3(v));g.E3(this.element,"ytp-autonav-cancelled-mini-mode",v.width<=400||v.height<=360);this.overlay&&g.ep(this.overlay.element,{width:v.width+"px"});if(!this.j)for(v=0;v<this.videos.length;v++)g.E3(this.videos[v].element,"ytp-suggestion-card-with-margin",v%2===1)};
g.q.onVideoDataChange=function(){var v=this.player.getVideoData();if(this.videoData!==v&&v){this.videoData=v;if((v=this.videoData.suggestions)&&v.length||this.player.C("web_player_autonav_empty_suggestions_fix")){var J=g.$J(this.videoData);J&&(this.T.FV(J),this.T!==this.X&&this.X.FV(J))}if(v&&v.length)for(J=0;J<dMG.length;++J){var G=dMG[J];if(v&&v[G]){this.videos[J]=new JH(this.player);var K=this.videos[J];G=v[G];K.suggestion!==G&&(K.suggestion=G,ve(K,G));g.k(this,this.videos[J]);this.videos[J].vH(this.U.element)}}this.S0()}};
g.q.rY=function(v){v===1?(this.K=!1,this.Z=this.videoData.clientPlaybackNonce,this.T.PU(),this.TG&&this.S0()):(this.K=!0,this.D6()&&(v===2?this.T.qp():v===3&&this.T.AN()))};
g.q.oN=function(v){v?this.rY(1):(this.Z=null,this.K=!1)};
g.q.qC=function(){return this.videoData.autonavState!==1};
g.q.Ls=function(v){return(v.width<910||v.height<459)&&!this.m3(v)&&!(v.width<=400||v.height<=360)};
g.q.m3=function(v){return v.width<800&&!(v.width<=400||v.height<=360)};
g.q.D6=function(){return this.TG&&g.X5(this.player)&&this.qC()&&!this.Z};
var dMG=[1,3,2,4];g.z(qs,g.F);g.q=qs.prototype;g.q.FA=function(){switch(this.buttonType){case 1:var v="Watch again on YouTube";var J=156915;break;case 2:v="Continue watching on YouTube";J=156942;break;default:v="Continue watching on YouTube",J=156942}this.update({content:v});this.S.hasVe(this.element)&&this.S.destroyVe(this.element);this.S.createClientVe(this.element,this,J)};
g.q.onClick=function(v){this.S.C("web_player_log_click_before_generating_ve_conversion_params")&&this.S.logClick(this.element);g.Ev(this.getVideoUrl(),this.S,v);this.S.C("web_player_log_click_before_generating_ve_conversion_params")||this.S.logClick(this.element)};
g.q.getVideoUrl=function(){var v=!0;switch(this.buttonType){case 1:v=!0;break;case 2:v=!1}v=this.S.getVideoUrl(v,!1,!1,!0);var J=this.S.B();if(g.Of(J)){var G={};g.Of(J)&&g.Dw(this.S,"addEmbedsConversionTrackingParams",[G]);v=g.vt(v,G)}return v};
g.q.logVisibility=function(){this.S.logVisibility(this.element,this.TG&&this.J)};
g.q.show=function(){g.F.prototype.show.call(this);this.logVisibility()};
g.q.hide=function(){g.F.prototype.hide.call(this);this.logVisibility()};
g.q.I$=function(v){g.F.prototype.I$.call(this,v);this.logVisibility()};g.z(EW,Kx);EW.prototype.show=function(){this.player.getPlayerState()!==3&&(Kx.prototype.show.call(this),this.T.Ju(!0),this.T.XD(!0),this.S.B().G4||this.T.Ai(!0),this.S.logVisibility(this.element,!0),this.watchButton.I$(!0))};
EW.prototype.hide=function(){Kx.prototype.hide.call(this);this.T.Ju(!1);this.T.XD(!1);this.T.Ai(!1);this.S.logVisibility(this.element,!1);this.watchButton.I$(!1)};g.z(eq,g.F);eq.prototype.select=function(){this.api.Gx(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.pX||void 0)&&this.api.logClick(this.element)};
eq.prototype.onClick=function(v){if(g.Of(this.api.B())&&this.api.C("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var J=this.suggestion.lh(),G={};g.fm(this.api,G);J=g.vt(J,G);g.Ev(J,this.api,v)}else g.qI(v,this.api,this.X,this.suggestion.sessionData||void 0)&&this.select()};
eq.prototype.onKeyPress=function(v){switch(v.keyCode){case 13:case 32:v.defaultPrevented||(this.select(),v.preventDefault())}};
eq.prototype.onVideoDataChange=function(){var v=this.api.getVideoData(),J=this.api.B();this.X=v.aR?!1:J.L};g.z(t7F,Kx);g.q=t7F.prototype;g.q.create=function(){Kx.prototype.create.call(this);var v=this.player.getVideoData();v&&(this.videoData=v);this.lN();this.X.G(this.player,"appresize",this.lN);this.X.G(this.player,"onVideoAreaChange",this.lN);this.X.G(this.player,"videodatachange",this.onVideoDataChange);this.X.G(this.player,"autonavchange",this.vz);this.X.G(this.player,"onAutonavCancelled",this.Tj);v=this.videoData.autonavState;v!==this.U&&this.vz(v);this.X.G(this.element,"transitionend",this.Qm)};
g.q.destroy=function(){g.O9(this.X);g.qS(this.stills);this.stills=[];Kx.prototype.destroy.call(this);g.rz(this.element,"ytp-show-tiles");this.j.stop();this.U=this.videoData.autonavState};
g.q.qC=function(){return this.videoData.autonavState!==1};
g.q.show=function(){var v=this.TG;Kx.prototype.show.call(this);g.rz(this.element,"ytp-show-tiles");this.player.B().X?g.CM(this.j):this.j.start();(this.L||this.Z&&this.Z!==this.videoData.clientPlaybackNonce)&&g.UM(this.player,!1);Pe(this)?(Dj(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.qp():this.videoData.autonavState===3&&this.T.AN()):(g.UM(this.player,!0),Dj(this));v!==this.TG&&this.player.logVisibility(this.element,!0)};
g.q.hide=function(){var v=this.TG;Kx.prototype.hide.call(this);this.T.AN();Dj(this);v!==this.TG&&this.player.logVisibility(this.element,!1)};
g.q.Qm=function(v){v.target===this.element&&this.lN()};
g.q.lN=function(){var v,J,G,K;var V=((v=this.videoData)==null?0:(J=v.suggestions)==null?0:J.length)?(G=this.videoData)==null?void 0:G.suggestions:[(K=this.videoData)==null?void 0:g.$J(K)];if(V.length){J=this.S.Tg(!0,this.S.isFullscreen());v=Math.floor((J.width-64+16)/(g.nk(J.width*.27,250,450)+16));J=Math.min(3,Math.floor((J.height-64)/((J.width-64-(v-1)*16)/v*.5625+70)));g.qR(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.Vj(this.element,"ytp-modern-endscreen-limit-rows-"+J);g.E3(this.element,"ytp-modern-endscreen-single-item",v===1);g.E3(this.element,"ytp-modern-endscreen-row-0",J===0);v=this.table.element;v.ariaLive="polite";this.T.FV(g.$J(this.videoData));this.T instanceof Gi&&or(this.T);g.E3(this.element,"ytp-endscreen-takeover",Pe(this));Dj(this);J=0;v.ariaBusy="true";G=V.length;for(K=0;K<G;K++){var Y=K%G,r=this.stills[K];r||(r=new eq(this.player),this.stills[K]=r,v.appendChild(r.element));Y=V[Y];if(r.suggestion!==
Y){r.suggestion=Y;var E=r.api.B();ve(r,Y,"hqdefault.jpg");if(g.Of(E)&&!r.api.C("web_player_log_click_before_generating_ve_conversion_params")){E=Y.lh();var e={};g.Dw(r.api,"addEmbedsConversionTrackingParams",[e]);E=g.vt(E,e);r.updateValue("url",E)}(Y=(Y=Y.sessionData)&&Y.itct)&&r.api.setTrackingParams(r.element,Y)}J++}this.stills.length=J}};
g.q.onVideoDataChange=function(){var v=this.player.getVideoData(1);this.videoData!==v&&(v!=null&&g.$J(v)?(this.videoData=v,this.lN()):this.player.uw("missg",{vid:(v==null?void 0:v.videoId)||"",cpn:(v==null?void 0:v.clientPlaybackNonce)||""}))};
g.q.nu=function(){return this.T.Hx()};
g.q.vz=function(v){v===1?(this.L=!1,this.Z=this.videoData.clientPlaybackNonce,this.T.PU(),this.TG&&this.lN()):(this.L=!0,this.TG&&Pe(this)&&(v===2?this.T.qp():v===3&&this.T.AN()))};
g.q.Tj=function(v){if(v){for(v=0;v<this.stills.length;v++)this.S.logVisibility(this.stills[v].element,!0);this.vz(1)}else this.Z=null,this.L=!1;this.lN()};
g.q.D6=function(){return this.TG&&Pe(this)};g.z(B5F,Kx);B5F.prototype.De=function(){var v=this.player.getVideoData();this.T.update({profilePicture:v.profilePicture,author:v.author});this.subscribeButton.channelId=v.kN;var J=this.subscribeButton;v.subscribed?J.T():J.X()};g.z(tH,g.F);tH.prototype.select=function(){this.api.Gx(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.pX||void 0)&&this.api.logClick(this.element)};
tH.prototype.onClick=function(v){if(g.Of(this.api.B())&&this.api.C("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var J=this.suggestion.lh(),G={};g.fm(this.api,G);J=g.vt(J,G);g.Ev(J,this.api,v)}else g.qI(v,this.api,this.X,this.suggestion.sessionData||void 0)&&this.select()};
tH.prototype.onKeyPress=function(v){switch(v.keyCode){case 13:case 32:v.defaultPrevented||(this.select(),v.preventDefault())}};
tH.prototype.onVideoDataChange=function(){var v=this.api.getVideoData(),J=this.api.B();this.X=v.aR?!1:J.L};g.z(Be,Kx);g.q=Be.prototype;g.q.create=function(){Kx.prototype.create.call(this);var v=this.player.getVideoData();v&&(this.videoData=v);this.V_();this.X.G(this.player,"appresize",this.V_);this.X.G(this.player,"onVideoAreaChange",this.V_);this.X.G(this.player,"videodatachange",this.onVideoDataChange);this.X.G(this.player,"autonavchange",this.L_);this.X.G(this.player,"onAutonavCancelled",this.tK);v=this.videoData.autonavState;v!==this.N&&this.L_(v);this.X.G(this.element,"transitionend",this.Xr)};
g.q.destroy=function(){g.O9(this.X);g.qS(this.stills);this.stills=[];Kx.prototype.destroy.call(this);g.rz(this.element,"ytp-show-tiles");this.K.stop();this.N=this.videoData.autonavState};
g.q.qC=function(){return this.videoData.autonavState!==1};
g.q.show=function(){var v=this.TG;Kx.prototype.show.call(this);g.rz(this.element,"ytp-show-tiles");this.player.B().X?g.CM(this.K):this.K.start();(this.j||this.L&&this.L!==this.videoData.clientPlaybackNonce)&&g.UM(this.player,!1);Ir(this)?(hH(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.qp():this.videoData.autonavState===3&&this.T.AN()):(g.UM(this.player,!0),hH(this));v!==this.TG&&this.player.logVisibility(this.element,!0)};
g.q.hide=function(){var v=this.TG;Kx.prototype.hide.call(this);this.T.AN();hH(this);v!==this.TG&&this.player.logVisibility(this.element,!1)};
g.q.Xr=function(v){v.target===this.element&&this.V_()};
g.q.V_=function(){var v,J,G,K;var V=((v=this.videoData)==null?0:(J=v.suggestions)==null?0:J.length)?(G=this.videoData)==null?void 0:G.suggestions:[(K=this.videoData)==null?void 0:g.$J(K)];if(V.length){g.Vj(this.element,"ytp-endscreen-paginate");var Y=this.S.Tg(!0,this.S.isFullscreen());if(v=g.zT(this.S))v=v.XQ()?48:32,Y.width-=v*2;var r=Y.width/Y.height;K=96/54;J=v=2;var E=Math.max(Y.width/96,2),e=Math.max(Y.height/54,2);G=V.length;var P=G*4;for(P-=4;P>0&&(v<E||J<e);){var D=v/2,t=J/2,B=v<=E-2&&P>=
t*4,I=J<=e-2&&P>=D*4;if((D+1)/t*K/r>r/(D/(t+1)*K)&&I)P-=D*4,J+=2;else if(B)P-=t*4,v+=2;else if(I)P-=D*4,J+=2;else break}K=!1;P>=12&&G*4-P<=6&&(J>=4||v>=4)&&(K=!0);P=v*96;E=J*54;r=P/E<r?Y.height/E:Y.width/P;r=Math.min(r,2);P=Math.floor(Math.min(Y.width,P*r));E=Math.floor(Math.min(Y.height,E*r));Y=this.table.element;Y.ariaLive="polite";g.RY(Y,P,E);g.ep(Y,{marginLeft:P/-2+"px",marginTop:E/-2+"px"});this.T.FV(g.$J(this.videoData));this.T instanceof Gi&&or(this.T);g.E3(this.element,"ytp-endscreen-takeover",
Ir(this));hH(this);P+=4;E+=4;r=0;Y.ariaBusy="true";for(e=0;e<v;e++)for(D=0;D<J;D++)if(t=r,I=0,K&&e>=v-2&&D>=J-2?I=1:D%2===0&&e%2===0&&(D<2&&e<2?D===0&&e===0&&(I=2):I=2),t=g.dd(t+this.Z,G),I!==0){B=this.stills[r];B||(B=new tH(this.player),this.stills[r]=B,Y.appendChild(B.element));var h=Math.floor(E*D/J),R=Math.floor(P*e/v),T=Math.floor(E*(D+I)/J)-h-4,L=Math.floor(P*(e+I)/v)-R-4;g.zK(B.element,R,h);g.RY(B.element,L,T);g.ep(B.element,"transitionDelay",(D+e)/20+"s");g.E3(B.element,"ytp-videowall-still-mini",
I===1);g.E3(B.element,"ytp-videowall-still-large",I>2);I=Math.max(L,T);g.E3(B.element,"ytp-videowall-still-round-large",I>=256);g.E3(B.element,"ytp-videowall-still-round-medium",I>96&&I<256);g.E3(B.element,"ytp-videowall-still-round-small",I<=96);t=V[t];B.suggestion!==t&&(B.suggestion=t,I=B.api.B(),h=g.K7(B.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",ve(B,t,h),g.Of(I)&&!B.api.C("web_player_log_click_before_generating_ve_conversion_params")&&(I=t.lh(),h={},g.Dw(B.api,"addEmbedsConversionTrackingParams",
[h]),I=g.vt(I,h),B.updateValue("url",I)),(t=(t=t.sessionData)&&t.itct)&&B.api.setTrackingParams(B.element,t));r++}Y.ariaBusy="false";g.E3(this.element,"ytp-endscreen-paginate",r<G);for(V=this.stills.length-1;V>=r;V--)v=this.stills[V],g.tx(v.element),g.rT(v);this.stills.length=r}};
g.q.onVideoDataChange=function(){var v=this.player.getVideoData(1);this.videoData!==v&&(v!=null&&g.$J(v)?(this.Z=0,this.videoData=v,this.V_()):this.player.uw("missg",{vid:(v==null?void 0:v.videoId)||"",cpn:(v==null?void 0:v.clientPlaybackNonce)||""}))};
g.q.bW=function(){this.Z+=this.stills.length;this.V_()};
g.q.AK=function(){this.Z-=this.stills.length;this.V_()};
g.q.nu=function(){return this.T.Hx()};
g.q.L_=function(v){v===1?(this.j=!1,this.L=this.videoData.clientPlaybackNonce,this.T.PU(),this.TG&&this.V_()):(this.j=!0,this.TG&&Ir(this)&&(v===2?this.T.qp():v===3&&this.T.AN()))};
g.q.tK=function(v){if(v){for(v=0;v<this.stills.length;v++)this.S.logVisibility(this.stills[v].element,!0);this.L_(1)}else this.L=null,this.j=!1;this.V_()};
g.q.D6=function(){return this.TG&&Ir(this)};g.z(zi,Kx);zi.prototype.hasSuggestions=function(){var v;return(v=this.T)==null?void 0:v.hasSuggestions()};
zi.prototype.show=function(){if(this.player.getPlayerState()!==3){Kx.prototype.show.call(this);var v=this.X;if(v){var J=this.T.hasSuggestions();g.E3(this.element,"ytp-shorts-branded-ui",J);J?v.show():v.hide()}var G;(G=g.zT(this.player))==null||G.Cb(!0);this.player.logVisibility(this.element,!0);this.watchButton.I$(!0)}};
zi.prototype.hide=function(){Kx.prototype.hide.call(this);var v;(v=g.zT(this.player))==null||v.Cb(!1);this.player.logVisibility(this.element,!1);this.watchButton.I$(!1)};g.z(nl_,g.YQ);g.q=nl_.prototype;g.q.nB=function(){var v=this.player.getVideoData(),J=v.mutedAutoplay&&(v.limitedPlaybackDurationInSeconds>0||v.endSeconds>0||v.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.X)&&!J)return!0;var G;var K=!!((v==null?0:g.$J(v))||(v==null?0:(G=v.suggestions)==null?0:G.length));K=!ID8(this.player)||K;v=v.Lj;G=this.player.Dh();return K&&!v&&!G&&!J};
g.q.D6=function(){return this.endScreen.D6()};
g.q.hUr=function(){return this.D6()?this.endScreen.nu():!1};
g.q.X4=function(){this.player.RA("endscreen");g.YQ.prototype.X4.call(this)};
g.q.load=function(){var v=this.player.getVideoData();var J=v.transitionEndpointAtEndOfStream;if(J&&J.videoId){var G=this.player.c$().AI.get("heartbeat"),K=g.$J(v);!K||J.videoId!==K.videoId||v.Kl?(this.player.Gx(J.videoId,void 0,void 0,!0,!0,J),G&&G.aC("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),v=!0):v=!1}else v=!1;v||(g.YQ.prototype.load.call(this),this.endScreen.show())};
g.q.unload=function(){g.YQ.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.q.onCueRangeEnter=function(v){this.nB()&&(this.endScreen.created||this.endScreen.create(),v.getId()==="load"&&this.load())};
g.q.onCueRangeExit=function(v){v.getId()==="load"&&this.loaded&&this.unload()};
g.q.onVideoDataChange=function(){zpo(this);this.L&&hpF(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.T?this.endScreen=new Yh(this.player):this.endScreen=new Be(this.player),g.k(this,this.endScreen),g.gr(this.player,this.endScreen.element,4))};g.Vp("endscreen",nl_);})(_yt_player);
